////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSD91RUNx_H_
#define _MSD91RUNx_H_

#define PAD_NC 9999
#define PAD_GND 0

#define PIN_6 PAD_RX2P_B
#define PAD_RX2P_B 149
#define GPIO_PAD_149 GPIO148
#ifndef PIN_6_IS_GPIO
#define PIN_6_IS_GPIO 0
#endif 
#ifndef PAD_RX2P_B_IS_GPIO
#define PAD_RX2P_B_IS_GPIO PIN_6_IS_GPIO
#endif 

#define PIN_10 PAD_RX0N_A
#define PAD_RX0N_A 136
#define GPIO_PAD_136 GPIO135
#ifndef PIN_10_IS_GPIO
#define PIN_10_IS_GPIO 0
#endif 
#ifndef PAD_RX0N_A_IS_GPIO
#define PAD_RX0N_A_IS_GPIO PIN_10_IS_GPIO
#endif 

#define PIN_8 PAD_RXCN_A
#define PAD_RXCN_A 134
#define GPIO_PAD_134 GPIO133
#ifndef PIN_8_IS_GPIO
#define PIN_8_IS_GPIO 0
#endif 
#ifndef PAD_RXCN_A_IS_GPIO
#define PAD_RXCN_A_IS_GPIO PIN_8_IS_GPIO
#endif 

#define PIN_11 PAD_RX0P_A
#define PAD_RX0P_A 137
#define GPIO_PAD_137 GPIO136
#ifndef PIN_11_IS_GPIO
#define PIN_11_IS_GPIO 0
#endif 
#ifndef PAD_RX0P_A_IS_GPIO
#define PAD_RX0P_A_IS_GPIO PIN_11_IS_GPIO
#endif 

#define PIN_9 PAD_RXCP_A
#define PAD_RXCP_A 135
#define GPIO_PAD_135 GPIO134
#ifndef PIN_9_IS_GPIO
#define PIN_9_IS_GPIO 0
#endif 
#ifndef PAD_RXCP_A_IS_GPIO
#define PAD_RXCP_A_IS_GPIO PIN_9_IS_GPIO
#endif 

#define PIN_14 PAD_RX2N_A
#define PAD_RX2N_A 140
#define GPIO_PAD_140 GPIO139
#ifndef PIN_14_IS_GPIO
#define PIN_14_IS_GPIO 0
#endif 
#ifndef PAD_RX2N_A_IS_GPIO
#define PAD_RX2N_A_IS_GPIO PIN_14_IS_GPIO
#endif 

#define PIN_12 PAD_RX1N_A
#define PAD_RX1N_A 138
#define GPIO_PAD_138 GPIO137
#ifndef PIN_12_IS_GPIO
#define PIN_12_IS_GPIO 0
#endif 
#ifndef PAD_RX1N_A_IS_GPIO
#define PAD_RX1N_A_IS_GPIO PIN_12_IS_GPIO
#endif 

#define PIN_15 PAD_RX2P_A
#define PAD_RX2P_A 141
#define GPIO_PAD_141 GPIO140
#ifndef PIN_15_IS_GPIO
#define PIN_15_IS_GPIO 0
#endif 
#ifndef PAD_RX2P_A_IS_GPIO
#define PAD_RX2P_A_IS_GPIO PIN_15_IS_GPIO
#endif 

#define PIN_13 PAD_RX1P_A
#define PAD_RX1P_A 139
#define GPIO_PAD_139 GPIO138
#ifndef PIN_13_IS_GPIO
#define PIN_13_IS_GPIO 0
#endif 
#ifndef PAD_RX1P_A_IS_GPIO
#define PAD_RX1P_A_IS_GPIO PIN_13_IS_GPIO
#endif 

#define PIN_16 PADA_HSYNC0
#define PADA_HSYNC0 106
#define GPIO_PAD_106 GPIO105
#ifndef PIN_16_IS_GPIO
#define PIN_16_IS_GPIO 0
#endif 
#ifndef PADA_HSYNC0_IS_GPIO
#define PADA_HSYNC0_IS_GPIO PIN_16_IS_GPIO
#endif 

#define PIN_17 PADA_BIN0P
#define PADA_BIN0P 118
#define GPIO_PAD_118 GPIO117
#ifndef PIN_17_IS_GPIO
#define PIN_17_IS_GPIO 0
#endif 
#ifndef PADA_BIN0P_IS_GPIO
#define PADA_BIN0P_IS_GPIO PIN_17_IS_GPIO
#endif 

#define PADA_BIN0M 9999
#ifndef PADA_BIN0M_IS_GPIO
#define PADA_BIN0M_IS_GPIO 0
#endif 

#define PIN_18 PADA_GIN0P
#define PADA_GIN0P 114
#define GPIO_PAD_114 GPIO113
#ifndef PIN_18_IS_GPIO
#define PIN_18_IS_GPIO 0
#endif 
#ifndef PADA_GIN0P_IS_GPIO
#define PADA_GIN0P_IS_GPIO PIN_18_IS_GPIO
#endif 

#define PIN_19 PADA_GIN0M
#define PADA_GIN0M 116
#define GPIO_PAD_116 GPIO115
#ifndef PIN_19_IS_GPIO
#define PIN_19_IS_GPIO 0
#endif 
#ifndef PADA_GIN0M_IS_GPIO
#define PADA_GIN0M_IS_GPIO PIN_19_IS_GPIO
#endif 

#define PIN_20 PADA_RIN0P
#define PADA_RIN0P 110
#define GPIO_PAD_110 GPIO109
#ifndef PIN_20_IS_GPIO
#define PIN_20_IS_GPIO 0
#endif 
#ifndef PADA_RIN0P_IS_GPIO
#define PADA_RIN0P_IS_GPIO PIN_20_IS_GPIO
#endif 

#define PADA_RIN0M 9999
#ifndef PADA_RIN0M_IS_GPIO
#define PADA_RIN0M_IS_GPIO 0
#endif 

#define PIN_21 PADA_VSYNC0
#define PADA_VSYNC0 108
#define GPIO_PAD_108 GPIO107
#ifndef PIN_21_IS_GPIO
#define PIN_21_IS_GPIO 0
#endif 
#ifndef PADA_VSYNC0_IS_GPIO
#define PADA_VSYNC0_IS_GPIO PIN_21_IS_GPIO
#endif 

#define PADA_HSYNC1 9999
#ifndef PADA_HSYNC1_IS_GPIO
#define PADA_HSYNC1_IS_GPIO 0
#endif 

#define PIN_23 PADA_BIN1P
#define PADA_BIN1P 119
#define GPIO_PAD_119 GPIO118
#ifndef PIN_23_IS_GPIO
#define PIN_23_IS_GPIO 0
#endif 
#ifndef PADA_BIN1P_IS_GPIO
#define PADA_BIN1P_IS_GPIO PIN_23_IS_GPIO
#endif 

#define PADA_BIN1M 9999
#ifndef PADA_BIN1M_IS_GPIO
#define PADA_BIN1M_IS_GPIO 0
#endif 

#define PIN_24 PADA_GIN1P
#define PADA_GIN1P 115
#define GPIO_PAD_115 GPIO114
#ifndef PIN_24_IS_GPIO
#define PIN_24_IS_GPIO 0
#endif 
#ifndef PADA_GIN1P_IS_GPIO
#define PADA_GIN1P_IS_GPIO PIN_24_IS_GPIO
#endif 

#define PIN_25 PADA_GIN1M
#define PADA_GIN1M 117
#define GPIO_PAD_117 GPIO116
#ifndef PIN_25_IS_GPIO
#define PIN_25_IS_GPIO 0
#endif 
#ifndef PADA_GIN1M_IS_GPIO
#define PADA_GIN1M_IS_GPIO PIN_25_IS_GPIO
#endif 

#define PIN_26 PADA_RIN1P
#define PADA_RIN1P 111
#define GPIO_PAD_111 GPIO110
#ifndef PIN_26_IS_GPIO
#define PIN_26_IS_GPIO 0
#endif 
#ifndef PADA_RIN1P_IS_GPIO
#define PADA_RIN1P_IS_GPIO PIN_26_IS_GPIO
#endif 

#define PADA_RIN1M 9999
#ifndef PADA_RIN1M_IS_GPIO
#define PADA_RIN1M_IS_GPIO 0
#endif 

#define PADA_VSYNC1 9999
#ifndef PADA_VSYNC1_IS_GPIO
#define PADA_VSYNC1_IS_GPIO 0
#endif 

#define PIN_31 PAD_LINEIN_R0
#define PAD_LINEIN_R0 123
#define GPIO_PAD_123 GPIO122
#ifndef PIN_31_IS_GPIO
#define PIN_31_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_R0_IS_GPIO
#define PAD_LINEIN_R0_IS_GPIO PIN_31_IS_GPIO
#endif 

#define PIN_32 PAD_LINEIN_L0
#define PAD_LINEIN_L0 122
#define GPIO_PAD_122 GPIO121
#ifndef PIN_32_IS_GPIO
#define PIN_32_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_L0_IS_GPIO
#define PAD_LINEIN_L0_IS_GPIO PIN_32_IS_GPIO
#endif 

#define PAD_LINEIN_R1 9999
#ifndef PAD_LINEIN_R1_IS_GPIO
#define PAD_LINEIN_R1_IS_GPIO 0
#endif 

#define PAD_LINEIN_L1 9999
#ifndef PAD_LINEIN_L1_IS_GPIO
#define PAD_LINEIN_L1_IS_GPIO 0
#endif 

#define PAD_LINEIN_R2 9999
#ifndef PAD_LINEIN_R2_IS_GPIO
#define PAD_LINEIN_R2_IS_GPIO 0
#endif 

#define PAD_LINEIN_L2 9999
#ifndef PAD_LINEIN_L2_IS_GPIO
#define PAD_LINEIN_L2_IS_GPIO 0
#endif 

#define PAD_LINEIN_R3 9999
#ifndef PAD_LINEIN_R3_IS_GPIO
#define PAD_LINEIN_R3_IS_GPIO 0
#endif 

#define PAD_LINEIN_L3 9999
#ifndef PAD_LINEIN_L3_IS_GPIO
#define PAD_LINEIN_L3_IS_GPIO 0
#endif 

#define PIN_35 PAD_LINEIN_L4
#define PAD_LINEIN_L4 130
#define GPIO_PAD_130 GPIO129
#ifndef PIN_35_IS_GPIO
#define PIN_35_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_L4_IS_GPIO
#define PAD_LINEIN_L4_IS_GPIO PIN_35_IS_GPIO
#endif 

#define PIN_36 PAD_LINEIN_R4
#define PAD_LINEIN_R4 131
#define GPIO_PAD_131 GPIO130
#ifndef PIN_36_IS_GPIO
#define PIN_36_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_R4_IS_GPIO
#define PAD_LINEIN_R4_IS_GPIO PIN_36_IS_GPIO
#endif 

#define PIN_37 PAD_LINEIN_L5
#define PAD_LINEIN_L5 132
#define GPIO_PAD_132 GPIO131
#ifndef PIN_37_IS_GPIO
#define PIN_37_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_L5_IS_GPIO
#define PAD_LINEIN_L5_IS_GPIO PIN_37_IS_GPIO
#endif 

#define PIN_38 PAD_LINEIN_R5
#define PAD_LINEIN_R5 133
#define GPIO_PAD_133 GPIO132
#ifndef PIN_38_IS_GPIO
#define PIN_38_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_R5_IS_GPIO
#define PAD_LINEIN_R5_IS_GPIO PIN_38_IS_GPIO
#endif 

#define PIN_51 PAD_GPIO0
#define PAD_GPIO0 45
#define GPIO_PAD_45 GPIO44 
#ifndef PIN_51_IS_GPIO
#define PIN_51_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO PIN_51_IS_GPIO
#endif 

#define PIN_52 PAD_GPIO1
#define PAD_GPIO1 46
#define GPIO_PAD_46 GPIO45 
#ifndef PIN_52_IS_GPIO
#define PIN_52_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO PIN_52_IS_GPIO
#endif 

#define PIN_53 PAD_GPIO2
#define PAD_GPIO2 47
#define GPIO_PAD_47 GPIO46 
#ifndef PIN_53_IS_GPIO
#define PIN_53_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO PIN_53_IS_GPIO
#endif 

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif 

#define PAD_GPIO4 9999
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO 0
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif 

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif 

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif 

#define PIN_61 PAD_B_ODD0
#define PAD_B_ODD0 44
#define GPIO_PAD_44 GPIO43 
#ifndef PIN_61_IS_GPIO
#define PIN_61_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD0_IS_GPIO
#define PAD_B_ODD0_IS_GPIO PIN_61_IS_GPIO
#endif 

#define PIN_62 PAD_B_ODD1
#define PAD_B_ODD1 43
#define GPIO_PAD_43 GPIO42 
#ifndef PIN_62_IS_GPIO
#define PIN_62_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD1_IS_GPIO
#define PAD_B_ODD1_IS_GPIO PIN_62_IS_GPIO
#endif 

#define PIN_63 PAD_B_ODD2
#define PAD_B_ODD2 42
#define GPIO_PAD_42 GPIO41 
#ifndef PIN_63_IS_GPIO
#define PIN_63_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD2_IS_GPIO
#define PAD_B_ODD2_IS_GPIO PIN_63_IS_GPIO
#endif 

#define PIN_64 PAD_B_ODD3
#define PAD_B_ODD3 41
#define GPIO_PAD_41 GPIO40 
#ifndef PIN_64_IS_GPIO
#define PIN_64_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD3_IS_GPIO
#define PAD_B_ODD3_IS_GPIO PIN_64_IS_GPIO
#endif 

#define PIN_65 PAD_B_ODD4
#define PAD_B_ODD4 40
#define GPIO_PAD_40 GPIO39 
#ifndef PIN_65_IS_GPIO
#define PIN_65_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD4_IS_GPIO
#define PAD_B_ODD4_IS_GPIO PIN_65_IS_GPIO
#endif 

#define PIN_66 PAD_B_ODD5
#define PAD_B_ODD5 39
#define GPIO_PAD_39 GPIO38 
#ifndef PIN_66_IS_GPIO
#define PIN_66_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD5_IS_GPIO
#define PAD_B_ODD5_IS_GPIO PIN_66_IS_GPIO
#endif 

#define PIN_67 PAD_B_ODD6
#define PAD_B_ODD6 38
#define GPIO_PAD_38 GPIO37 
#ifndef PIN_67_IS_GPIO
#define PIN_67_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD6_IS_GPIO
#define PAD_B_ODD6_IS_GPIO PIN_67_IS_GPIO
#endif 

#define PIN_68 PAD_B_ODD7
#define PAD_B_ODD7 37
#define GPIO_PAD_37 GPIO36 
#ifndef PIN_68_IS_GPIO
#define PIN_68_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD7_IS_GPIO
#define PAD_B_ODD7_IS_GPIO PIN_68_IS_GPIO
#endif 

#define PIN_69 PAD_G_ODD0
#define PAD_G_ODD0 36
#define GPIO_PAD_36 GPIO35 
#ifndef PIN_69_IS_GPIO
#define PIN_69_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD0_IS_GPIO
#define PAD_G_ODD0_IS_GPIO PIN_69_IS_GPIO
#endif 

#define PIN_70 PAD_G_ODD1
#define PAD_G_ODD1 35
#define GPIO_PAD_35 GPIO34 
#ifndef PIN_70_IS_GPIO
#define PIN_70_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD1_IS_GPIO
#define PAD_G_ODD1_IS_GPIO PIN_70_IS_GPIO
#endif 

#define PIN_71 PAD_G_ODD2
#define PAD_G_ODD2 34
#define GPIO_PAD_34 GPIO33 
#ifndef PIN_71_IS_GPIO
#define PIN_71_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD2_IS_GPIO
#define PAD_G_ODD2_IS_GPIO PIN_71_IS_GPIO
#endif 

#define PIN_72 PAD_G_ODD3
#define PAD_G_ODD3 33
#define GPIO_PAD_33 GPIO32 
#ifndef PIN_72_IS_GPIO
#define PIN_72_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD3_IS_GPIO
#define PAD_G_ODD3_IS_GPIO PIN_72_IS_GPIO
#endif 

#define PIN_73 PAD_G_ODD4
#define PAD_G_ODD4 32
#define GPIO_PAD_32 GPIO31 
#ifndef PIN_73_IS_GPIO
#define PIN_73_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD4_IS_GPIO
#define PAD_G_ODD4_IS_GPIO PIN_73_IS_GPIO
#endif 

#define PIN_74 PAD_G_ODD5
#define PAD_G_ODD5 31
#define GPIO_PAD_31 GPIO30 
#ifndef PIN_74_IS_GPIO
#define PIN_74_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD5_IS_GPIO
#define PAD_G_ODD5_IS_GPIO PIN_74_IS_GPIO
#endif 

#define PIN_75 PAD_G_ODD7
#define PAD_G_ODD7 29
#define GPIO_PAD_29 GPIO28 
#ifndef PIN_75_IS_GPIO
#define PIN_75_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD7_IS_GPIO
#define PAD_G_ODD7_IS_GPIO PIN_75_IS_GPIO
#endif 

#define PIN_76 PAD_G_ODD6
#define PAD_G_ODD6 30
#define GPIO_PAD_30 GPIO29 
#ifndef PIN_76_IS_GPIO
#define PIN_76_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD6_IS_GPIO
#define PAD_G_ODD6_IS_GPIO PIN_76_IS_GPIO
#endif 

#define PIN_77 PAD_R_ODD0
#define PAD_R_ODD0 28
#define GPIO_PAD_28 GPIO27 
#ifndef PIN_77_IS_GPIO
#define PIN_77_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD0_IS_GPIO
#define PAD_R_ODD0_IS_GPIO PIN_77_IS_GPIO
#endif 

#define PIN_78 PAD_R_ODD1
#define PAD_R_ODD1 27
#define GPIO_PAD_27 GPIO26 
#ifndef PIN_78_IS_GPIO
#define PIN_78_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD1_IS_GPIO
#define PAD_R_ODD1_IS_GPIO PIN_78_IS_GPIO
#endif 

#define PAD_R_ODD2 9999
#ifndef PAD_R_ODD2_IS_GPIO
#define PAD_R_ODD2_IS_GPIO 0
#endif 

#define PAD_R_ODD3 9999
#ifndef PAD_R_ODD3_IS_GPIO
#define PAD_R_ODD3_IS_GPIO 0
#endif 

#define PAD_R_ODD4 9999
#ifndef PAD_R_ODD4_IS_GPIO
#define PAD_R_ODD4_IS_GPIO 0
#endif 

#define PAD_R_ODD5 9999
#ifndef PAD_R_ODD5_IS_GPIO
#define PAD_R_ODD5_IS_GPIO 0
#endif 

#define PAD_R_ODD6 9999
#ifndef PAD_R_ODD6_IS_GPIO
#define PAD_R_ODD6_IS_GPIO 0
#endif 

#define PAD_R_ODD7 9999
#ifndef PAD_R_ODD7_IS_GPIO
#define PAD_R_ODD7_IS_GPIO 0
#endif 

#define PAD_LCK 9999
#ifndef PAD_LCK_IS_GPIO
#define PAD_LCK_IS_GPIO 0
#endif 

#define PAD_LDE 9999
#ifndef PAD_LDE_IS_GPIO
#define PAD_LDE_IS_GPIO 0
#endif 

#define PAD_LHSYNC 9999
#ifndef PAD_LHSYNC_IS_GPIO
#define PAD_LHSYNC_IS_GPIO 0
#endif 

#define PAD_LVSYNC 9999
#ifndef PAD_LVSYNC_IS_GPIO
#define PAD_LVSYNC_IS_GPIO 0
#endif 

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif 

#define PAD_TCON7 9999
#ifndef PAD_TCON7_IS_GPIO
#define PAD_TCON7_IS_GPIO 0
#endif 

#define PAD_TCON6 9999
#ifndef PAD_TCON6_IS_GPIO
#define PAD_TCON6_IS_GPIO 0
#endif 

#define PIN_80 PAD_TCON5
#define PAD_TCON5 6
#define GPIO_PAD_6 GPIO5  
#ifndef PIN_80_IS_GPIO
#define PIN_80_IS_GPIO 0
#endif 
#ifndef PAD_TCON5_IS_GPIO
#define PAD_TCON5_IS_GPIO PIN_80_IS_GPIO
#endif 

#define PIN_81 PAD_TCON4
#define PAD_TCON4 5
#define GPIO_PAD_5 GPIO4  
#ifndef PIN_81_IS_GPIO
#define PIN_81_IS_GPIO 0
#endif 
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO PIN_81_IS_GPIO
#endif 

#define PIN_82 PAD_TCON3
#define PAD_TCON3 4
#define GPIO_PAD_4 GPIO3  
#ifndef PIN_82_IS_GPIO
#define PIN_82_IS_GPIO 0
#endif 
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO PIN_82_IS_GPIO
#endif 

#define PIN_83 PAD_TCON2
#define PAD_TCON2 3
#define GPIO_PAD_3 GPIO2  
#ifndef PIN_83_IS_GPIO
#define PIN_83_IS_GPIO 0
#endif 
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO PIN_83_IS_GPIO
#endif 

#define PIN_84 PAD_TCON1
#define PAD_TCON1 2
#define GPIO_PAD_2 GPIO1  
#ifndef PIN_84_IS_GPIO
#define PIN_84_IS_GPIO 0
#endif 
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO PIN_84_IS_GPIO
#endif 

#define PIN_85 PAD_TCON0
#define PAD_TCON0 1
#define GPIO_PAD_1 GPIO0  
#ifndef PIN_85_IS_GPIO
#define PIN_85_IS_GPIO 0
#endif 
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO PIN_85_IS_GPIO
#endif 

#define PIN_86 PAD_PWM0
#define PAD_PWM0 16
#define GPIO_PAD_16 GPIO15 
#ifndef PIN_86_IS_GPIO
#define PIN_86_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO PIN_86_IS_GPIO
#endif 

#define PIN_87 PAD_PWM1
#define PAD_PWM1 15
#define GPIO_PAD_15 GPIO14 
#ifndef PIN_87_IS_GPIO
#define PIN_87_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO PIN_87_IS_GPIO
#endif 

#define PAD_PWM2 9999
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO 0
#endif 

#define PAD_PWM3 9999
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO 0
#endif 

#define PAD_INT 9999
#ifndef PAD_INT_IS_GPIO
#define PAD_INT_IS_GPIO 0
#endif 

#define PAD_GPIO28 9999
#ifndef PAD_GPIO28_IS_GPIO
#define PAD_GPIO28_IS_GPIO 0
#endif 

#define PAD_GPIO29 9999
#ifndef PAD_GPIO29_IS_GPIO
#define PAD_GPIO29_IS_GPIO 0
#endif 

#define PAD_GPIO30 9999
#ifndef PAD_GPIO30_IS_GPIO
#define PAD_GPIO30_IS_GPIO 0
#endif 

#define PAD_GPIO31 9999
#ifndef PAD_GPIO31_IS_GPIO
#define PAD_GPIO31_IS_GPIO 0
#endif 

#define PAD_GPIO20 9999
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO 0
#endif 

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif 

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif 

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif 

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif 

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif 

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif 

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif 

#define PAD_GPIO32 9999
#ifndef PAD_GPIO32_IS_GPIO
#define PAD_GPIO32_IS_GPIO 0
#endif 

#define PIN_97 PAD_MHL_DET
#define PAD_MHL_DET 87
#define GPIO_PAD_87 GPIO86 
#ifndef PIN_97_IS_GPIO
#define PIN_97_IS_GPIO 0
#endif 
#ifndef PAD_MHL_DET_IS_GPIO
#define PAD_MHL_DET_IS_GPIO PIN_97_IS_GPIO
#endif 

#define PIN_98 PAD_DDCDC_DAT
#define PAD_DDCDC_DAT 85
#define GPIO_PAD_85 GPIO84 
#ifndef PIN_98_IS_GPIO
#define PIN_98_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_DAT_IS_GPIO
#define PAD_DDCDC_DAT_IS_GPIO PIN_98_IS_GPIO
#endif 

#define PIN_99 PAD_DDCDC_CLK
#define PAD_DDCDC_CLK 84
#define GPIO_PAD_84 GPIO83 
#ifndef PIN_99_IS_GPIO
#define PIN_99_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_CLK_IS_GPIO
#define PAD_DDCDC_CLK_IS_GPIO PIN_99_IS_GPIO
#endif 

#define PAD_GPIO33 9999
#ifndef PAD_GPIO33_IS_GPIO
#define PAD_GPIO33_IS_GPIO 0
#endif 

#define PAD_GPIO34 9999
#ifndef PAD_GPIO34_IS_GPIO
#define PAD_GPIO34_IS_GPIO 0
#endif 

#define PAD_GPIO35 9999
#ifndef PAD_GPIO35_IS_GPIO
#define PAD_GPIO35_IS_GPIO 0
#endif 

#define PAD_GPIO36 9999
#ifndef PAD_GPIO36_IS_GPIO
#define PAD_GPIO36_IS_GPIO 0
#endif 

#define PIN_101 PAD_SAR0
#define PAD_SAR0 76
#define GPIO_PAD_76 GPIO75 
#ifndef PIN_101_IS_GPIO
#define PIN_101_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO PIN_101_IS_GPIO
#endif 

#define PIN_102 PAD_SAR1
#define PAD_SAR1 75
#define GPIO_PAD_75 GPIO74 
#ifndef PIN_102_IS_GPIO
#define PIN_102_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO PIN_102_IS_GPIO
#endif 

#define PAD_SAR2 9999
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO 0
#endif 

#define PAD_SAR3 9999
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO 0
#endif 

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif 

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif 

#define PIN_107 PAD_DDCDB_DAT
#define PAD_DDCDB_DAT 82
#define GPIO_PAD_82 GPIO81 
#ifndef PIN_107_IS_GPIO
#define PIN_107_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_DAT_IS_GPIO
#define PAD_DDCDB_DAT_IS_GPIO PIN_107_IS_GPIO
#endif 

#define PIN_108 PAD_DDCDB_CLK
#define PAD_DDCDB_CLK 81
#define GPIO_PAD_81 GPIO80 
#ifndef PIN_108_IS_GPIO
#define PIN_108_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_CLK_IS_GPIO
#define PAD_DDCDB_CLK_IS_GPIO PIN_108_IS_GPIO
#endif 

#define PIN_109 PAD_DDCDA_DAT
#define PAD_DDCDA_DAT 79
#define GPIO_PAD_79 GPIO78 
#ifndef PIN_109_IS_GPIO
#define PIN_109_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DAT_IS_GPIO
#define PAD_DDCDA_DAT_IS_GPIO PIN_109_IS_GPIO
#endif 

#define PIN_110 PAD_DDCDA_CLK
#define PAD_DDCDA_CLK 78
#define GPIO_PAD_78 GPIO77 
#ifndef PIN_110_IS_GPIO
#define PIN_110_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CLK_IS_GPIO
#define PAD_DDCDA_CLK_IS_GPIO PIN_110_IS_GPIO
#endif 

#define PIN_111 PAD_CEC
#define PAD_CEC 72
#define GPIO_PAD_72 GPIO71 
#ifndef PIN_111_IS_GPIO
#define PIN_111_IS_GPIO 0
#endif 
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO PIN_111_IS_GPIO
#endif 

#define PIN_112 PAD_HOTPLUG_C
#define PAD_HOTPLUG_C 86
#define GPIO_PAD_86 GPIO85 
#ifndef PIN_112_IS_GPIO
#define PIN_112_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUG_C_IS_GPIO
#define PAD_HOTPLUG_C_IS_GPIO PIN_112_IS_GPIO
#endif 

#define PIN_113 PAD_HOTPLUG_B
#define PAD_HOTPLUG_B 83
#define GPIO_PAD_83 GPIO82 
#ifndef PIN_113_IS_GPIO
#define PIN_113_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUG_B_IS_GPIO
#define PAD_HOTPLUG_B_IS_GPIO PIN_113_IS_GPIO
#endif 

#define PIN_114 PAD_HOTPLUG_A
#define PAD_HOTPLUG_A 80
#define GPIO_PAD_80 GPIO79 
#ifndef PIN_114_IS_GPIO
#define PIN_114_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUG_A_IS_GPIO
#define PAD_HOTPLUG_A_IS_GPIO PIN_114_IS_GPIO
#endif 

#define PIN_119 PAD_RXCN_D
#define PAD_RXCN_D 150
#define GPIO_PAD_150 GPIO149
#ifndef PIN_119_IS_GPIO
#define PIN_119_IS_GPIO 0
#endif 
#ifndef PAD_RXCN_D_IS_GPIO
#define PAD_RXCN_D_IS_GPIO PIN_119_IS_GPIO
#endif 

#define PIN_121 PAD_RX0N_D
#define PAD_RX0N_D 152
#define GPIO_PAD_152 GPIO151
#ifndef PIN_121_IS_GPIO
#define PIN_121_IS_GPIO 0
#endif 
#ifndef PAD_RX0N_D_IS_GPIO
#define PAD_RX0N_D_IS_GPIO PIN_121_IS_GPIO
#endif 

#define PIN_120 PAD_RXCP_D
#define PAD_RXCP_D 151
#define GPIO_PAD_151 GPIO150
#ifndef PIN_120_IS_GPIO
#define PIN_120_IS_GPIO 0
#endif 
#ifndef PAD_RXCP_D_IS_GPIO
#define PAD_RXCP_D_IS_GPIO PIN_120_IS_GPIO
#endif 

#define PIN_122 PAD_RX0P_D
#define PAD_RX0P_D 153
#define GPIO_PAD_153 GPIO152
#ifndef PIN_122_IS_GPIO
#define PIN_122_IS_GPIO 0
#endif 
#ifndef PAD_RX0P_D_IS_GPIO
#define PAD_RX0P_D_IS_GPIO PIN_122_IS_GPIO
#endif 

#define PIN_123 PAD_RX1N_D
#define PAD_RX1N_D 154
#define GPIO_PAD_154 GPIO153
#ifndef PIN_123_IS_GPIO
#define PIN_123_IS_GPIO 0
#endif 
#ifndef PAD_RX1N_D_IS_GPIO
#define PAD_RX1N_D_IS_GPIO PIN_123_IS_GPIO
#endif 

#define PIN_125 PAD_RX2N_D
#define PAD_RX2N_D 156
#define GPIO_PAD_156 GPIO155
#ifndef PIN_125_IS_GPIO
#define PIN_125_IS_GPIO 0
#endif 
#ifndef PAD_RX2N_D_IS_GPIO
#define PAD_RX2N_D_IS_GPIO PIN_125_IS_GPIO
#endif 

#define PIN_124 PAD_RX1P_D
#define PAD_RX1P_D 155
#define GPIO_PAD_155 GPIO154
#ifndef PIN_124_IS_GPIO
#define PIN_124_IS_GPIO 0
#endif 
#ifndef PAD_RX1P_D_IS_GPIO
#define PAD_RX1P_D_IS_GPIO PIN_124_IS_GPIO
#endif 

#define PIN_126 PAD_RX2P_D
#define PAD_RX2P_D 157
#define GPIO_PAD_157 GPIO156
#ifndef PIN_126_IS_GPIO
#define PIN_126_IS_GPIO 0
#endif 
#ifndef PAD_RX2P_D_IS_GPIO
#define PAD_RX2P_D_IS_GPIO PIN_126_IS_GPIO
#endif 

#define PIN_1 PAD_RX0N_B
#define PAD_RX0N_B 144
#define GPIO_PAD_144 GPIO143
#ifndef PIN_1_IS_GPIO
#define PIN_1_IS_GPIO 0
#endif 
#ifndef PAD_RX0N_B_IS_GPIO
#define PAD_RX0N_B_IS_GPIO PIN_1_IS_GPIO
#endif 

#define PIN_127 PAD_RXCN_B
#define PAD_RXCN_B 142
#define GPIO_PAD_142 GPIO141
#ifndef PIN_127_IS_GPIO
#define PIN_127_IS_GPIO 0
#endif 
#ifndef PAD_RXCN_B_IS_GPIO
#define PAD_RXCN_B_IS_GPIO PIN_127_IS_GPIO
#endif 

#define PIN_2 PAD_RX0P_B
#define PAD_RX0P_B 145
#define GPIO_PAD_145 GPIO144
#ifndef PIN_2_IS_GPIO
#define PIN_2_IS_GPIO 0
#endif 
#ifndef PAD_RX0P_B_IS_GPIO
#define PAD_RX0P_B_IS_GPIO PIN_2_IS_GPIO
#endif 

#define PIN_128 PAD_RXCP_B
#define PAD_RXCP_B 143
#define GPIO_PAD_143 GPIO142
#ifndef PIN_128_IS_GPIO
#define PIN_128_IS_GPIO 0
#endif 
#ifndef PAD_RXCP_B_IS_GPIO
#define PAD_RXCP_B_IS_GPIO PIN_128_IS_GPIO
#endif 

#define PIN_5 PAD_RX2N_B
#define PAD_RX2N_B 148
#define GPIO_PAD_148 GPIO147
#ifndef PIN_5_IS_GPIO
#define PIN_5_IS_GPIO 0
#endif 
#ifndef PAD_RX2N_B_IS_GPIO
#define PAD_RX2N_B_IS_GPIO PIN_5_IS_GPIO
#endif 

#define PIN_3 PAD_RX1N_B
#define PAD_RX1N_B 146
#define GPIO_PAD_146 GPIO145
#ifndef PIN_3_IS_GPIO
#define PIN_3_IS_GPIO 0
#endif 
#ifndef PAD_RX1N_B_IS_GPIO
#define PAD_RX1N_B_IS_GPIO PIN_3_IS_GPIO
#endif 

#define PIN_4 PAD_RX1P_B
#define PAD_RX1P_B 147
#define GPIO_PAD_147 GPIO146
#ifndef PIN_4_IS_GPIO
#define PIN_4_IS_GPIO 0
#endif 
#ifndef PAD_RX1P_B_IS_GPIO
#define PAD_RX1P_B_IS_GPIO PIN_4_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_MELODY

#endif /* _MSD91RUNx_H_*/
