/*************************************************************************************
                  Silicon Laboratories Broadcast Si21XXC Layer 1 API

   EVALUATION AND USE OF THIS SOFTWARE IS SUBJECT TO THE TERMS AND CONDITIONS OF
     THE SOFTWARE LICENSE AGREEMENT IN THE DOCUMENTATION FILE CORRESPONDING
     TO THIS SOURCE FILE.
   IF YOU DO NOT AGREE TO THE LIMITED LICENSE AND CONDITIONS OF SUCH AGREEMENT,
     PLEASE RETURN ALL SOURCE FILES TO SILICON LABORATORIES.

   API properties structures and functions definitions
   FILE: Si21XXC_Properties.h
   Supported IC : Si2178B,Si2190B,Si2191B,Si2191C
   Compiled for ROM 71 firmware 3_0_build_1
   Revision: 0.1
   Tag:  Si2190B_30b1_Si2178B_42b7_Si2191C_30b1_Si2191B_42b7_V0.1
   Date: August 12 2015
  (C) Copyright 2014, Silicon Laboratories, Inc. All rights reserved.
**************************************************************************************/
#ifndef   _Si21XXC_PROPERTIES_H_
#define   _Si21XXC_PROPERTIES_H_

/* _properties_defines_insertion_start */
#ifdef __cplusplus
extern "C"{
#endif
/* Si21XXC ATV_AFC_RANGE property definition */
#define   Si21XXC_ATV_AFC_RANGE_PROP 0x0610

#ifdef    Si21XXC_ATV_AFC_RANGE_PROP
  #define Si21XXC_ATV_AFC_RANGE_PROP_CODE 0x000610


    typedef struct { /* Si21XXC_ATV_AFC_RANGE_PROP_struct */
      unsigned int    range_khz;
   } Si21XXC_ATV_AFC_RANGE_PROP_struct;

   /* ATV_AFC_RANGE property, RANGE_KHZ field definition (NO TITLE)*/
   #define  Si21XXC_ATV_AFC_RANGE_PROP_RANGE_KHZ_LSB         0
   #define  Si21XXC_ATV_AFC_RANGE_PROP_RANGE_KHZ_MASK        0xffff
   #define  Si21XXC_ATV_AFC_RANGE_PROP_RANGE_KHZ_DEFAULT    1000
    #define Si21XXC_ATV_AFC_RANGE_PROP_RANGE_KHZ_RANGE_KHZ_MIN  0
    #define Si21XXC_ATV_AFC_RANGE_PROP_RANGE_KHZ_RANGE_KHZ_MAX  65535

#endif /* Si21XXC_ATV_AFC_RANGE_PROP */

/* Si21XXC ATV_AGC_SPEED property definition */
#define   Si21XXC_ATV_AGC_SPEED_PROP 0x0611

#ifdef    Si21XXC_ATV_AGC_SPEED_PROP
  #define Si21XXC_ATV_AGC_SPEED_PROP_CODE 0x000611


    typedef struct { /* Si21XXC_ATV_AGC_SPEED_PROP_struct */
      unsigned char   if_agc_speed;
   } Si21XXC_ATV_AGC_SPEED_PROP_struct;

   /* ATV_AGC_SPEED property, IF_AGC_SPEED field definition (NO TITLE)*/
   #define  Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_LSB         0
   #define  Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_MASK        0xff
   #define  Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_DEFAULT    0
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_AUTO    0
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_89      89
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_105     105
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_121     121
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_137     137
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_158     158
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_172     172
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_178     178
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_185     185
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_196     196
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_206     206
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_216     216
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_219     219
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_222     222
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_223     223
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_248     248
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_250     250
    #define Si21XXC_ATV_AGC_SPEED_PROP_IF_AGC_SPEED_251     251

#endif /* Si21XXC_ATV_AGC_SPEED_PROP */

/* Si21XXC ATV_AGC_SPEED_LOW_RSSI property definition */
#define   Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP 0x0623

#ifdef    Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP
  #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_CODE 0x000623


    typedef struct { /* Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_struct */
      unsigned char   if_agc_speed;
               char   thld;
   } Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_struct;

   /* ATV_AGC_SPEED_LOW_RSSI property, IF_AGC_SPEED field definition (NO TITLE)*/
   #define  Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_LSB         0
   #define  Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_MASK        0xff
   #define  Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_DEFAULT    158
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_89      89
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_105     105
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_121     121
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_137     137
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_158     158
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_172     172
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_178     178
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_185     185
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_196     196
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_206     206
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_216     216
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_219     219
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_222     222
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_223     223
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_248     248
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_250     250
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_IF_AGC_SPEED_251     251

   /* ATV_AGC_SPEED_LOW_RSSI property, THLD field definition (NO TITLE)*/
   #define  Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_THLD_LSB         8
   #define  Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_THLD_MASK        0xff
   #define  Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_THLD_DEFAULT    -128
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_THLD_THLD_MIN  -128
    #define Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_THLD_THLD_MAX  127

#endif /* Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP */

/* Si21XXC ATV_ARTIFICIAL_SNOW property definition */
#define   Si21XXC_ATV_ARTIFICIAL_SNOW_PROP 0x0624

#ifdef    Si21XXC_ATV_ARTIFICIAL_SNOW_PROP
  #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_CODE 0x000624


    typedef struct { /* Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_struct */
      unsigned char   gain;
               char   offset;
      unsigned char   period;
      unsigned char   sound;
   } Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_struct;

   /* ATV_ARTIFICIAL_SNOW property, GAIN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_LSB         0
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_MASK        0x0f
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_DEFAULT    0
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_AUTO  0
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_0DB   1
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_6DB   2
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_12DB  3
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_18DB  4
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_24DB  5
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_30DB  6
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_36DB  7
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_42DB  8
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_GAIN_OFF   9

   /* ATV_ARTIFICIAL_SNOW property, OFFSET field definition (NO TITLE)*/
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_OFFSET_LSB         8
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_OFFSET_MASK        0xff
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_OFFSET_DEFAULT    0
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_OFFSET_OFFSET_MIN  -128
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_OFFSET_OFFSET_MAX  127

   /* ATV_ARTIFICIAL_SNOW property, PERIOD field definition (NO TITLE)*/
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_PERIOD_LSB         7
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_PERIOD_MASK        0x01
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_PERIOD_DEFAULT    0
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_PERIOD_LONG   0
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_PERIOD_SHORT  1

  /* ATV_ARTIFICIAL_SNOW property, SOUND field definition (NO TITLE)*/
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_SOUND_LSB         4
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_SOUND_MASK        0x07
   #define  Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_SOUND_DEFAULT    0
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_SOUND_MUTE          0
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_SOUND_6DB           1
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_SOUND_12DB          2
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_SOUND_18DB          3
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_SOUND_24DB          4
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_SOUND_30DB          5
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_SOUND_36DB          6
    #define Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_SOUND_PASS_THROUGH  7

#endif /* Si21XXC_ATV_ARTIFICIAL_SNOW_PROP */

/* Si21XXC ATV_AUDIO_MODE property definition */
#define   Si21XXC_ATV_AUDIO_MODE_PROP 0x0602

#ifdef    Si21XXC_ATV_AUDIO_MODE_PROP
  #define Si21XXC_ATV_AUDIO_MODE_PROP_CODE 0x000602


    typedef struct { /* Si21XXC_ATV_AUDIO_MODE_PROP_struct */
      unsigned char   audio_sys;
      unsigned char   chan_bw;
   } Si21XXC_ATV_AUDIO_MODE_PROP_struct;

   /* ATV_AUDIO_MODE property, AUDIO_SYS field definition (NO TITLE)*/
   #define  Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_LSB         0
   #define  Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_MASK        0x0f
   #define  Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_DEFAULT    0
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_DEFAULT          0
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_MONO             1
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_MONO_NICAM       2
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_A2               3
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_A2_DK2           4
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_A2_DK3           5
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_BTSC             6
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_EIAJ             7
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_SCAN             8
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_A2_DK4           9
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_WIDE_SCAN        10
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_MONO_NICAM_6DB   11
    #define Si21XXC_ATV_AUDIO_MODE_PROP_AUDIO_SYS_MONO_NICAM_10DB  12

   /* ATV_AUDIO_MODE property, CHAN_BW field definition (NO TITLE)*/
   #define  Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_LSB         8
   #define  Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_MASK        0x0f
   #define  Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_DEFAULT    0
    #define Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_DEFAULT         0
    #define Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_4X_OVERMOD      1
    #define Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_8X_OVERMOD      2
    #define Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_12X_OVERMOD     3
    #define Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_7P5_KHZ_OFFSET  4
    #define Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_15_KHZ_OFFSET   5
    #define Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_30_KHZ_OFFSET   6
    #define Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_75_KHZ_OFFSET   7
    #define Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_150_KHZ_OFFSET  8
    #define Si21XXC_ATV_AUDIO_MODE_PROP_CHAN_BW_CUSTOM          9

#endif /* Si21XXC_ATV_AUDIO_MODE_PROP */

/* Si21XXC ATV_CONFIG_IF_PORT property definition */
#define   Si21XXC_ATV_CONFIG_IF_PORT_PROP 0x0603

#ifdef    Si21XXC_ATV_CONFIG_IF_PORT_PROP
  #define Si21XXC_ATV_CONFIG_IF_PORT_PROP_CODE 0x000603


    typedef struct { /* Si21XXC_ATV_CONFIG_IF_PORT_PROP_struct */
      unsigned char   atv_out_type;
   } Si21XXC_ATV_CONFIG_IF_PORT_PROP_struct;

   /* ATV_CONFIG_IF_PORT property, ATV_OUT_TYPE field definition (NO TITLE)*/
   #define  Si21XXC_ATV_CONFIG_IF_PORT_PROP_ATV_OUT_TYPE_LSB         0
   #define  Si21XXC_ATV_CONFIG_IF_PORT_PROP_ATV_OUT_TYPE_MASK        0x0f
   #define  Si21XXC_ATV_CONFIG_IF_PORT_PROP_ATV_OUT_TYPE_DEFAULT    0
    #define Si21XXC_ATV_CONFIG_IF_PORT_PROP_ATV_OUT_TYPE_CVBS_IF2B_SOUND_IF2A        0
    #define Si21XXC_ATV_CONFIG_IF_PORT_PROP_ATV_OUT_TYPE_CVBS_IF2B_SOUND_DIFF_IF1  3
    #define Si21XXC_ATV_CONFIG_IF_PORT_PROP_ATV_OUT_TYPE_LIF_DIFF_IF1  8
    #define Si21XXC_ATV_CONFIG_IF_PORT_PROP_ATV_OUT_TYPE_LIF_DIFF_IF2  10
    #define Si21XXC_ATV_CONFIG_IF_PORT_PROP_ATV_OUT_TYPE_LIF_SE_IF1A   12
    #define Si21XXC_ATV_CONFIG_IF_PORT_PROP_ATV_OUT_TYPE_LIF_SE_IF2A   14

#endif /* Si21XXC_ATV_CONFIG_IF_PORT_PROP */

/* Si2190B ATV_CVBS_ATTENUATION property definition */
#define   Si2190B_ATV_CVBS_ATTENUATION_PROP 0x0628

#ifdef    Si2190B_ATV_CVBS_ATTENUATION_PROP
  #define Si2190B_ATV_CVBS_ATTENUATION_PROP_CODE 0x000628


    typedef struct { /* Si2190B_ATV_CVBS_ATTENUATION_PROP_struct */
      unsigned char   bw;
      unsigned char   rate;
      unsigned char   threshold;
   } Si2190B_ATV_CVBS_ATTENUATION_PROP_struct;

   /* ATV_CVBS_ATTENUATION property, BW field definition (NO TITLE)*/
   #define  Si2190B_ATV_CVBS_ATTENUATION_PROP_BW_LSB         13
   #define  Si2190B_ATV_CVBS_ATTENUATION_PROP_BW_MASK        0x07
   #define  Si2190B_ATV_CVBS_ATTENUATION_PROP_BW_DEFAULT    4
    #define Si2190B_ATV_CVBS_ATTENUATION_PROP_BW_BW_MIN  0
    #define Si2190B_ATV_CVBS_ATTENUATION_PROP_BW_BW_MAX  7

   /* ATV_CVBS_ATTENUATION property, RATE field definition (NO TITLE)*/
   #define  Si2190B_ATV_CVBS_ATTENUATION_PROP_RATE_LSB         7
   #define  Si2190B_ATV_CVBS_ATTENUATION_PROP_RATE_MASK        0x3f
   #define  Si2190B_ATV_CVBS_ATTENUATION_PROP_RATE_DEFAULT    0
    #define Si2190B_ATV_CVBS_ATTENUATION_PROP_RATE_RATE_MIN  0
    #define Si2190B_ATV_CVBS_ATTENUATION_PROP_RATE_RATE_MAX  63

   /* ATV_CVBS_ATTENUATION property, THRESHOLD field definition (NO TITLE)*/
   #define  Si2190B_ATV_CVBS_ATTENUATION_PROP_THRESHOLD_LSB         0
   #define  Si2190B_ATV_CVBS_ATTENUATION_PROP_THRESHOLD_MASK        0x7f
   #define  Si2190B_ATV_CVBS_ATTENUATION_PROP_THRESHOLD_DEFAULT    0
    #define Si2190B_ATV_CVBS_ATTENUATION_PROP_THRESHOLD_THRESHOLD_MIN  0
    #define Si2190B_ATV_CVBS_ATTENUATION_PROP_THRESHOLD_THRESHOLD_MAX  127

#endif /* Si2190B_ATV_CVBS_ATTENUATION_PROP */

/* Si21XXC ATV_CVBS_OUT property definition */
#define   Si21XXC_ATV_CVBS_OUT_PROP 0x0609

#ifdef    Si21XXC_ATV_CVBS_OUT_PROP
  #define Si21XXC_ATV_CVBS_OUT_PROP_CODE 0x000609


    typedef struct { /* Si21XXC_ATV_CVBS_OUT_PROP_struct */
      unsigned char   amp;
      unsigned char   offset;
   } Si21XXC_ATV_CVBS_OUT_PROP_struct;

   /* ATV_CVBS_OUT property, AMP field definition (NO TITLE)*/
   #define  Si21XXC_ATV_CVBS_OUT_PROP_AMP_LSB         8
   #define  Si21XXC_ATV_CVBS_OUT_PROP_AMP_MASK        0xff
   #define  Si21XXC_ATV_CVBS_OUT_PROP_AMP_DEFAULT    200
    #define Si21XXC_ATV_CVBS_OUT_PROP_AMP_AMP_MIN  0
    #define Si21XXC_ATV_CVBS_OUT_PROP_AMP_AMP_MAX  255

   /* ATV_CVBS_OUT property, OFFSET field definition (NO TITLE)*/
   #define  Si21XXC_ATV_CVBS_OUT_PROP_OFFSET_LSB         0
   #define  Si21XXC_ATV_CVBS_OUT_PROP_OFFSET_MASK        0xff
   #define  Si21XXC_ATV_CVBS_OUT_PROP_OFFSET_DEFAULT    25
    #define Si21XXC_ATV_CVBS_OUT_PROP_OFFSET_OFFSET_MIN  0
    #define Si21XXC_ATV_CVBS_OUT_PROP_OFFSET_OFFSET_MAX  255

#endif /* Si21XXC_ATV_CVBS_OUT_PROP */

/* Si21XXC ATV_CVBS_OUT_FINE property definition */
#define   Si21XXC_ATV_CVBS_OUT_FINE_PROP 0x0614

#ifdef    Si21XXC_ATV_CVBS_OUT_FINE_PROP
  #define Si21XXC_ATV_CVBS_OUT_FINE_PROP_CODE 0x000614


    typedef struct { /* Si21XXC_ATV_CVBS_OUT_FINE_PROP_struct */
      unsigned char   amp;
               char   offset;
   } Si21XXC_ATV_CVBS_OUT_FINE_PROP_struct;

   /* ATV_CVBS_OUT_FINE property, AMP field definition (NO TITLE)*/
   #define  Si21XXC_ATV_CVBS_OUT_FINE_PROP_AMP_LSB         8
   #define  Si21XXC_ATV_CVBS_OUT_FINE_PROP_AMP_MASK        0xff
   #define  Si21XXC_ATV_CVBS_OUT_FINE_PROP_AMP_DEFAULT    100
    #define Si21XXC_ATV_CVBS_OUT_FINE_PROP_AMP_AMP_MIN  25
    #define Si21XXC_ATV_CVBS_OUT_FINE_PROP_AMP_AMP_MAX  100

   /* ATV_CVBS_OUT_FINE property, OFFSET field definition (NO TITLE)*/
   #define  Si21XXC_ATV_CVBS_OUT_FINE_PROP_OFFSET_LSB         0
   #define  Si21XXC_ATV_CVBS_OUT_FINE_PROP_OFFSET_MASK        0xff
   #define  Si21XXC_ATV_CVBS_OUT_FINE_PROP_OFFSET_DEFAULT    0
    #define Si21XXC_ATV_CVBS_OUT_FINE_PROP_OFFSET_OFFSET_MIN  -128
    #define Si21XXC_ATV_CVBS_OUT_FINE_PROP_OFFSET_OFFSET_MAX  127

#endif /* Si21XXC_ATV_CVBS_OUT_FINE_PROP */

/* Si21XXC ATV_IEN property definition */
#define   Si21XXC_ATV_IEN_PROP 0x0601

#ifdef    Si21XXC_ATV_IEN_PROP
  #define Si21XXC_ATV_IEN_PROP_CODE 0x000601


    typedef struct { /* Si21XXC_ATV_IEN_PROP_struct */
      unsigned char   chlien;
      unsigned char   dlien;
      unsigned char   pclien;
      unsigned char   snrhien;
      unsigned char   snrlien;
   } Si21XXC_ATV_IEN_PROP_struct;

   /* ATV_IEN property, CHLIEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_IEN_PROP_CHLIEN_LSB         0
   #define  Si21XXC_ATV_IEN_PROP_CHLIEN_MASK        0x01
   #define  Si21XXC_ATV_IEN_PROP_CHLIEN_DEFAULT    1
    #define Si21XXC_ATV_IEN_PROP_CHLIEN_DISABLE  0
    #define Si21XXC_ATV_IEN_PROP_CHLIEN_ENABLE   1

   /* ATV_IEN property, DLIEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_IEN_PROP_DLIEN_LSB         2
   #define  Si21XXC_ATV_IEN_PROP_DLIEN_MASK        0x01
   #define  Si21XXC_ATV_IEN_PROP_DLIEN_DEFAULT    0
    #define Si21XXC_ATV_IEN_PROP_DLIEN_DISABLE  0
    #define Si21XXC_ATV_IEN_PROP_DLIEN_ENABLE   1

   /* ATV_IEN property, PCLIEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_IEN_PROP_PCLIEN_LSB         1
   #define  Si21XXC_ATV_IEN_PROP_PCLIEN_MASK        0x01
   #define  Si21XXC_ATV_IEN_PROP_PCLIEN_DEFAULT    0
    #define Si21XXC_ATV_IEN_PROP_PCLIEN_DISABLE  0
    #define Si21XXC_ATV_IEN_PROP_PCLIEN_ENABLE   1

   /* ATV_IEN property, SNRHIEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_IEN_PROP_SNRHIEN_LSB         4
   #define  Si21XXC_ATV_IEN_PROP_SNRHIEN_MASK        0x01
   #define  Si21XXC_ATV_IEN_PROP_SNRHIEN_DEFAULT    0
    #define Si21XXC_ATV_IEN_PROP_SNRHIEN_DISABLE  0
    #define Si21XXC_ATV_IEN_PROP_SNRHIEN_ENABLE   1

   /* ATV_IEN property, SNRLIEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_IEN_PROP_SNRLIEN_LSB         3
   #define  Si21XXC_ATV_IEN_PROP_SNRLIEN_MASK        0x01
   #define  Si21XXC_ATV_IEN_PROP_SNRLIEN_DEFAULT    0
    #define Si21XXC_ATV_IEN_PROP_SNRLIEN_DISABLE  0
    #define Si21XXC_ATV_IEN_PROP_SNRLIEN_ENABLE   1

#endif /* Si21XXC_ATV_IEN_PROP */

/* Si21XXC ATV_INT_SENSE property definition */
#define   Si21XXC_ATV_INT_SENSE_PROP 0x0613

#ifdef    Si21XXC_ATV_INT_SENSE_PROP
  #define Si21XXC_ATV_INT_SENSE_PROP_CODE 0x000613


    typedef struct { /* Si21XXC_ATV_INT_SENSE_PROP_struct */
      unsigned char   chlnegen;
      unsigned char   chlposen;
      unsigned char   dlnegen;
      unsigned char   dlposen;
      unsigned char   pclnegen;
      unsigned char   pclposen;
      unsigned char   snrhnegen;
      unsigned char   snrhposen;
      unsigned char   snrlnegen;
      unsigned char   snrlposen;
   } Si21XXC_ATV_INT_SENSE_PROP_struct;

   /* ATV_INT_SENSE property, CHLNEGEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_INT_SENSE_PROP_CHLNEGEN_LSB         0
   #define  Si21XXC_ATV_INT_SENSE_PROP_CHLNEGEN_MASK        0x01
   #define  Si21XXC_ATV_INT_SENSE_PROP_CHLNEGEN_DEFAULT    0
    #define Si21XXC_ATV_INT_SENSE_PROP_CHLNEGEN_DISABLE  0
    #define Si21XXC_ATV_INT_SENSE_PROP_CHLNEGEN_ENABLE   1

   /* ATV_INT_SENSE property, CHLPOSEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_INT_SENSE_PROP_CHLPOSEN_LSB         8
   #define  Si21XXC_ATV_INT_SENSE_PROP_CHLPOSEN_MASK        0x01
   #define  Si21XXC_ATV_INT_SENSE_PROP_CHLPOSEN_DEFAULT    1
    #define Si21XXC_ATV_INT_SENSE_PROP_CHLPOSEN_DISABLE  0
    #define Si21XXC_ATV_INT_SENSE_PROP_CHLPOSEN_ENABLE   1

   /* ATV_INT_SENSE property, DLNEGEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_INT_SENSE_PROP_DLNEGEN_LSB         2
   #define  Si21XXC_ATV_INT_SENSE_PROP_DLNEGEN_MASK        0x01
   #define  Si21XXC_ATV_INT_SENSE_PROP_DLNEGEN_DEFAULT    0
    #define Si21XXC_ATV_INT_SENSE_PROP_DLNEGEN_DISABLE  0
    #define Si21XXC_ATV_INT_SENSE_PROP_DLNEGEN_ENABLE   1

   /* ATV_INT_SENSE property, DLPOSEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_INT_SENSE_PROP_DLPOSEN_LSB         10
   #define  Si21XXC_ATV_INT_SENSE_PROP_DLPOSEN_MASK        0x01
   #define  Si21XXC_ATV_INT_SENSE_PROP_DLPOSEN_DEFAULT    1
    #define Si21XXC_ATV_INT_SENSE_PROP_DLPOSEN_DISABLE  0
    #define Si21XXC_ATV_INT_SENSE_PROP_DLPOSEN_ENABLE   1

   /* ATV_INT_SENSE property, PCLNEGEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_INT_SENSE_PROP_PCLNEGEN_LSB         1
   #define  Si21XXC_ATV_INT_SENSE_PROP_PCLNEGEN_MASK        0x01
   #define  Si21XXC_ATV_INT_SENSE_PROP_PCLNEGEN_DEFAULT    0
    #define Si21XXC_ATV_INT_SENSE_PROP_PCLNEGEN_DISABLE  0
    #define Si21XXC_ATV_INT_SENSE_PROP_PCLNEGEN_ENABLE   1

   /* ATV_INT_SENSE property, PCLPOSEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_INT_SENSE_PROP_PCLPOSEN_LSB         9
   #define  Si21XXC_ATV_INT_SENSE_PROP_PCLPOSEN_MASK        0x01
   #define  Si21XXC_ATV_INT_SENSE_PROP_PCLPOSEN_DEFAULT    1
    #define Si21XXC_ATV_INT_SENSE_PROP_PCLPOSEN_DISABLE  0
    #define Si21XXC_ATV_INT_SENSE_PROP_PCLPOSEN_ENABLE   1

   /* ATV_INT_SENSE property, SNRHNEGEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRHNEGEN_LSB         4
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRHNEGEN_MASK        0x01
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRHNEGEN_DEFAULT    0
    #define Si21XXC_ATV_INT_SENSE_PROP_SNRHNEGEN_DISABLE  0
    #define Si21XXC_ATV_INT_SENSE_PROP_SNRHNEGEN_ENABLE   1

   /* ATV_INT_SENSE property, SNRHPOSEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRHPOSEN_LSB         12
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRHPOSEN_MASK        0x01
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRHPOSEN_DEFAULT    1
    #define Si21XXC_ATV_INT_SENSE_PROP_SNRHPOSEN_DISABLE  0
    #define Si21XXC_ATV_INT_SENSE_PROP_SNRHPOSEN_ENABLE   1

   /* ATV_INT_SENSE property, SNRLNEGEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRLNEGEN_LSB         3
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRLNEGEN_MASK        0x01
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRLNEGEN_DEFAULT    0
    #define Si21XXC_ATV_INT_SENSE_PROP_SNRLNEGEN_DISABLE  0
    #define Si21XXC_ATV_INT_SENSE_PROP_SNRLNEGEN_ENABLE   1

   /* ATV_INT_SENSE property, SNRLPOSEN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRLPOSEN_LSB         11
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRLPOSEN_MASK        0x01
   #define  Si21XXC_ATV_INT_SENSE_PROP_SNRLPOSEN_DEFAULT    1
    #define Si21XXC_ATV_INT_SENSE_PROP_SNRLPOSEN_DISABLE  0
    #define Si21XXC_ATV_INT_SENSE_PROP_SNRLPOSEN_ENABLE   1

#endif /* Si21XXC_ATV_INT_SENSE_PROP */

/* Si21XXC ATV_PGA_TARGET property definition */
#define   Si21XXC_ATV_PGA_TARGET_PROP 0x0617

#ifdef    Si21XXC_ATV_PGA_TARGET_PROP
  #define Si21XXC_ATV_PGA_TARGET_PROP_CODE 0x000617


    typedef struct { /* Si2190B_ATV_PGA_TARGET_PROP_struct */
      unsigned char   override_enable;
               char   pga_target;
   } Si21XXC_ATV_PGA_TARGET_PROP_struct;

   /* ATV_PGA_TARGET property, OVERRIDE_ENABLE field definition (NO TITLE)*/
   #define  Si21XXC_ATV_PGA_TARGET_PROP_OVERRIDE_ENABLE_LSB         8
   #define  Si21XXC_ATV_PGA_TARGET_PROP_OVERRIDE_ENABLE_MASK        0x01
   #define  Si21XXC_ATV_PGA_TARGET_PROP_OVERRIDE_ENABLE_DEFAULT    0
    #define Si21XXC_ATV_PGA_TARGET_PROP_OVERRIDE_ENABLE_DISABLE  0
    #define Si21XXC_ATV_PGA_TARGET_PROP_OVERRIDE_ENABLE_ENABLE   1

   /* ATV_PGA_TARGET property, PGA_TARGET field definition (NO TITLE)*/
   #define  Si21XXC_ATV_PGA_TARGET_PROP_PGA_TARGET_LSB         0
   #define  Si21XXC_ATV_PGA_TARGET_PROP_PGA_TARGET_MASK        0xff
   #define  Si21XXC_ATV_PGA_TARGET_PROP_PGA_TARGET_DEFAULT    0
    #define Si21XXC_ATV_PGA_TARGET_PROP_PGA_TARGET_PGA_TARGET_MIN  -13
    #define Si21XXC_ATV_PGA_TARGET_PROP_PGA_TARGET_PGA_TARGET_MAX  7

#endif /* Si21XXC_ATV_PGA_TARGET_PROP */

/* Si21XXC ATV_RF_TOP property definition */
#define   Si21XXC_ATV_RF_TOP_PROP 0x0612

#ifdef    Si21XXC_ATV_RF_TOP_PROP
  #define Si21XXC_ATV_RF_TOP_PROP_CODE 0x000612


    typedef struct { /* Si21XXC_ATV_RF_TOP_PROP_struct */
      unsigned char   atv_rf_top;
   } Si21XXC_ATV_RF_TOP_PROP_struct;

   /* ATV_RF_TOP property, ATV_RF_TOP field definition (NO TITLE)*/
   #define  Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_LSB         0
   #define  Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_MASK        0xff
   #define  Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_DEFAULT    0
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_AUTO   0
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_P2DB   4
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_P1DB   5
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_0DB    6
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_M1DB   7
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_M2DB   8
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_M3DB   9
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_M4DB   10
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_M5DB   11
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_M6DB   12
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_M7DB   13
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_M8DB   14
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_M9DB   15
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_M10DB  16
    #define Si21XXC_ATV_RF_TOP_PROP_ATV_RF_TOP_M11DB  17

#endif /* Si21XXC_ATV_RF_TOP_PROP */

/* Si21XXC ATV_RSQ_RSSI_THRESHOLD property definition */
#define   Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP 0x0605

#ifdef    Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP
  #define Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_CODE 0x000605


    typedef struct { /* Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_struct */
               char   hi;
               char   lo;
   } Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_struct;

   /* ATV_RSQ_RSSI_THRESHOLD property, HI field definition (NO TITLE)*/
   #define  Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_HI_LSB         8
   #define  Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_HI_MASK        0xff
   #define  Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_HI_DEFAULT    0
    #define Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_HI_HI_MIN  -128
    #define Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_HI_HI_MAX  127

   /* ATV_RSQ_RSSI_THRESHOLD property, LO field definition (NO TITLE)*/
   #define  Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_LO_LSB         0
   #define  Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_LO_MASK        0xff
   #define  Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_LO_DEFAULT    -70
    #define Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_LO_LO_MIN  -128
    #define Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_LO_LO_MAX  127

#endif /* Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP */

/* Si21XXC ATV_RSQ_SNR_THRESHOLD property definition */
#define   Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP 0x0606

#ifdef    Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP
  #define Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_CODE 0x000606


    typedef struct { /* Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_struct */
      unsigned char   hi;
      unsigned char   lo;
   } Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_struct;

   /* ATV_RSQ_SNR_THRESHOLD property, HI field definition (NO TITLE)*/
   #define  Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_HI_LSB         8
   #define  Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_HI_MASK        0xff
   #define  Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_HI_DEFAULT    45
    #define Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_HI_HI_MIN  0
    #define Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_HI_HI_MAX  255

   /* ATV_RSQ_SNR_THRESHOLD property, LO field definition (NO TITLE)*/
   #define  Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_LO_LSB         0
   #define  Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_LO_MASK        0xff
   #define  Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_LO_DEFAULT    25
    #define Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_LO_LO_MIN  0
    #define Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_LO_LO_MAX  255

#endif /* Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP */

/* Si21XXC ATV_SIF_OUT property definition */
#define   Si21XXC_ATV_SIF_OUT_PROP 0x060a

#ifdef    Si21XXC_ATV_SIF_OUT_PROP
  #define Si21XXC_ATV_SIF_OUT_PROP_CODE 0x00060a


    typedef struct { /* Si21XXC_ATV_SIF_OUT_PROP_struct */
      unsigned char   amp;
      unsigned char   offset;
   } Si21XXC_ATV_SIF_OUT_PROP_struct;

   /* ATV_SIF_OUT property, AMP field definition (NO TITLE)*/
   #define  Si21XXC_ATV_SIF_OUT_PROP_AMP_LSB         8
   #define  Si21XXC_ATV_SIF_OUT_PROP_AMP_MASK        0xff
   #define  Si21XXC_ATV_SIF_OUT_PROP_AMP_DEFAULT    60
    #define Si21XXC_ATV_SIF_OUT_PROP_AMP_AMP_MIN  0
    #define Si21XXC_ATV_SIF_OUT_PROP_AMP_AMP_MAX  255

   /* ATV_SIF_OUT property, OFFSET field definition (NO TITLE)*/
   #define  Si21XXC_ATV_SIF_OUT_PROP_OFFSET_LSB         0
   #define  Si21XXC_ATV_SIF_OUT_PROP_OFFSET_MASK        0xff
   #define  Si21XXC_ATV_SIF_OUT_PROP_OFFSET_DEFAULT    135
    #define Si21XXC_ATV_SIF_OUT_PROP_OFFSET_OFFSET_MIN  0
    #define Si21XXC_ATV_SIF_OUT_PROP_OFFSET_OFFSET_MAX  255

#endif /* Si21XXC_ATV_SIF_OUT_PROP */

/* Si21XXC ATV_SOUND_AGC_LIMIT property definition */
#define   Si21XXC_ATV_SOUND_AGC_LIMIT_PROP 0x0618

#ifdef    Si21XXC_ATV_SOUND_AGC_LIMIT_PROP
  #define Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_CODE 0x000618


    typedef struct { /* Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_struct */
               char   max_gain;
               char   min_gain;
   } Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_struct;

   /* ATV_SOUND_AGC_LIMIT property, MAX_GAIN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_MAX_GAIN_LSB         0
   #define  Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_MAX_GAIN_MASK        0xff
   #define  Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_MAX_GAIN_DEFAULT    84
    #define Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_MAX_GAIN_MAX_GAIN_MIN  -84
    #define Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_MAX_GAIN_MAX_GAIN_MAX  84

   /* ATV_SOUND_AGC_LIMIT property, MIN_GAIN field definition (NO TITLE)*/
   #define  Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_MIN_GAIN_LSB         8
   #define  Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_MIN_GAIN_MASK        0xff
   #define  Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_MIN_GAIN_DEFAULT    -84
    #define Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_MIN_GAIN_MIN_GAIN_MIN  -84
    #define Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_MIN_GAIN_MIN_GAIN_MAX  84

#endif /* Si21XXC_ATV_SOUND_AGC_LIMIT_PROP */

/* Si21XXC ATV_SOUND_AGC_SPEED property definition */
#define   Si21XXC_ATV_SOUND_AGC_SPEED_PROP 0x0619

#ifdef    Si21XXC_ATV_SOUND_AGC_SPEED_PROP
  #define Si21XXC_ATV_SOUND_AGC_SPEED_PROP_CODE 0x000619


    typedef struct { /* Si21XXC_ATV_SOUND_AGC_SPEED_PROP_struct */
      unsigned char   other_systems;
      unsigned char   system_l;
   } Si21XXC_ATV_SOUND_AGC_SPEED_PROP_struct;

   /* ATV_SOUND_AGC_SPEED property, OTHER_SYSTEMS field definition (NO TITLE)*/
   #define  Si21XXC_ATV_SOUND_AGC_SPEED_PROP_OTHER_SYSTEMS_LSB         8
   #define  Si21XXC_ATV_SOUND_AGC_SPEED_PROP_OTHER_SYSTEMS_MASK        0xff
   #define  Si21XXC_ATV_SOUND_AGC_SPEED_PROP_OTHER_SYSTEMS_DEFAULT    4
    #define Si21XXC_ATV_SOUND_AGC_SPEED_PROP_OTHER_SYSTEMS_OTHER_SYSTEMS_MIN  0
    #define Si21XXC_ATV_SOUND_AGC_SPEED_PROP_OTHER_SYSTEMS_OTHER_SYSTEMS_MAX  15

   /* ATV_SOUND_AGC_SPEED property, SYSTEM_L field definition (NO TITLE)*/
   #define  Si21XXC_ATV_SOUND_AGC_SPEED_PROP_SYSTEM_L_LSB         0
   #define  Si21XXC_ATV_SOUND_AGC_SPEED_PROP_SYSTEM_L_MASK        0xff
   #define  Si21XXC_ATV_SOUND_AGC_SPEED_PROP_SYSTEM_L_DEFAULT    5
    #define Si21XXC_ATV_SOUND_AGC_SPEED_PROP_SYSTEM_L_SYSTEM_L_MIN  0
    #define Si21XXC_ATV_SOUND_AGC_SPEED_PROP_SYSTEM_L_SYSTEM_L_MAX  15

#endif /* Si21XXC_ATV_SOUND_AGC_SPEED_PROP */

/* Si21XXC ATV_VIDEO_EQUALIZER property definition */
#define   Si21XXC_ATV_VIDEO_EQUALIZER_PROP 0x0608

#ifdef    Si21XXC_ATV_VIDEO_EQUALIZER_PROP
  #define Si21XXC_ATV_VIDEO_EQUALIZER_PROP_CODE 0x000608


    typedef struct { /* Si21XXC_ATV_VIDEO_EQUALIZER_PROP_struct */
               char   slope;
   } Si21XXC_ATV_VIDEO_EQUALIZER_PROP_struct;

   /* ATV_VIDEO_EQUALIZER property, SLOPE field definition (NO TITLE)*/
   #define  Si21XXC_ATV_VIDEO_EQUALIZER_PROP_SLOPE_LSB         0
   #define  Si21XXC_ATV_VIDEO_EQUALIZER_PROP_SLOPE_MASK        0xff
   #define  Si21XXC_ATV_VIDEO_EQUALIZER_PROP_SLOPE_DEFAULT    0
    #define Si21XXC_ATV_VIDEO_EQUALIZER_PROP_SLOPE_SLOPE_MIN  -25
    #define Si21XXC_ATV_VIDEO_EQUALIZER_PROP_SLOPE_SLOPE_MAX  15

#endif /* Si21XXC_ATV_VIDEO_EQUALIZER_PROP */

/* Si21XXC ATV_VIDEO_MODE property definition */
#define   Si21XXC_ATV_VIDEO_MODE_PROP 0x0604

#ifdef    Si21XXC_ATV_VIDEO_MODE_PROP
  #define Si21XXC_ATV_VIDEO_MODE_PROP_CODE 0x000604


    typedef struct { /* Si21XXC_ATV_VIDEO_MODE_PROP_struct */
      unsigned char   color;
      unsigned char   invert_signal;
      unsigned char   video_sys;
   } Si21XXC_ATV_VIDEO_MODE_PROP_struct;

   /* ATV_VIDEO_MODE property, COLOR field definition (NO TITLE)*/
   #define  Si21XXC_ATV_VIDEO_MODE_PROP_COLOR_LSB         4
   #define  Si21XXC_ATV_VIDEO_MODE_PROP_COLOR_MASK        0x01
   #define  Si21XXC_ATV_VIDEO_MODE_PROP_COLOR_DEFAULT    0
    #define Si21XXC_ATV_VIDEO_MODE_PROP_COLOR_PAL_NTSC  0
    #define Si21XXC_ATV_VIDEO_MODE_PROP_COLOR_SECAM     1

   /* ATV_VIDEO_MODE property, INVERT_SIGNAL field definition (NO TITLE)*/
   #define  Si21XXC_ATV_VIDEO_MODE_PROP_INVERT_SIGNAL_LSB         10
   #define  Si21XXC_ATV_VIDEO_MODE_PROP_INVERT_SIGNAL_MASK        0x01
   #define  Si21XXC_ATV_VIDEO_MODE_PROP_INVERT_SIGNAL_DEFAULT    0
    #define Si21XXC_ATV_VIDEO_MODE_PROP_INVERT_SIGNAL_NORMAL    0
    #define Si21XXC_ATV_VIDEO_MODE_PROP_INVERT_SIGNAL_INVERTED  1

   /* ATV_VIDEO_MODE property, VIDEO_SYS field definition (NO TITLE)*/
   #define  Si21XXC_ATV_VIDEO_MODE_PROP_VIDEO_SYS_LSB         0
   #define  Si21XXC_ATV_VIDEO_MODE_PROP_VIDEO_SYS_MASK        0x07
   #define  Si21XXC_ATV_VIDEO_MODE_PROP_VIDEO_SYS_DEFAULT    0
    #define Si21XXC_ATV_VIDEO_MODE_PROP_VIDEO_SYS_B   0
    #define Si21XXC_ATV_VIDEO_MODE_PROP_VIDEO_SYS_GH  1
    #define Si21XXC_ATV_VIDEO_MODE_PROP_VIDEO_SYS_M   2
    #define Si21XXC_ATV_VIDEO_MODE_PROP_VIDEO_SYS_N   3
    #define Si21XXC_ATV_VIDEO_MODE_PROP_VIDEO_SYS_I   4
    #define Si21XXC_ATV_VIDEO_MODE_PROP_VIDEO_SYS_DK  5
    #define Si21XXC_ATV_VIDEO_MODE_PROP_VIDEO_SYS_L   6
    #define Si21XXC_ATV_VIDEO_MODE_PROP_VIDEO_SYS_LP  7

#endif /* Si21XXC_ATV_VIDEO_MODE_PROP */

/* Si21XXC ATV_VSNR_CAP property definition */
#define   Si21XXC_ATV_VSNR_CAP_PROP 0x0616

#ifdef    Si21XXC_ATV_VSNR_CAP_PROP
  #define Si21XXC_ATV_VSNR_CAP_PROP_CODE 0x000616


    typedef struct { /* Si21XXC_ATV_VSNR_CAP_PROP_struct */
      unsigned char   atv_vsnr_cap;
   } Si21XXC_ATV_VSNR_CAP_PROP_struct;

   /* ATV_VSNR_CAP property, ATV_VSNR_CAP field definition (NO TITLE)*/
   #define  Si21XXC_ATV_VSNR_CAP_PROP_ATV_VSNR_CAP_LSB         0
   #define  Si21XXC_ATV_VSNR_CAP_PROP_ATV_VSNR_CAP_MASK        0xff
   #define  Si21XXC_ATV_VSNR_CAP_PROP_ATV_VSNR_CAP_DEFAULT    0
    #define Si21XXC_ATV_VSNR_CAP_PROP_ATV_VSNR_CAP_ATV_VSNR_CAP_MIN  0
    #define Si21XXC_ATV_VSNR_CAP_PROP_ATV_VSNR_CAP_ATV_VSNR_CAP_MAX  127

#endif /* Si21XXC_ATV_VSNR_CAP_PROP */

/* Si21XXC CRYSTAL_TRIM property definition */
#define   Si21XXC_CRYSTAL_TRIM_PROP 0x0402

#ifdef    Si21XXC_CRYSTAL_TRIM_PROP
  #define Si21XXC_CRYSTAL_TRIM_PROP_CODE 0x000402


    typedef struct { /* Si21XXC_CRYSTAL_TRIM_PROP_struct */
      unsigned char   xo_cap;
   } Si21XXC_CRYSTAL_TRIM_PROP_struct;

   /* CRYSTAL_TRIM property, XO_CAP field definition (NO TITLE)*/
   #define  Si21XXC_CRYSTAL_TRIM_PROP_XO_CAP_LSB         0
   #define  Si21XXC_CRYSTAL_TRIM_PROP_XO_CAP_MASK        0x0f
   #define  Si21XXC_CRYSTAL_TRIM_PROP_XO_CAP_DEFAULT    8
    #define Si21XXC_CRYSTAL_TRIM_PROP_XO_CAP_4P7PF   0
    #define Si21XXC_CRYSTAL_TRIM_PROP_XO_CAP_5P2PF   2
    #define Si21XXC_CRYSTAL_TRIM_PROP_XO_CAP_5P7PF   4
    #define Si21XXC_CRYSTAL_TRIM_PROP_XO_CAP_6P2PF   6
    #define Si21XXC_CRYSTAL_TRIM_PROP_XO_CAP_6P7PF   8
    #define Si21XXC_CRYSTAL_TRIM_PROP_XO_CAP_7P2PF   10
    #define Si21XXC_CRYSTAL_TRIM_PROP_XO_CAP_7P7PF   12
    #define Si21XXC_CRYSTAL_TRIM_PROP_XO_CAP_8P2PF   14

#endif /* Si21XXC_CRYSTAL_TRIM_PROP */

/* Si21XXC DTV_AGC_AUTO_FREEZE property definition */
#define   Si21XXC_DTV_AGC_AUTO_FREEZE_PROP 0x0714

#ifdef    Si21XXC_DTV_AGC_AUTO_FREEZE_PROP
  #define Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_CODE 0x000714


    typedef struct { /* Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_struct */
      unsigned char   thld;
      unsigned char   timeout;
   } Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_struct;

   /* DTV_AGC_AUTO_FREEZE property, THLD field definition (NO TITLE)*/
   #define  Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_THLD_LSB         0
   #define  Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_THLD_MASK        0xff
   #define  Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_THLD_DEFAULT    255
    #define Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_THLD_THLD_MIN  0
    #define Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_THLD_THLD_MAX  255

   /* DTV_AGC_AUTO_FREEZE property, TIMEOUT field definition (NO TITLE)*/
   #define  Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_TIMEOUT_LSB         8
   #define  Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_TIMEOUT_MASK        0xff
   #define  Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_TIMEOUT_DEFAULT    1
    #define Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_TIMEOUT_TIMEOUT_MIN  1
    #define Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_TIMEOUT_TIMEOUT_MAX  250

#endif /* Si21XXC_DTV_AGC_AUTO_FREEZE_PROP */

/* Si21XXC DTV_AGC_FREEZE_INPUT property definition */
#define   Si21XXC_DTV_AGC_FREEZE_INPUT_PROP 0x0711

#ifdef    Si21XXC_DTV_AGC_FREEZE_INPUT_PROP
  #define Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_CODE 0x000711


    typedef struct { /* Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_struct */
      unsigned char   level;
      unsigned char   pin;
   } Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_struct;

   /* DTV_AGC_FREEZE_INPUT property, LEVEL field definition (NO TITLE)*/
   #define  Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_LEVEL_LSB         0
   #define  Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_LEVEL_MASK        0x01
   #define  Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_LEVEL_DEFAULT    0
    #define Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_LEVEL_LOW   0
    #define Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_LEVEL_HIGH  1

   /* DTV_AGC_FREEZE_INPUT property, PIN field definition (NO TITLE)*/
   #define  Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_PIN_LSB         1
   #define  Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_PIN_MASK        0x07
   #define  Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_PIN_DEFAULT    0
    #define Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_PIN_NONE      0
    #define Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_PIN_GPIO1     1
    #define Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_PIN_GPIO2     2
    #define Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_PIN_RESERVED  3
    #define Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_PIN_AGC1      4
    #define Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_PIN_AGC2      5

#endif /* Si21XXC_DTV_AGC_FREEZE_INPUT_PROP */

/* Si21XXC DTV_AGC_SPEED property definition */
#define   Si21XXC_DTV_AGC_SPEED_PROP 0x0708

#ifdef    Si21XXC_DTV_AGC_SPEED_PROP
  #define Si21XXC_DTV_AGC_SPEED_PROP_CODE 0x000708


    typedef struct { /* Si21XXC_DTV_AGC_SPEED_PROP_struct */
      unsigned char   agc_decim;
      unsigned char   if_agc_speed;
   } Si21XXC_DTV_AGC_SPEED_PROP_struct;

   /* DTV_AGC_SPEED property, AGC_DECIM field definition (NO TITLE)*/
   #define  Si21XXC_DTV_AGC_SPEED_PROP_AGC_DECIM_LSB         8
   #define  Si21XXC_DTV_AGC_SPEED_PROP_AGC_DECIM_MASK        0x03
   #define  Si21XXC_DTV_AGC_SPEED_PROP_AGC_DECIM_DEFAULT    0
    #define Si21XXC_DTV_AGC_SPEED_PROP_AGC_DECIM_OFF  0
    #define Si21XXC_DTV_AGC_SPEED_PROP_AGC_DECIM_2    1
    #define Si21XXC_DTV_AGC_SPEED_PROP_AGC_DECIM_4    2
    #define Si21XXC_DTV_AGC_SPEED_PROP_AGC_DECIM_8    3

   /* DTV_AGC_SPEED property, IF_AGC_SPEED field definition (NO TITLE)*/
   #define  Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_LSB         0
   #define  Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_MASK        0xff
   #define  Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_DEFAULT    0
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_AUTO  0
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_39    39
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_54    54
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_63    63
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_89    89
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_105   105
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_121   121
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_137   137
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_158   158
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_172   172
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_185   185
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_196   196
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_206   206
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_216   216
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_219   219
    #define Si21XXC_DTV_AGC_SPEED_PROP_IF_AGC_SPEED_222   222

#endif /* Si21XXC_DTV_AGC_SPEED_PROP */

/* Si21XXC DTV_CONFIG_IF_PORT property definition */
#define   Si21XXC_DTV_CONFIG_IF_PORT_PROP 0x0702

#ifdef    Si21XXC_DTV_CONFIG_IF_PORT_PROP
  #define Si21XXC_DTV_CONFIG_IF_PORT_PROP_CODE 0x000702


    typedef struct { /* Si21XXC_DTV_CONFIG_IF_PORT_PROP_struct */
      unsigned char   dtv_agc_source;
      unsigned char   dtv_out_type;
   } Si21XXC_DTV_CONFIG_IF_PORT_PROP_struct;

   /* DTV_CONFIG_IF_PORT property, DTV_AGC_SOURCE field definition (NO TITLE)*/
   #define  Si21XXC_DTV_CONFIG_IF_PORT_PROP_DTV_AGC_SOURCE_LSB         8
   #define  Si21XXC_DTV_CONFIG_IF_PORT_PROP_DTV_AGC_SOURCE_MASK        0x07
   #define  Si21XXC_DTV_CONFIG_IF_PORT_PROP_DTV_AGC_SOURCE_DEFAULT    0
    #define Si21XXC_DTV_CONFIG_IF_PORT_PROP_DTV_AGC_SOURCE_INTERNAL   0
    #define Si21XXC_DTV_CONFIG_IF_PORT_PROP_DTV_AGC_SOURCE_AGC1_3DB   1
    #define Si21XXC_DTV_CONFIG_IF_PORT_PROP_DTV_AGC_SOURCE_AGC2_3DB   2

   /* DTV_CONFIG_IF_PORT property, DTV_OUT_TYPE field definition (NO TITLE)*/
   #define  Si21XXC_DTV_CONFIG_IF_PORT_PROP_DTV_OUT_TYPE_LSB         0
   #define  Si21XXC_DTV_CONFIG_IF_PORT_PROP_DTV_OUT_TYPE_MASK        0x0f
   #define  Si21XXC_DTV_CONFIG_IF_PORT_PROP_DTV_OUT_TYPE_DEFAULT    0
    #define Si21XXC_DTV_CONFIG_IF_PORT_PROP_DTV_OUT_TYPE_LIF_IF1      0
    #define Si21XXC_DTV_CONFIG_IF_PORT_PROP_DTV_OUT_TYPE_LIF_SE_IF1A  4

#endif /* Si21XXC_DTV_CONFIG_IF_PORT_PROP */

/* Si21XXC DTV_EXT_AGC property definition */
#define   Si21XXC_DTV_EXT_AGC_PROP 0x0705

#ifdef    Si21XXC_DTV_EXT_AGC_PROP
  #define Si21XXC_DTV_EXT_AGC_PROP_CODE 0x000705


    typedef struct { /* Si21XXC_DTV_EXT_AGC_PROP_struct */
      unsigned char   max_10mv;
      unsigned char   min_10mv;
   } Si21XXC_DTV_EXT_AGC_PROP_struct;

   /* DTV_EXT_AGC property, MAX_10MV field definition (NO TITLE)*/
   #define  Si21XXC_DTV_EXT_AGC_PROP_MAX_10MV_LSB         8
   #define  Si21XXC_DTV_EXT_AGC_PROP_MAX_10MV_MASK        0xff
   #define  Si21XXC_DTV_EXT_AGC_PROP_MAX_10MV_DEFAULT    200
    #define Si21XXC_DTV_EXT_AGC_PROP_MAX_10MV_MAX_10MV_MIN  0
    #define Si21XXC_DTV_EXT_AGC_PROP_MAX_10MV_MAX_10MV_MAX  255

   /* DTV_EXT_AGC property, MIN_10MV field definition (NO TITLE)*/
   #define  Si21XXC_DTV_EXT_AGC_PROP_MIN_10MV_LSB         0
   #define  Si21XXC_DTV_EXT_AGC_PROP_MIN_10MV_MASK        0xff
   #define  Si21XXC_DTV_EXT_AGC_PROP_MIN_10MV_DEFAULT    50
    #define Si21XXC_DTV_EXT_AGC_PROP_MIN_10MV_MIN_10MV_MIN  0
    #define Si21XXC_DTV_EXT_AGC_PROP_MIN_10MV_MIN_10MV_MAX  255

#endif /* Si21XXC_DTV_EXT_AGC_PROP */

/* Si21XXC DTV_IEN property definition */
#define   Si21XXC_DTV_IEN_PROP 0x0701

#ifdef    Si21XXC_DTV_IEN_PROP
  #define Si21XXC_DTV_IEN_PROP_CODE 0x000701


    typedef struct { /* Si21XXC_DTV_IEN_PROP_struct */
      unsigned char   chlien;
   } Si21XXC_DTV_IEN_PROP_struct;

   /* DTV_IEN property, CHLIEN field definition (NO TITLE)*/
   #define  Si21XXC_DTV_IEN_PROP_CHLIEN_LSB         0
   #define  Si21XXC_DTV_IEN_PROP_CHLIEN_MASK        0x01
   #define  Si21XXC_DTV_IEN_PROP_CHLIEN_DEFAULT    1
    #define Si21XXC_DTV_IEN_PROP_CHLIEN_DISABLE  0
    #define Si21XXC_DTV_IEN_PROP_CHLIEN_ENABLE   1

#endif /* Si21XXC_DTV_IEN_PROP */

/* Si21XXC DTV_IF_AGC_SPEED property definition */
#define   Si21XXC_DTV_IF_AGC_SPEED_PROP 0x0717

#ifdef    Si21XXC_DTV_IF_AGC_SPEED_PROP
  #define Si21XXC_DTV_IF_AGC_SPEED_PROP_CODE 0x000717


    typedef struct { /* Si21XXC_DTV_IF_AGC_SPEED_PROP_struct */
      unsigned char   attack;
      unsigned char   decay;
   } Si21XXC_DTV_IF_AGC_SPEED_PROP_struct;

   /* DTV_IF_AGC_SPEED property, ATTACK field definition (NO TITLE)*/
   #define  Si21XXC_DTV_IF_AGC_SPEED_PROP_ATTACK_LSB         0
   #define  Si21XXC_DTV_IF_AGC_SPEED_PROP_ATTACK_MASK        0xff
   #define  Si21XXC_DTV_IF_AGC_SPEED_PROP_ATTACK_DEFAULT    0
    #define Si21XXC_DTV_IF_AGC_SPEED_PROP_ATTACK_AUTO  0

    #define Si21XXC_DTV_IF_AGC_SPEED_PROP_ATTACK_ATTACK_MIN  0
    #define Si21XXC_DTV_IF_AGC_SPEED_PROP_ATTACK_ATTACK_MAX  231

   /* DTV_IF_AGC_SPEED property, DECAY field definition (NO TITLE)*/
   #define  Si21XXC_DTV_IF_AGC_SPEED_PROP_DECAY_LSB         8
   #define  Si21XXC_DTV_IF_AGC_SPEED_PROP_DECAY_MASK        0xff
   #define  Si21XXC_DTV_IF_AGC_SPEED_PROP_DECAY_DEFAULT    0
    #define Si21XXC_DTV_IF_AGC_SPEED_PROP_DECAY_AUTO  0

    #define Si21XXC_DTV_IF_AGC_SPEED_PROP_DECAY_DECAY_MIN  0
    #define Si21XXC_DTV_IF_AGC_SPEED_PROP_DECAY_DECAY_MAX  231

#endif /* Si21XXC_DTV_IF_AGC_SPEED_PROP */

/* Si21XXC DTV_INITIAL_AGC_SPEED property definition */
#define   Si21XXC_DTV_INITIAL_AGC_SPEED_PROP 0x070d

#ifdef    Si21XXC_DTV_INITIAL_AGC_SPEED_PROP
  #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_CODE 0x00070d


    typedef struct { /* Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_struct */
      unsigned char   agc_decim;
      unsigned char   if_agc_speed;
   } Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_struct;

   /* DTV_INITIAL_AGC_SPEED property, AGC_DECIM field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_AGC_DECIM_LSB         8
   #define  Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_AGC_DECIM_MASK        0x03
   #define  Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_AGC_DECIM_DEFAULT    0
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_AGC_DECIM_OFF  0
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_AGC_DECIM_2    1
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_AGC_DECIM_4    2
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_AGC_DECIM_8    3

   /* DTV_INITIAL_AGC_SPEED property, IF_AGC_SPEED field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_LSB         0
   #define  Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_MASK        0xff
   #define  Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_DEFAULT    0
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_AUTO  0
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_39    39
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_54    54
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_63    63
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_89    89
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_105   105
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_121   121
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_137   137
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_158   158
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_172   172
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_185   185
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_196   196
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_206   206
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_216   216
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_219   219
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_IF_AGC_SPEED_222   222

#endif /* Si21XXC_DTV_INITIAL_AGC_SPEED_PROP */

/* Si21XXC DTV_INITIAL_AGC_SPEED_PERIOD property definition */
#define   Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP 0x070e

#ifdef    Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP
  #define Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP_CODE 0x00070e


    typedef struct { /* Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP_struct */
      unsigned int    period;
   } Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP_struct;

   /* DTV_INITIAL_AGC_SPEED_PERIOD property, PERIOD field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP_PERIOD_LSB         0
   #define  Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP_PERIOD_MASK        0xffff
   #define  Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP_PERIOD_DEFAULT    0
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP_PERIOD_PERIOD_MIN  0
    #define Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP_PERIOD_PERIOD_MAX  65535

#endif /* Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP */

/* Si21XXC DTV_INTERNAL_ZIF property definition */
#define   Si21XXC_DTV_INTERNAL_ZIF_PROP 0x0710

#ifdef    Si21XXC_DTV_INTERNAL_ZIF_PROP
  #define Si21XXC_DTV_INTERNAL_ZIF_PROP_CODE 0x000710


    typedef struct { /* Si21XXC_DTV_INTERNAL_ZIF_PROP_struct */
      unsigned char   atsc;
      unsigned char   dtmb;
      unsigned char   dvbc;
      unsigned char   dvbt;
      unsigned char   isdbc;
      unsigned char   isdbt;
      unsigned char   qam_us;
   } Si21XXC_DTV_INTERNAL_ZIF_PROP_struct;

   /* DTV_INTERNAL_ZIF property, ATSC field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_ATSC_LSB         0
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_ATSC_MASK        0x01
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_ATSC_DEFAULT    1
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_ATSC_LIF  0
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_ATSC_ZIF  1

   /* DTV_INTERNAL_ZIF property, DTMB field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_DTMB_LSB         6
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_DTMB_MASK        0x01
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_DTMB_DEFAULT    0
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_DTMB_LIF  0
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_DTMB_ZIF  1

   /* DTV_INTERNAL_ZIF property, DVBC field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_DVBC_LSB         3
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_DVBC_MASK        0x01
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_DVBC_DEFAULT    1
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_DVBC_LIF  0
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_DVBC_ZIF  1

   /* DTV_INTERNAL_ZIF property, DVBT field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_DVBT_LSB         2
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_DVBT_MASK        0x01
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_DVBT_DEFAULT    1
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_DVBT_LIF  0
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_DVBT_ZIF  1

   /* DTV_INTERNAL_ZIF property, ISDBC field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_ISDBC_LSB         5
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_ISDBC_MASK        0x01
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_ISDBC_DEFAULT    1
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_ISDBC_LIF  0
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_ISDBC_ZIF  1

   /* DTV_INTERNAL_ZIF property, ISDBT field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_ISDBT_LSB         4
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_ISDBT_MASK        0x01
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_ISDBT_DEFAULT    1
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_ISDBT_LIF  0
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_ISDBT_ZIF  1

   /* DTV_INTERNAL_ZIF property, QAM_US field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_QAM_US_LSB         1
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_QAM_US_MASK        0x01
   #define  Si21XXC_DTV_INTERNAL_ZIF_PROP_QAM_US_DEFAULT    1
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_QAM_US_LIF  0
    #define Si21XXC_DTV_INTERNAL_ZIF_PROP_QAM_US_ZIF  1

#endif /* Si21XXC_DTV_INTERNAL_ZIF_PROP */

/* Si21XXC DTV_INT_SENSE property definition */
#define   Si21XXC_DTV_INT_SENSE_PROP 0x070a

#ifdef    Si21XXC_DTV_INT_SENSE_PROP
  #define Si21XXC_DTV_INT_SENSE_PROP_CODE 0x00070a


    typedef struct { /* Si21XXC_DTV_INT_SENSE_PROP_struct */
      unsigned char   chlnegen;
      unsigned char   chlposen;
   } Si21XXC_DTV_INT_SENSE_PROP_struct;

   /* DTV_INT_SENSE property, CHLNEGEN field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INT_SENSE_PROP_CHLNEGEN_LSB         0
   #define  Si21XXC_DTV_INT_SENSE_PROP_CHLNEGEN_MASK        0x01
   #define  Si21XXC_DTV_INT_SENSE_PROP_CHLNEGEN_DEFAULT    0
    #define Si21XXC_DTV_INT_SENSE_PROP_CHLNEGEN_DISABLE  0
    #define Si21XXC_DTV_INT_SENSE_PROP_CHLNEGEN_ENABLE   1

   /* DTV_INT_SENSE property, CHLPOSEN field definition (NO TITLE)*/
   #define  Si21XXC_DTV_INT_SENSE_PROP_CHLPOSEN_LSB         8
   #define  Si21XXC_DTV_INT_SENSE_PROP_CHLPOSEN_MASK        0x01
   #define  Si21XXC_DTV_INT_SENSE_PROP_CHLPOSEN_DEFAULT    1
    #define Si21XXC_DTV_INT_SENSE_PROP_CHLPOSEN_DISABLE  0
    #define Si21XXC_DTV_INT_SENSE_PROP_CHLPOSEN_ENABLE   1

#endif /* Si21XXC_DTV_INT_SENSE_PROP */

/* Si21XXC DTV_LIF_FREQ property definition */
#define   Si21XXC_DTV_LIF_FREQ_PROP 0x0706

#ifdef    Si21XXC_DTV_LIF_FREQ_PROP
  #define Si21XXC_DTV_LIF_FREQ_PROP_CODE 0x000706


    typedef struct { /* Si21XXC_DTV_LIF_FREQ_PROP_struct */
      unsigned int    offset;
   } Si21XXC_DTV_LIF_FREQ_PROP_struct;

   /* DTV_LIF_FREQ property, OFFSET field definition (NO TITLE)*/
   #define  Si21XXC_DTV_LIF_FREQ_PROP_OFFSET_LSB         0
   #define  Si21XXC_DTV_LIF_FREQ_PROP_OFFSET_MASK        0xffff
   #define  Si21XXC_DTV_LIF_FREQ_PROP_OFFSET_DEFAULT    5000
    #define Si21XXC_DTV_LIF_FREQ_PROP_OFFSET_OFFSET_MIN  0
    #define Si21XXC_DTV_LIF_FREQ_PROP_OFFSET_OFFSET_MAX  7000

#endif /* Si21XXC_DTV_LIF_FREQ_PROP */

/* Si21XXC DTV_LIF_OUT property definition */
#define   Si21XXC_DTV_LIF_OUT_PROP 0x0707

#ifdef    Si21XXC_DTV_LIF_OUT_PROP
  #define Si21XXC_DTV_LIF_OUT_PROP_CODE 0x000707


    typedef struct { /* Si21XXC_DTV_LIF_OUT_PROP_struct */
      unsigned char   amp;
      unsigned char   offset;
   } Si21XXC_DTV_LIF_OUT_PROP_struct;

   /* DTV_LIF_OUT property, AMP field definition (NO TITLE)*/
   #define  Si21XXC_DTV_LIF_OUT_PROP_AMP_LSB         8
   #define  Si21XXC_DTV_LIF_OUT_PROP_AMP_MASK        0xff
   #define  Si21XXC_DTV_LIF_OUT_PROP_AMP_DEFAULT    27
    #define Si21XXC_DTV_LIF_OUT_PROP_AMP_AMP_MIN  0
    #define Si21XXC_DTV_LIF_OUT_PROP_AMP_AMP_MAX  255

   /* DTV_LIF_OUT property, OFFSET field definition (NO TITLE)*/
   #define  Si21XXC_DTV_LIF_OUT_PROP_OFFSET_LSB         0
   #define  Si21XXC_DTV_LIF_OUT_PROP_OFFSET_MASK        0xff
   #define  Si21XXC_DTV_LIF_OUT_PROP_OFFSET_DEFAULT    148
    #define Si21XXC_DTV_LIF_OUT_PROP_OFFSET_OFFSET_MIN  0
    #define Si21XXC_DTV_LIF_OUT_PROP_OFFSET_OFFSET_MAX  255

#endif /* Si21XXC_DTV_LIF_OUT_PROP */

/* Si21XXC DTV_MODE property definition */
#define   Si21XXC_DTV_MODE_PROP 0x0703

#ifdef    Si21XXC_DTV_MODE_PROP
  #define Si21XXC_DTV_MODE_PROP_CODE 0x000703


    typedef struct { /* Si21XXC_DTV_MODE_PROP_struct */
      unsigned char   bw;
      unsigned char   invert_spectrum;
      unsigned char   modulation;
   } Si21XXC_DTV_MODE_PROP_struct;

   /* DTV_MODE property, BW field definition (NO TITLE)*/
   #define  Si21XXC_DTV_MODE_PROP_BW_LSB         0
   #define  Si21XXC_DTV_MODE_PROP_BW_MASK        0x0f
   #define  Si21XXC_DTV_MODE_PROP_BW_DEFAULT    8
    #define Si21XXC_DTV_MODE_PROP_BW_BW_6MHZ  6
    #define Si21XXC_DTV_MODE_PROP_BW_BW_7MHZ  7
    #define Si21XXC_DTV_MODE_PROP_BW_BW_8MHZ  8
    #define Si21XXC_DTV_MODE_PROP_BW_BW_1P7MHZ  9
    #define Si21XXC_DTV_MODE_PROP_BW_BW_6P1MHZ  10

   /* DTV_MODE property, INVERT_SPECTRUM field definition (NO TITLE)*/
   #define  Si21XXC_DTV_MODE_PROP_INVERT_SPECTRUM_LSB         8
   #define  Si21XXC_DTV_MODE_PROP_INVERT_SPECTRUM_MASK        0x01
   #define  Si21XXC_DTV_MODE_PROP_INVERT_SPECTRUM_DEFAULT    0
    #define Si21XXC_DTV_MODE_PROP_INVERT_SPECTRUM_NORMAL    0
    #define Si21XXC_DTV_MODE_PROP_INVERT_SPECTRUM_INVERTED  1

   /* DTV_MODE property, MODULATION field definition (NO TITLE)*/
   #define  Si21XXC_DTV_MODE_PROP_MODULATION_LSB         4
   #define  Si21XXC_DTV_MODE_PROP_MODULATION_MASK        0x0f
   #define  Si21XXC_DTV_MODE_PROP_MODULATION_DEFAULT    2
    #define Si21XXC_DTV_MODE_PROP_MODULATION_ATSC    0
    #define Si21XXC_DTV_MODE_PROP_MODULATION_QAM_US  1
    #define Si21XXC_DTV_MODE_PROP_MODULATION_DVBT    2
    #define Si21XXC_DTV_MODE_PROP_MODULATION_DVBC    3
    #define Si21XXC_DTV_MODE_PROP_MODULATION_ISDBT   4
    #define Si21XXC_DTV_MODE_PROP_MODULATION_ISDBC   5
    #define Si21XXC_DTV_MODE_PROP_MODULATION_DTMB    6

#endif /* Si21XXC_DTV_MODE_PROP */

/* Si21XXC DTV_RF_AGC_SPEED property definition */
#define   Si21XXC_DTV_RF_AGC_SPEED_PROP 0x0716

#ifdef    Si21XXC_DTV_RF_AGC_SPEED_PROP
  #define Si21XXC_DTV_RF_AGC_SPEED_PROP_CODE 0x000716


    typedef struct { /* Si21XXC_DTV_RF_AGC_SPEED_PROP_struct */
      unsigned char   attack;
      unsigned char   decay;
   } Si21XXC_DTV_RF_AGC_SPEED_PROP_struct;

   /* DTV_RF_AGC_SPEED property, ATTACK field definition (NO TITLE)*/
   #define  Si21XXC_DTV_RF_AGC_SPEED_PROP_ATTACK_LSB         0
   #define  Si21XXC_DTV_RF_AGC_SPEED_PROP_ATTACK_MASK        0xff
   #define  Si21XXC_DTV_RF_AGC_SPEED_PROP_ATTACK_DEFAULT    0
    #define Si21XXC_DTV_RF_AGC_SPEED_PROP_ATTACK_ATTACK_MIN  0
    #define Si21XXC_DTV_RF_AGC_SPEED_PROP_ATTACK_ATTACK_MAX  231
    #define Si21XXC_DTV_RF_AGC_SPEED_PROP_ATTACK_AUTO  0

   /* DTV_RF_AGC_SPEED property, DECAY field definition (NO TITLE)*/
   #define  Si21XXC_DTV_RF_AGC_SPEED_PROP_DECAY_LSB         8
   #define  Si21XXC_DTV_RF_AGC_SPEED_PROP_DECAY_MASK        0xff
   #define  Si21XXC_DTV_RF_AGC_SPEED_PROP_DECAY_DEFAULT    0
    #define Si21XXC_DTV_RF_AGC_SPEED_PROP_DECAY_DECAY_MIN  0
    #define Si21XXC_DTV_RF_AGC_SPEED_PROP_DECAY_DECAY_MAX  231

   #define Si21XXC_DTV_RF_AGC_SPEED_PROP_DECAY_AUTO  0
#endif /* Si21XXC_DTV_RF_AGC_SPEED_PROP */

/* Si21XXC DTV_RF_TOP property definition */
#define   Si21XXC_DTV_RF_TOP_PROP 0x0709

#ifdef    Si21XXC_DTV_RF_TOP_PROP
  #define Si21XXC_DTV_RF_TOP_PROP_CODE 0x000709


    typedef struct { /* Si21XXC_DTV_RF_TOP_PROP_struct */
      unsigned char   dtv_rf_top;
   } Si21XXC_DTV_RF_TOP_PROP_struct;

   /* DTV_RF_TOP property, DTV_RF_TOP field definition (NO TITLE)*/
   #define  Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_LSB         0
   #define  Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_MASK        0xff
   #define  Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_DEFAULT    0
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_AUTO     0
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P6DB     9
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P5P5DB   10
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P5DB     11
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P4P5DB   12
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P4DB     13
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P3P5DB   14
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P3DB     15
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P2P5DB   16
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P2DB     17
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P1P5DB   18
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P1DB     19
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_P0P5DB   20
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_0DB      21
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M0P5DB   22
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M1DB     23
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M1P5DB   24
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M2DB     25
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M2P5DB   26
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M3DB     27
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M3P5DB   28
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M4DB     29
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M4P5DB   30
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M5DB     31
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M5P5DB   32
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M6DB     33
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M6P5DB   34
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M7DB     35
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M7P5DB   36
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M8DB     37
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M8P5DB   38
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M9DB     39
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M9P5DB   40
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M10DB    41
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M10P5DB  42
    #define Si21XXC_DTV_RF_TOP_PROP_DTV_RF_TOP_M11DB    43

#endif /* Si21XXC_DTV_RF_TOP_PROP */

/* Si21XXC DTV_RSQ_RSSI_THRESHOLD property definition */
#define   Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP 0x0704

#ifdef    Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP
  #define Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_CODE 0x000704


    typedef struct { /* Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_struct */
               char   hi;
               char   lo;
   } Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_struct;

   /* DTV_RSQ_RSSI_THRESHOLD property, HI field definition (NO TITLE)*/
   #define  Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_HI_LSB         8
   #define  Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_HI_MASK        0xff
   #define  Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_HI_DEFAULT    0
    #define Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_HI_HI_MIN  -128
    #define Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_HI_HI_MAX  127

   /* DTV_RSQ_RSSI_THRESHOLD property, LO field definition (NO TITLE)*/
   #define  Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_LO_LSB         0
   #define  Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_LO_MASK        0xff
   #define  Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_LO_DEFAULT    -80
    #define Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_LO_LO_MIN  -128
    #define Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_LO_LO_MAX  127

#endif /* Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP */

/* Si21XXC DTV_WB_AGC_SPEED property definition */
#define   Si21XXC_DTV_WB_AGC_SPEED_PROP 0x0718

#ifdef    Si21XXC_DTV_WB_AGC_SPEED_PROP
  #define Si21XXC_DTV_WB_AGC_SPEED_PROP_CODE 0x000718


    typedef struct { /* Si21XXC_DTV_WB_AGC_SPEED_PROP_struct */
      unsigned char   attack;
      unsigned char   decay;
   } Si21XXC_DTV_WB_AGC_SPEED_PROP_struct;

   /* DTV_WB_AGC_SPEED property, ATTACK field definition (NO TITLE)*/
   #define  Si21XXC_DTV_WB_AGC_SPEED_PROP_ATTACK_LSB         0
   #define  Si21XXC_DTV_WB_AGC_SPEED_PROP_ATTACK_MASK        0xff
   #define  Si21XXC_DTV_WB_AGC_SPEED_PROP_ATTACK_DEFAULT    0
    #define Si21XXC_DTV_WB_AGC_SPEED_PROP_ATTACK_AUTO  0

    #define Si21XXC_DTV_WB_AGC_SPEED_PROP_ATTACK_ATTACK_MIN  0
    #define Si21XXC_DTV_WB_AGC_SPEED_PROP_ATTACK_ATTACK_MAX  231

   /* DTV_WB_AGC_SPEED property, DECAY field definition (NO TITLE)*/
   #define  Si21XXC_DTV_WB_AGC_SPEED_PROP_DECAY_LSB         8
   #define  Si21XXC_DTV_WB_AGC_SPEED_PROP_DECAY_MASK        0xff
   #define  Si21XXC_DTV_WB_AGC_SPEED_PROP_DECAY_DEFAULT    0
    #define Si21XXC_DTV_WB_AGC_SPEED_PROP_DECAY_AUTO  0

    #define Si21XXC_DTV_WB_AGC_SPEED_PROP_DECAY_DECAY_MIN  0
    #define Si21XXC_DTV_WB_AGC_SPEED_PROP_DECAY_DECAY_MAX  231

#endif /* Si21XXC_DTV_WB_AGC_SPEED_PROP */


/* Si21XXC MASTER_IEN property definition */
#define   Si21XXC_MASTER_IEN_PROP 0x0401

#ifdef    Si21XXC_MASTER_IEN_PROP
  #define Si21XXC_MASTER_IEN_PROP_CODE 0x000401


    typedef struct { /* Si21XXC_MASTER_IEN_PROP_struct */
      unsigned char   atvien;
      unsigned char   ctsien;
      unsigned char   dtvien;
      unsigned char   errien;
      unsigned char   tunien;
   } Si21XXC_MASTER_IEN_PROP_struct;

   /* MASTER_IEN property, ATVIEN field definition (NO TITLE)*/
   #define  Si21XXC_MASTER_IEN_PROP_ATVIEN_LSB         1
   #define  Si21XXC_MASTER_IEN_PROP_ATVIEN_MASK        0x01
   #define  Si21XXC_MASTER_IEN_PROP_ATVIEN_DEFAULT    0
    #define Si21XXC_MASTER_IEN_PROP_ATVIEN_OFF  0
    #define Si21XXC_MASTER_IEN_PROP_ATVIEN_ON   1

   /* MASTER_IEN property, CTSIEN field definition (NO TITLE)*/
   #define  Si21XXC_MASTER_IEN_PROP_CTSIEN_LSB         7
   #define  Si21XXC_MASTER_IEN_PROP_CTSIEN_MASK        0x01
   #define  Si21XXC_MASTER_IEN_PROP_CTSIEN_DEFAULT    0
    #define Si21XXC_MASTER_IEN_PROP_CTSIEN_OFF  0
    #define Si21XXC_MASTER_IEN_PROP_CTSIEN_ON   1

   /* MASTER_IEN property, DTVIEN field definition (NO TITLE)*/
   #define  Si21XXC_MASTER_IEN_PROP_DTVIEN_LSB         2
   #define  Si21XXC_MASTER_IEN_PROP_DTVIEN_MASK        0x01
   #define  Si21XXC_MASTER_IEN_PROP_DTVIEN_DEFAULT    0
    #define Si21XXC_MASTER_IEN_PROP_DTVIEN_OFF  0
    #define Si21XXC_MASTER_IEN_PROP_DTVIEN_ON   1

   /* MASTER_IEN property, ERRIEN field definition (NO TITLE)*/
   #define  Si21XXC_MASTER_IEN_PROP_ERRIEN_LSB         6
   #define  Si21XXC_MASTER_IEN_PROP_ERRIEN_MASK        0x01
   #define  Si21XXC_MASTER_IEN_PROP_ERRIEN_DEFAULT    0
    #define Si21XXC_MASTER_IEN_PROP_ERRIEN_OFF  0
    #define Si21XXC_MASTER_IEN_PROP_ERRIEN_ON   1

   /* MASTER_IEN property, TUNIEN field definition (NO TITLE)*/
   #define  Si21XXC_MASTER_IEN_PROP_TUNIEN_LSB         0
   #define  Si21XXC_MASTER_IEN_PROP_TUNIEN_MASK        0x01
   #define  Si21XXC_MASTER_IEN_PROP_TUNIEN_DEFAULT    0
    #define Si21XXC_MASTER_IEN_PROP_TUNIEN_OFF  0
    #define Si21XXC_MASTER_IEN_PROP_TUNIEN_ON   1

#endif /* Si21XXC_MASTER_IEN_PROP */

/* Si21XXC TUNER_BLOCKED_VCO property definition */
#define   Si21XXC_TUNER_BLOCKED_VCO_PROP 0x0504

#ifdef    Si21XXC_TUNER_BLOCKED_VCO_PROP
  #define Si21XXC_TUNER_BLOCKED_VCO_PROP_CODE 0x000504


    typedef struct { /* Si21XXC_TUNER_BLOCKED_VCO_PROP_struct */
               int    vco_code;
   } Si21XXC_TUNER_BLOCKED_VCO_PROP_struct;

   /* TUNER_BLOCKED_VCO property, VCO_CODE field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_BLOCKED_VCO_PROP_VCO_CODE_LSB         0
   #define  Si21XXC_TUNER_BLOCKED_VCO_PROP_VCO_CODE_MASK        0xffff
   #define  Si21XXC_TUNER_BLOCKED_VCO_PROP_VCO_CODE_DEFAULT    0x8000
    #define Si21XXC_TUNER_BLOCKED_VCO_PROP_VCO_CODE_VCO_CODE_MIN  -32768
    #define Si21XXC_TUNER_BLOCKED_VCO_PROP_VCO_CODE_VCO_CODE_MAX  32767

#endif /* Si21XXC_TUNER_BLOCKED_VCO_PROP */

/* Si21XXC TUNER_IEN property definition */
#define   Si21XXC_TUNER_IEN_PROP 0x0501

#ifdef    Si21XXC_TUNER_IEN_PROP
  #define Si21XXC_TUNER_IEN_PROP_CODE 0x000501


    typedef struct { /* Si21XXC_TUNER_IEN_PROP_struct */
      unsigned char   rssihien;
      unsigned char   rssilien;
      unsigned char   tcien;
   } Si21XXC_TUNER_IEN_PROP_struct;

   /* TUNER_IEN property, RSSIHIEN field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_IEN_PROP_RSSIHIEN_LSB         2
   #define  Si21XXC_TUNER_IEN_PROP_RSSIHIEN_MASK        0x01
   #define  Si21XXC_TUNER_IEN_PROP_RSSIHIEN_DEFAULT    0
    #define Si21XXC_TUNER_IEN_PROP_RSSIHIEN_DISABLE  0
    #define Si21XXC_TUNER_IEN_PROP_RSSIHIEN_ENABLE   1

   /* TUNER_IEN property, RSSILIEN field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_IEN_PROP_RSSILIEN_LSB         1
   #define  Si21XXC_TUNER_IEN_PROP_RSSILIEN_MASK        0x01
   #define  Si21XXC_TUNER_IEN_PROP_RSSILIEN_DEFAULT    0
    #define Si21XXC_TUNER_IEN_PROP_RSSILIEN_DISABLE  0
    #define Si21XXC_TUNER_IEN_PROP_RSSILIEN_ENABLE   1

   /* TUNER_IEN property, TCIEN field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_IEN_PROP_TCIEN_LSB         0
   #define  Si21XXC_TUNER_IEN_PROP_TCIEN_MASK        0x01
   #define  Si21XXC_TUNER_IEN_PROP_TCIEN_DEFAULT    1
    #define Si21XXC_TUNER_IEN_PROP_TCIEN_DISABLE  0
    #define Si21XXC_TUNER_IEN_PROP_TCIEN_ENABLE   1

#endif /* Si21XXC_TUNER_IEN_PROP */

/* Si21XXC TUNER_INT_SENSE property definition */
#define   Si21XXC_TUNER_INT_SENSE_PROP 0x0505

#ifdef    Si21XXC_TUNER_INT_SENSE_PROP
  #define Si21XXC_TUNER_INT_SENSE_PROP_CODE 0x000505


    typedef struct { /* Si21XXC_TUNER_INT_SENSE_PROP_struct */
      unsigned char   rssihnegen;
      unsigned char   rssihposen;
      unsigned char   rssilnegen;
      unsigned char   rssilposen;
      unsigned char   tcnegen;
      unsigned char   tcposen;
   } Si21XXC_TUNER_INT_SENSE_PROP_struct;

   /* TUNER_INT_SENSE property, RSSIHNEGEN field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSIHNEGEN_LSB         2
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSIHNEGEN_MASK        0x01
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSIHNEGEN_DEFAULT    0
    #define Si21XXC_TUNER_INT_SENSE_PROP_RSSIHNEGEN_DISABLE  0
    #define Si21XXC_TUNER_INT_SENSE_PROP_RSSIHNEGEN_ENABLE   1

   /* TUNER_INT_SENSE property, RSSIHPOSEN field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSIHPOSEN_LSB         10
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSIHPOSEN_MASK        0x01
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSIHPOSEN_DEFAULT    1
    #define Si21XXC_TUNER_INT_SENSE_PROP_RSSIHPOSEN_DISABLE  0
    #define Si21XXC_TUNER_INT_SENSE_PROP_RSSIHPOSEN_ENABLE   1

   /* TUNER_INT_SENSE property, RSSILNEGEN field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSILNEGEN_LSB         1
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSILNEGEN_MASK        0x01
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSILNEGEN_DEFAULT    0
    #define Si21XXC_TUNER_INT_SENSE_PROP_RSSILNEGEN_DISABLE  0
    #define Si21XXC_TUNER_INT_SENSE_PROP_RSSILNEGEN_ENABLE   1

   /* TUNER_INT_SENSE property, RSSILPOSEN field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSILPOSEN_LSB         9
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSILPOSEN_MASK        0x01
   #define  Si21XXC_TUNER_INT_SENSE_PROP_RSSILPOSEN_DEFAULT    1
    #define Si21XXC_TUNER_INT_SENSE_PROP_RSSILPOSEN_DISABLE  0
    #define Si21XXC_TUNER_INT_SENSE_PROP_RSSILPOSEN_ENABLE   1

   /* TUNER_INT_SENSE property, TCNEGEN field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_INT_SENSE_PROP_TCNEGEN_LSB         0
   #define  Si21XXC_TUNER_INT_SENSE_PROP_TCNEGEN_MASK        0x01
   #define  Si21XXC_TUNER_INT_SENSE_PROP_TCNEGEN_DEFAULT    0
    #define Si21XXC_TUNER_INT_SENSE_PROP_TCNEGEN_DISABLE  0
    #define Si21XXC_TUNER_INT_SENSE_PROP_TCNEGEN_ENABLE   1

   /* TUNER_INT_SENSE property, TCPOSEN field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_INT_SENSE_PROP_TCPOSEN_LSB         8
   #define  Si21XXC_TUNER_INT_SENSE_PROP_TCPOSEN_MASK        0x01
   #define  Si21XXC_TUNER_INT_SENSE_PROP_TCPOSEN_DEFAULT    1
    #define Si21XXC_TUNER_INT_SENSE_PROP_TCPOSEN_DISABLE  0
    #define Si21XXC_TUNER_INT_SENSE_PROP_TCPOSEN_ENABLE   1

#endif /* Si21XXC_TUNER_INT_SENSE_PROP */

/* Si21XXC TUNER_LO_INJECTION property definition */
#define   Si21XXC_TUNER_LO_INJECTION_PROP 0x0506

#ifdef    Si21XXC_TUNER_LO_INJECTION_PROP
  #define Si21XXC_TUNER_LO_INJECTION_PROP_CODE 0x000506


    typedef struct { /* Si21XXC_TUNER_LO_INJECTION_PROP_struct */
      unsigned char   band_1;
      unsigned char   band_2;
      unsigned char   band_3;
   } Si21XXC_TUNER_LO_INJECTION_PROP_struct;

   /* TUNER_LO_INJECTION property, BAND_1 field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_LO_INJECTION_PROP_BAND_1_LSB         0
   #define  Si21XXC_TUNER_LO_INJECTION_PROP_BAND_1_MASK        0x01
   #define  Si21XXC_TUNER_LO_INJECTION_PROP_BAND_1_DEFAULT    1
    #define Si21XXC_TUNER_LO_INJECTION_PROP_BAND_1_LOW_SIDE   0
    #define Si21XXC_TUNER_LO_INJECTION_PROP_BAND_1_HIGH_SIDE  1

   /* TUNER_LO_INJECTION property, BAND_2 field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_LO_INJECTION_PROP_BAND_2_LSB         1
   #define  Si21XXC_TUNER_LO_INJECTION_PROP_BAND_2_MASK        0x01
   #define  Si21XXC_TUNER_LO_INJECTION_PROP_BAND_2_DEFAULT    0
    #define Si21XXC_TUNER_LO_INJECTION_PROP_BAND_2_LOW_SIDE   0
    #define Si21XXC_TUNER_LO_INJECTION_PROP_BAND_2_HIGH_SIDE  1

   /* TUNER_LO_INJECTION property, BAND_3 field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_LO_INJECTION_PROP_BAND_3_LSB         2
   #define  Si21XXC_TUNER_LO_INJECTION_PROP_BAND_3_MASK        0x01
   #define  Si21XXC_TUNER_LO_INJECTION_PROP_BAND_3_DEFAULT    0
    #define Si21XXC_TUNER_LO_INJECTION_PROP_BAND_3_LOW_SIDE   0
    #define Si21XXC_TUNER_LO_INJECTION_PROP_BAND_3_HIGH_SIDE  1

#endif /* Si21XXC_TUNER_LO_INJECTION_PROP */

/* Si21XXC TUNER_RETURN_LOSS property definition */
#define   Si21XXC_TUNER_RETURN_LOSS_PROP 0x0507

#ifdef    Si21XXC_TUNER_RETURN_LOSS_PROP
  #define Si21XXC_TUNER_RETURN_LOSS_PROP_CODE 0x000507


    typedef struct { /* Si21XXC_TUNER_RETURN_LOSS_PROP_struct */
      unsigned char   config;
      unsigned char   mode;
   } Si21XXC_TUNER_RETURN_LOSS_PROP_struct;

   /* TUNER_RETURN_LOSS property, CONFIG field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_RETURN_LOSS_PROP_CONFIG_LSB         0
   #define  Si21XXC_TUNER_RETURN_LOSS_PROP_CONFIG_MASK        0xff
   #define  Si21XXC_TUNER_RETURN_LOSS_PROP_CONFIG_DEFAULT    127
    #define Si21XXC_TUNER_RETURN_LOSS_PROP_CONFIG_75   75
    #define Si21XXC_TUNER_RETURN_LOSS_PROP_CONFIG_83   83
    #define Si21XXC_TUNER_RETURN_LOSS_PROP_CONFIG_91   91
    #define Si21XXC_TUNER_RETURN_LOSS_PROP_CONFIG_103  103
    #define Si21XXC_TUNER_RETURN_LOSS_PROP_CONFIG_115  115
   #define  Si21XXC_TUNER_RETURN_LOSS_PROP_CONFIG_127        127

   /* TUNER_RETURN_LOSS property, MODE field definition (NO TITLE)*/
   #define  Si21XXC_TUNER_RETURN_LOSS_PROP_MODE_LSB         8
   #define  Si21XXC_TUNER_RETURN_LOSS_PROP_MODE_MASK        0xff
   #define  Si21XXC_TUNER_RETURN_LOSS_PROP_MODE_DEFAULT    0
    #define Si21XXC_TUNER_RETURN_LOSS_PROP_MODE_TERRESTRIAL  0
    #define Si21XXC_TUNER_RETURN_LOSS_PROP_MODE_CABLE        1

#endif /* Si21XXC_TUNER_RETURN_LOSS_PROP */
/* Si2190B TUNER_RETURN_LOSS_OPTIMIZE property definition */
#define   Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP 0x050b

#ifdef    Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP
  #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CODE 0x00050b


    typedef struct { /* Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_struct */
      unsigned char   config;
      unsigned char   disengagement_delay;
      unsigned char   engagement_delay;
      unsigned char   thld;
   } Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_struct;

   /* TUNER_RETURN_LOSS_OPTIMIZE property, CONFIG field definition (NO TITLE)*/
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_LSB         3
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_MASK        0x1f
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_DEFAULT    30
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_2        0
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_3        1
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_4        2
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_5        3
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_6        4
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_7        5
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_8        6
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_9        7
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_10       8
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_11       9
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_13       10
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_15       11
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_17       12
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_19       13
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_23       14
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_27       15
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_31       16
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_35       17
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_39       18
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_43       19
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_47       20
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_51       21
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_59       22
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_67       23
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_75       24
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_83       25
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_91       26
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_103      27
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_115      28
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_127      29
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_CONFIG_DISABLE  30

   /* TUNER_RETURN_LOSS_OPTIMIZE property, DISENGAGEMENT_DELAY field definition (NO TITLE)*/
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_DISENGAGEMENT_DELAY_LSB         12
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_DISENGAGEMENT_DELAY_MASK        0x0f
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_DISENGAGEMENT_DELAY_DEFAULT    10
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_DISENGAGEMENT_DELAY_DISENGAGEMENT_DELAY_MIN  0
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_DISENGAGEMENT_DELAY_DISENGAGEMENT_DELAY_MAX  15

   /* TUNER_RETURN_LOSS_OPTIMIZE property, ENGAGEMENT_DELAY field definition (NO TITLE)*/
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_ENGAGEMENT_DELAY_LSB         8
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_ENGAGEMENT_DELAY_MASK        0x0f
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_ENGAGEMENT_DELAY_DEFAULT    7
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_ENGAGEMENT_DELAY_ENGAGEMENT_DELAY_MIN  0
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_ENGAGEMENT_DELAY_ENGAGEMENT_DELAY_MAX  15

   /* TUNER_RETURN_LOSS_OPTIMIZE property, THLD field definition (NO TITLE)*/
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_THLD_LSB         0
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_THLD_MASK        0x07
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_THLD_DEFAULT    0
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_THLD_THLD_MIN  0
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_THLD_THLD_MAX  7

#endif /* Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP */

/* Si2190B TUNER_RETURN_LOSS_OPTIMIZE_2 property definition */
#define   Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP 0x050c

#ifdef    Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP
  #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_CODE 0x00050c


    typedef struct { /* Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_struct */
      unsigned char   engagement_delay;
      unsigned char   thld;
      unsigned char   window;
   } Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_struct;

   /* TUNER_RETURN_LOSS_OPTIMIZE_2 property, ENGAGEMENT_DELAY field definition (NO TITLE)*/
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_ENGAGEMENT_DELAY_LSB         8
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_ENGAGEMENT_DELAY_MASK        0x0f
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_ENGAGEMENT_DELAY_DEFAULT    15
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_ENGAGEMENT_DELAY_ENGAGEMENT_DELAY_MIN  0
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_ENGAGEMENT_DELAY_ENGAGEMENT_DELAY_MAX  15

   /* TUNER_RETURN_LOSS_OPTIMIZE_2 property, THLD field definition (NO TITLE)*/
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_THLD_LSB         0
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_THLD_MASK        0x1f
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_THLD_DEFAULT    31
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_THLD_THLD_MIN  0
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_THLD_THLD_MAX  31

   /* TUNER_RETURN_LOSS_OPTIMIZE_2 property, WINDOW field definition (NO TITLE)*/
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_WINDOW_LSB         5
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_WINDOW_MASK        0x07
   #define  Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_WINDOW_DEFAULT    0
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_WINDOW_WINDOW_MIN  0
    #define Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_WINDOW_WINDOW_MAX  7

#endif /* Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP */
/* Si2190B TUNER_TF1_BOUNDARY_OFFSET property definition */
#define   Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP 0x050f

#ifdef    Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP
  #define Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP_CODE 0x00050f


    typedef struct { /* Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP_struct */
               int    tf1_boundary_offset;
   } Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP_struct;

   /* TUNER_TF1_BOUNDARY_OFFSET property, TF1_BOUNDARY_OFFSET field definition (NO TITLE)*/
   #define  Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP_TF1_BOUNDARY_OFFSET_LSB         0
   #define  Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP_TF1_BOUNDARY_OFFSET_MASK        0xffff
   #define  Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP_TF1_BOUNDARY_OFFSET_DEFAULT    0
    #define Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP_TF1_BOUNDARY_OFFSET_TF1_OFFSET_MIN  -100
    #define Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP_TF1_BOUNDARY_OFFSET_TF1_OFFSET_MAX  100

#endif /* Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP */

/* Si2190B WIDE_BAND_ATT_THRS property definition */
#define   Si2190B_WIDE_BAND_ATT_THRS_PROP 0x0503

#ifdef    Si2190B_WIDE_BAND_ATT_THRS_PROP
  #define Si2190B_WIDE_BAND_ATT_THRS_PROP_CODE 0x000503


    typedef struct { /* Si2190B_WIDE_BAND_ATT_THRS_PROP_struct */
      unsigned char   wb_att_thrs;
   } Si2190B_WIDE_BAND_ATT_THRS_PROP_struct;

   /* WIDE_BAND_ATT_THRS property, WB_ATT_THRS field definition (NO TITLE)*/
   #define  Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_LSB         0
   #define  Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_MASK        0xff
   #define  Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_DEFAULT    0
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_AUTO     0
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_0DBM     12
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M1DBM    13
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M2DBM    14
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M3DBM    15
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M4DBM    16
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M5DBM    17
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M6DBM    18
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M7DBM    19
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M8DBM    20
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M9DBM    21
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M10DBM   22
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M11DBM   23
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_M12DBM   24
    #define Si2190B_WIDE_BAND_ATT_THRS_PROP_WB_ATT_THRS_DISABLE  255

#endif /* Si2190B_WIDE_BAND_ATT_THRS_PROP */

/* Si21XXC XOUT property definition */
#define   Si21XXC_XOUT_PROP 0x0404

#ifdef    Si21XXC_XOUT_PROP
  #define Si21XXC_XOUT_PROP_CODE 0x000404


    typedef struct { /* Si21XXC_XOUT_PROP_struct */
      unsigned char   amp;
   } Si21XXC_XOUT_PROP_struct;

   /* XOUT property, AMP field definition (NO TITLE)*/
   #define  Si21XXC_XOUT_PROP_AMP_LSB         0
   #define  Si21XXC_XOUT_PROP_AMP_MASK        0x01
   #define  Si21XXC_XOUT_PROP_AMP_DEFAULT    0
    #define Si21XXC_XOUT_PROP_AMP_HIGH  0
    #define Si21XXC_XOUT_PROP_AMP_LOW   1

#endif /* Si21XXC_XOUT_PROP */



  /* --------------------------------------------*/
  /* PROPERTIES STRUCT                           */
  /* This stores all property fields             */
  /* --------------------------------------------*/
  typedef struct {
    #ifdef    Si21XXC_ATV_AFC_RANGE_PROP
              Si21XXC_ATV_AFC_RANGE_PROP_struct                 atv_afc_range;
    #endif /* Si21XXC_ATV_AFC_RANGE_PROP */
    #ifdef    Si21XXC_ATV_AGC_SPEED_PROP
              Si21XXC_ATV_AGC_SPEED_PROP_struct                 atv_agc_speed;
    #endif /* Si21XXC_ATV_AGC_SPEED_PROP */
    #ifdef    Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP
              Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP_struct        atv_agc_speed_low_rssi;
    #endif /* Si21XXC_ATV_AGC_SPEED_LOW_RSSI_PROP */
    #ifdef    Si21XXC_ATV_ARTIFICIAL_SNOW_PROP
              Si21XXC_ATV_ARTIFICIAL_SNOW_PROP_struct           atv_artificial_snow;
    #endif /* Si21XXC_ATV_ARTIFICIAL_SNOW_PROP */
    #ifdef    Si21XXC_ATV_AUDIO_MODE_PROP
              Si21XXC_ATV_AUDIO_MODE_PROP_struct                atv_audio_mode;
    #endif /* Si21XXC_ATV_AUDIO_MODE_PROP */
    #ifdef    Si21XXC_ATV_CONFIG_IF_PORT_PROP
              Si21XXC_ATV_CONFIG_IF_PORT_PROP_struct            atv_config_if_port;
    #endif /* Si21XXC_ATV_CONFIG_IF_PORT_PROP */
      #ifdef    Si2190B_ATV_CVBS_ATTENUATION_PROP
              Si2190B_ATV_CVBS_ATTENUATION_PROP_struct          atv_cvbs_attenuation;
    #endif /* Si2190B_ATV_CVBS_ATTENUATION_PROP */
    #ifdef    Si21XXC_ATV_CVBS_OUT_PROP
              Si21XXC_ATV_CVBS_OUT_PROP_struct                  atv_cvbs_out;
    #endif /* Si21XXC_ATV_CVBS_OUT_PROP */
    #ifdef    Si21XXC_ATV_CVBS_OUT_FINE_PROP
              Si21XXC_ATV_CVBS_OUT_FINE_PROP_struct             atv_cvbs_out_fine;
    #endif /* Si21XXC_ATV_CVBS_OUT_FINE_PROP */
    #ifdef    Si21XXC_ATV_IEN_PROP
              Si21XXC_ATV_IEN_PROP_struct                       atv_ien;
    #endif /* Si21XXC_ATV_IEN_PROP */
    #ifdef    Si21XXC_ATV_INT_SENSE_PROP
              Si21XXC_ATV_INT_SENSE_PROP_struct                 atv_int_sense;
    #endif /* Si21XXC_ATV_INT_SENSE_PROP */
    #ifdef    Si21XXC_ATV_PGA_TARGET_PROP
              Si21XXC_ATV_PGA_TARGET_PROP_struct                atv_pga_target;
    #endif /* Si21XXC_ATV_PGA_TARGET_PROP */
    #ifdef    Si21XXC_ATV_RF_TOP_PROP
              Si21XXC_ATV_RF_TOP_PROP_struct                    atv_rf_top;
    #endif /* Si21XXC_ATV_RF_TOP_PROP */
    #ifdef    Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP
              Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP_struct        atv_rsq_rssi_threshold;
    #endif /* Si21XXC_ATV_RSQ_RSSI_THRESHOLD_PROP */
    #ifdef    Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP
              Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP_struct         atv_rsq_snr_threshold;
    #endif /* Si21XXC_ATV_RSQ_SNR_THRESHOLD_PROP */
    #ifdef    Si21XXC_ATV_SIF_OUT_PROP
              Si21XXC_ATV_SIF_OUT_PROP_struct                   atv_sif_out;
    #endif /* Si21XXC_ATV_SIF_OUT_PROP */
    #ifdef    Si21XXC_ATV_SOUND_AGC_LIMIT_PROP
              Si21XXC_ATV_SOUND_AGC_LIMIT_PROP_struct           atv_sound_agc_limit;
    #endif /* Si21XXC_ATV_SOUND_AGC_LIMIT_PROP */
    #ifdef    Si21XXC_ATV_SOUND_AGC_SPEED_PROP
              Si21XXC_ATV_SOUND_AGC_SPEED_PROP_struct           atv_sound_agc_speed;
    #endif /* Si21XXC_ATV_SOUND_AGC_SPEED_PROP */
    #ifdef    Si21XXC_ATV_VIDEO_EQUALIZER_PROP
              Si21XXC_ATV_VIDEO_EQUALIZER_PROP_struct           atv_video_equalizer;
    #endif /* Si21XXC_ATV_VIDEO_EQUALIZER_PROP */
    #ifdef    Si21XXC_ATV_VIDEO_MODE_PROP
              Si21XXC_ATV_VIDEO_MODE_PROP_struct                atv_video_mode;
    #endif /* Si21XXC_ATV_VIDEO_MODE_PROP */
    #ifdef    Si21XXC_ATV_VSNR_CAP_PROP
              Si21XXC_ATV_VSNR_CAP_PROP_struct                  atv_vsnr_cap;
    #endif /* Si21XXC_ATV_VSNR_CAP_PROP */
    #ifdef    Si21XXC_CRYSTAL_TRIM_PROP
              Si21XXC_CRYSTAL_TRIM_PROP_struct                  crystal_trim;
    #endif /* Si21XXC_CRYSTAL_TRIM_PROP */
    #ifdef    Si21XXC_DTV_AGC_AUTO_FREEZE_PROP
              Si21XXC_DTV_AGC_AUTO_FREEZE_PROP_struct           dtv_agc_auto_freeze;
    #endif /* Si21XXC_DTV_AGC_AUTO_FREEZE_PROP */
    #ifdef    Si21XXC_DTV_AGC_FREEZE_INPUT_PROP
              Si21XXC_DTV_AGC_FREEZE_INPUT_PROP_struct          dtv_agc_freeze_input;
    #endif /* Si21XXC_DTV_AGC_FREEZE_INPUT_PROP */
    #ifdef    Si21XXC_DTV_AGC_SPEED_PROP
              Si21XXC_DTV_AGC_SPEED_PROP_struct                 dtv_agc_speed;
    #endif /* Si21XXC_DTV_AGC_SPEED_PROP */
    #ifdef    Si21XXC_DTV_CONFIG_IF_PORT_PROP
              Si21XXC_DTV_CONFIG_IF_PORT_PROP_struct            dtv_config_if_port;
    #endif /* Si21XXC_DTV_CONFIG_IF_PORT_PROP */
    #ifdef    Si21XXC_DTV_EXT_AGC_PROP
              Si21XXC_DTV_EXT_AGC_PROP_struct                   dtv_ext_agc;
    #endif /* Si21XXC_DTV_EXT_AGC_PROP */
    #ifdef    Si21XXC_DTV_IEN_PROP
              Si21XXC_DTV_IEN_PROP_struct                       dtv_ien;
    #endif /* Si21XXC_DTV_IEN_PROP */
    #ifdef    Si21XXC_DTV_IF_AGC_SPEED_PROP
              Si21XXC_DTV_IF_AGC_SPEED_PROP_struct              dtv_if_agc_speed;
    #endif /* Si21XXC_DTV_IF_AGC_SPEED_PROP */
    #ifdef    Si21XXC_DTV_INITIAL_AGC_SPEED_PROP
              Si21XXC_DTV_INITIAL_AGC_SPEED_PROP_struct         dtv_initial_agc_speed;
    #endif /* Si21XXC_DTV_INITIAL_AGC_SPEED_PROP */
    #ifdef    Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP
              Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP_struct  dtv_initial_agc_speed_period;
    #endif /* Si21XXC_DTV_INITIAL_AGC_SPEED_PERIOD_PROP */
    #ifdef    Si21XXC_DTV_INTERNAL_ZIF_PROP
              Si21XXC_DTV_INTERNAL_ZIF_PROP_struct              dtv_internal_zif;
    #endif /* Si21XXC_DTV_INTERNAL_ZIF_PROP */
    #ifdef    Si21XXC_DTV_INT_SENSE_PROP
              Si21XXC_DTV_INT_SENSE_PROP_struct                 dtv_int_sense;
    #endif /* Si21XXC_DTV_INT_SENSE_PROP */
    #ifdef    Si21XXC_DTV_LIF_FREQ_PROP
              Si21XXC_DTV_LIF_FREQ_PROP_struct                  dtv_lif_freq;
    #endif /* Si21XXC_DTV_LIF_FREQ_PROP */
    #ifdef    Si21XXC_DTV_LIF_OUT_PROP
              Si21XXC_DTV_LIF_OUT_PROP_struct                   dtv_lif_out;
    #endif /* Si21XXC_DTV_LIF_OUT_PROP */
    #ifdef    Si21XXC_DTV_MODE_PROP
              Si21XXC_DTV_MODE_PROP_struct                      dtv_mode;
    #endif /* Si21XXC_DTV_MODE_PROP */
    #ifdef    Si21XXC_DTV_RF_AGC_SPEED_PROP
              Si21XXC_DTV_RF_AGC_SPEED_PROP_struct              dtv_rf_agc_speed;
    #endif /* Si21XXC_DTV_RF_AGC_SPEED_PROP */
    #ifdef    Si21XXC_DTV_RF_TOP_PROP
              Si21XXC_DTV_RF_TOP_PROP_struct                    dtv_rf_top;
    #endif /* Si21XXC_DTV_RF_TOP_PROP */
    #ifdef    Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP
              Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP_struct        dtv_rsq_rssi_threshold;
    #endif /* Si21XXC_DTV_RSQ_RSSI_THRESHOLD_PROP */
    #ifdef    Si21XXC_DTV_WB_AGC_SPEED_PROP
              Si21XXC_DTV_WB_AGC_SPEED_PROP_struct              dtv_wb_agc_speed;
    #endif /* Si21XXC_DTV_WB_AGC_SPEED_PROP */
    #ifdef    Si21XXC_MASTER_IEN_PROP
              Si21XXC_MASTER_IEN_PROP_struct                    master_ien;
    #endif /* Si21XXC_MASTER_IEN_PROP */
    #ifdef    Si21XXC_TUNER_BLOCKED_VCO_PROP
              Si21XXC_TUNER_BLOCKED_VCO_PROP_struct             tuner_blocked_vco;
    #endif /* Si21XXC_TUNER_BLOCKED_VCO_PROP */
    #ifdef    Si21XXC_TUNER_IEN_PROP
              Si21XXC_TUNER_IEN_PROP_struct                     tuner_ien;
    #endif /* Si21XXC_TUNER_IEN_PROP */
    #ifdef    Si21XXC_TUNER_INT_SENSE_PROP
              Si21XXC_TUNER_INT_SENSE_PROP_struct               tuner_int_sense;
    #endif /* Si21XXC_TUNER_INT_SENSE_PROP */
    #ifdef    Si21XXC_TUNER_LO_INJECTION_PROP
              Si21XXC_TUNER_LO_INJECTION_PROP_struct            tuner_lo_injection;
    #endif /* Si21XXC_TUNER_LO_INJECTION_PROP */
    #ifdef    Si21XXC_TUNER_RETURN_LOSS_PROP
              Si21XXC_TUNER_RETURN_LOSS_PROP_struct             tuner_return_loss;
    #endif /* Si21XXC_TUNER_RETURN_LOSS_PROP */
    #ifdef    Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP
              Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP_struct    tuner_return_loss_optimize;
    #endif /* Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_PROP */
    #ifdef    Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP
              Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP_struct  tuner_return_loss_optimize_2;
    #endif /* Si2190B_TUNER_RETURN_LOSS_OPTIMIZE_2_PROP */
    #ifdef    Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP
              Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP_struct     tuner_tf1_boundary_offset;
    #endif /* Si2190B_TUNER_TF1_BOUNDARY_OFFSET_PROP */
    #ifdef    Si2190B_WIDE_BAND_ATT_THRS_PROP
              Si2190B_WIDE_BAND_ATT_THRS_PROP_struct            wide_band_att_thrs;
    #endif /* Si2190B_WIDE_BAND_ATT_THRS_PROP */
    #ifdef    Si21XXC_XOUT_PROP
              Si21XXC_XOUT_PROP_struct                          xout;
    #endif /* Si21XXC_XOUT_PROP */
  } Si21XXC_PropObj;

/* #define   Si21XXC_GET_PROPERTY_STRING */
#ifdef __cplusplus
}
#endif
#endif /* _Si21XXC_PROPERTIES_H_ */





