#ifndef __SECU_MBX_REG_TBL__
#define __SECU_MBX_REG_TBL__

#define MBX_START_ADDR  (0x103300)
#define MBX_SECU_HDCP_ADDR     (MBX_START_ADDR + 0xC0)
#define MBX_HDCP_MSGID    (MBX_SECU_HDCP_ADDR + 0)
#define MBX_HDCP_STATUS   (MBX_SECU_HDCP_ADDR + 1)
#define MBX_HDCP_ERRCODE  (MBX_SECU_HDCP_ADDR + 2)
#define MBX_HDCP_ARGADDR  (MBX_SECU_HDCP_ADDR + 3) //0x3~0x6
#define MBX_HDCP_ARGSIZE  (MBX_SECU_HDCP_ADDR + 7) //0x7~0xA



#endif

