#ifndef __SECURE_R2_APP__
#define __SECURE_R2_APP__

#include "MsTypes.h"
#include "datatype.h"

typedef enum E_SecR2_ROM_Mode
{
	E_SECR2_ROM_RUN_DRAM_SUCCESS = 0,
	E_SECR2_ROM_Unknown_ERROR = 1,
	E_SECR2_ROM_INIT_ERROR = 2,
	E_SECR2_ROM_JUMP_START_ERROR = 3,
	E_SECR2_ROM_MBX_HEAD_ERROR = 4,
	E_SECR2_ROM_DRAMOBF_ERROR = 5,
	E_SECR2_ROM_RC_CLOCK_ENABLE_ERROR = 6,
    E_SECR2_ROM_RC_LOCK_ERROR = 7,
    E_SECR2_ROM_DRAMSIZE_LOCK_ERROR = 8,
    E_SECR2_ROM_DRAMSIZE_COMP_ERROR = 9,
    E_SECR2_ROM_STAR_ADDR_ERROR = 10,
    E_SECR2_ROM_END_ADDR_ERROR = 11,
	E_SECR2_ROM_RSA_BUSY = 12,
    E_SECR2_ROM_RSA_ERROR = 13,
    E_SECR2_ROM_SHA_ERROR = 14, 
    E_SECR2_ROM_SHA_RSA_COMP_ERROR = 15,
    E_SECR2_ROM_NOT_READY = 16
} E_SecR2_ROM_Mode;

E_SecR2_ROM_Mode SecureR2_Query_ROM_State(void);

#endif


