////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2017 09:17:51]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// FMRADIO_ROOT_TRANSPARENT_BG styles..


/////////////////////////////////////////////////////
// FMRADIO_BG_PAGE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Bg_Page_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_0 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE styles..


/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE_BG_L styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_List_Page_Bg_L_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_4 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE_BG_C styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_List_Page_Bg_C_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_89 },
    { CP_NOON, 0 },
};
#define _Zui_Fmradio_List_Page_Bg_C_Focus_DrawStyle _Zui_Fmradio_List_Page_Bg_C_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE_BG_R styles..

#define _Zui_Fmradio_List_Page_Bg_R_Normal_DrawStyle _Zui_Fmradio_List_Page_Bg_L_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_List_Item1_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_126 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM1_CHANNEL_NUMBER styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1444 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1445 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM1_FREQUENCY styles..

#define _Zui_Fmradio_List_Item1_Frequency_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item1_Frequency_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM1_EDIT_NAME styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1446 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1447 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM2 styles..

#define _Zui_Fmradio_List_Item2_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM2_CHANNEL_NUMBER styles..

#define _Zui_Fmradio_List_Item2_Channel_Number_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item2_Channel_Number_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM2_FREQUENCY styles..

#define _Zui_Fmradio_List_Item2_Frequency_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item2_Frequency_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM2_EDIT_NAME styles..

#define _Zui_Fmradio_List_Item2_Edit_Name_Normal_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle
#define _Zui_Fmradio_List_Item2_Edit_Name_Focus_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM3 styles..

#define _Zui_Fmradio_List_Item3_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM3_CHANNEL_NUMBER styles..

#define _Zui_Fmradio_List_Item3_Channel_Number_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item3_Channel_Number_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM3_FREQUENCY styles..

#define _Zui_Fmradio_List_Item3_Frequency_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item3_Frequency_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM3_EDIT_NAME styles..

#define _Zui_Fmradio_List_Item3_Edit_Name_Normal_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle
#define _Zui_Fmradio_List_Item3_Edit_Name_Focus_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM4 styles..

#define _Zui_Fmradio_List_Item4_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM4_CHANNEL_NUMBER styles..

#define _Zui_Fmradio_List_Item4_Channel_Number_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item4_Channel_Number_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM4_FREQUENCY styles..

#define _Zui_Fmradio_List_Item4_Frequency_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item4_Frequency_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM4_EDIT_NAME styles..

#define _Zui_Fmradio_List_Item4_Edit_Name_Normal_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle
#define _Zui_Fmradio_List_Item4_Edit_Name_Focus_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM5 styles..

#define _Zui_Fmradio_List_Item5_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM5_CHANNEL_NUMBER styles..

#define _Zui_Fmradio_List_Item5_Channel_Number_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item5_Channel_Number_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM5_FREQUENCY styles..

#define _Zui_Fmradio_List_Item5_Frequency_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item5_Frequency_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM5_EDIT_NAME styles..

#define _Zui_Fmradio_List_Item5_Edit_Name_Normal_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle
#define _Zui_Fmradio_List_Item5_Edit_Name_Focus_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM6 styles..

#define _Zui_Fmradio_List_Item6_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM6_CHANNEL_NUMBER styles..

#define _Zui_Fmradio_List_Item6_Channel_Number_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item6_Channel_Number_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM6_FREQUENCY styles..

#define _Zui_Fmradio_List_Item6_Frequency_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item6_Frequency_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM6_EDIT_NAME styles..

#define _Zui_Fmradio_List_Item6_Edit_Name_Normal_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle
#define _Zui_Fmradio_List_Item6_Edit_Name_Focus_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM7 styles..

#define _Zui_Fmradio_List_Item7_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM7_CHANNEL_NUMBER styles..

#define _Zui_Fmradio_List_Item7_Channel_Number_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item7_Channel_Number_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM7_FREQUENCY styles..

#define _Zui_Fmradio_List_Item7_Frequency_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item7_Frequency_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM7_EDIT_NAME styles..

#define _Zui_Fmradio_List_Item7_Edit_Name_Normal_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle
#define _Zui_Fmradio_List_Item7_Edit_Name_Focus_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM8 styles..

#define _Zui_Fmradio_List_Item8_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM8_CHANNEL_NUMBER styles..

#define _Zui_Fmradio_List_Item8_Channel_Number_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item8_Channel_Number_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM8_FREQUENCY styles..

#define _Zui_Fmradio_List_Item8_Frequency_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item8_Frequency_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM8_EDIT_NAME styles..

#define _Zui_Fmradio_List_Item8_Edit_Name_Normal_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle
#define _Zui_Fmradio_List_Item8_Edit_Name_Focus_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM9 styles..

#define _Zui_Fmradio_List_Item9_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM9_CHANNEL_NUMBER styles..

#define _Zui_Fmradio_List_Item9_Channel_Number_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item9_Channel_Number_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM9_FREQUENCY styles..

#define _Zui_Fmradio_List_Item9_Frequency_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item9_Frequency_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM9_EDIT_NAME styles..

#define _Zui_Fmradio_List_Item9_Edit_Name_Normal_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle
#define _Zui_Fmradio_List_Item9_Edit_Name_Focus_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM10 styles..

#define _Zui_Fmradio_List_Item10_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM10_CHANNEL_NUMBER styles..

#define _Zui_Fmradio_List_Item10_Channel_Number_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item10_Channel_Number_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM10_FREQUENCY styles..

#define _Zui_Fmradio_List_Item10_Frequency_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Item10_Frequency_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_ITEM10_EDIT_NAME styles..

#define _Zui_Fmradio_List_Item10_Edit_Name_Normal_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle
#define _Zui_Fmradio_List_Item10_Edit_Name_Focus_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_List_Page_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1448 },
    { CP_NOON, 0 },
};
#define _Zui_Fmradio_List_Page_Title_Focus_DrawStyle _Zui_Fmradio_List_Page_Title_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE_KEY_INFO styles..

#define _Zui_Fmradio_List_Page_Key_Info_Normal_DrawStyle _Zui_Fmradio_List_Page_Bg_L_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE_KEY_INFO_REDKEY styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_List_Page_Key_Info_Redkey_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_186 },
    { CP_NOON, 0 },
};
#define _Zui_Fmradio_List_Page_Key_Info_Redkey_Focus_DrawStyle _Zui_Fmradio_List_Page_Key_Info_Redkey_Normal_DrawStyle
#define _Zui_Fmradio_List_Page_Key_Info_Redkey_Disabled_DrawStyle _Zui_Fmradio_List_Page_Key_Info_Redkey_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE_KEY_INFO_REDKEY_TEXT styles..

#define _Zui_Fmradio_List_Page_Key_Info_Redkey_Text_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Page_Key_Info_Redkey_Text_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE_KEY_INFO_GREENKEY styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_List_Page_Key_Info_Greenkey_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_187 },
    { CP_NOON, 0 },
};
#define _Zui_Fmradio_List_Page_Key_Info_Greenkey_Focus_DrawStyle _Zui_Fmradio_List_Page_Key_Info_Greenkey_Normal_DrawStyle
#define _Zui_Fmradio_List_Page_Key_Info_Greenkey_Disabled_DrawStyle _Zui_Fmradio_List_Page_Key_Info_Greenkey_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE_KEY_INFO_GREENKEY_TEXT styles..

#define _Zui_Fmradio_List_Page_Key_Info_Greenkey_Text_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Page_Key_Info_Greenkey_Text_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE_KEY_INFO_SELECTKEY styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_List_Page_Key_Info_Selectkey_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_36 },
    { CP_NOON, 0 },
};
#define _Zui_Fmradio_List_Page_Key_Info_Selectkey_Focus_DrawStyle _Zui_Fmradio_List_Page_Key_Info_Selectkey_Normal_DrawStyle
#define _Zui_Fmradio_List_Page_Key_Info_Selectkey_Disabled_DrawStyle _Zui_Fmradio_List_Page_Key_Info_Selectkey_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_LIST_PAGE_KEY_INFO_SELECTKEY_TEXT styles..

#define _Zui_Fmradio_List_Page_Key_Info_Selectkey_Text_Normal_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_List_Page_Key_Info_Selectkey_Text_Focus_DrawStyle _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_PAGE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Page_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_35 },
    { CP_NOON, 0 },
};
#define _Zui_Fmradio_Infomation_Page_Focus_DrawStyle _Zui_Fmradio_Infomation_Page_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_CHANNEL_NUMBER styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Channel_Number_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_265 },
    { CP_NOON, 0 },
};
#define _Zui_Fmradio_Infomation_Channel_Number_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_CHANNEL_NUMBER_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Channel_Number_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1449 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Channel_Number_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1450 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_CHANNEL_NUMBER_VALUE styles..

#define _Zui_Fmradio_Infomation_Channel_Number_Value_Normal_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle
#define _Zui_Fmradio_Infomation_Channel_Number_Value_Focus_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_FREQUENCY styles..

#define _Zui_Fmradio_Infomation_Frequency_Normal_DrawStyle _Zui_Fmradio_Infomation_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_Infomation_Frequency_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_FREQUENCY_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Frequency_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1451 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Frequency_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1452 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_FREQUENCY_VALUE styles..

#define _Zui_Fmradio_Infomation_Frequency_Value_Normal_DrawStyle _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle
static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Frequency_Value_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_126 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1447 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_EDIT_NAME styles..

#define _Zui_Fmradio_Infomation_Edit_Name_Normal_DrawStyle _Zui_Fmradio_Infomation_Channel_Number_Normal_DrawStyle
#define _Zui_Fmradio_Infomation_Edit_Name_Focus_DrawStyle _Zui_Fmradio_List_Item1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_EDIT_NAME_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Edit_Name_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1453 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Edit_Name_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1454 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_EDIT_NAME_VALUE styles..


/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_EDIT_NAME_VALUE1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Edit_Name_Value1_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1455 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Edit_Name_Value1_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_126 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1456 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_EDIT_NAME_VALUE2 styles..

#define _Zui_Fmradio_Infomation_Edit_Name_Value2_Normal_DrawStyle _Zui_Fmradio_Infomation_Edit_Name_Value1_Normal_DrawStyle
#define _Zui_Fmradio_Infomation_Edit_Name_Value2_Focus_DrawStyle _Zui_Fmradio_Infomation_Edit_Name_Value1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_EDIT_NAME_VALUE3 styles..

#define _Zui_Fmradio_Infomation_Edit_Name_Value3_Normal_DrawStyle _Zui_Fmradio_Infomation_Edit_Name_Value1_Normal_DrawStyle
#define _Zui_Fmradio_Infomation_Edit_Name_Value3_Focus_DrawStyle _Zui_Fmradio_Infomation_Edit_Name_Value1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_EDIT_NAME_VALUE4 styles..

#define _Zui_Fmradio_Infomation_Edit_Name_Value4_Normal_DrawStyle _Zui_Fmradio_Infomation_Edit_Name_Value1_Normal_DrawStyle
#define _Zui_Fmradio_Infomation_Edit_Name_Value4_Focus_DrawStyle _Zui_Fmradio_Infomation_Edit_Name_Value1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_EDIT_NAME_VALUE5 styles..

#define _Zui_Fmradio_Infomation_Edit_Name_Value5_Normal_DrawStyle _Zui_Fmradio_Infomation_Edit_Name_Value1_Normal_DrawStyle
#define _Zui_Fmradio_Infomation_Edit_Name_Value5_Focus_DrawStyle _Zui_Fmradio_Infomation_Edit_Name_Value1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_EDIT_NAME_VALUE6 styles..

#define _Zui_Fmradio_Infomation_Edit_Name_Value6_Normal_DrawStyle _Zui_Fmradio_Infomation_Edit_Name_Value1_Normal_DrawStyle
#define _Zui_Fmradio_Infomation_Edit_Name_Value6_Focus_DrawStyle _Zui_Fmradio_Infomation_Edit_Name_Value1_Focus_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_INFOMATION_PAGE_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Infomation_Page_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1457 },
    { CP_NOON, 0 },
};
#define _Zui_Fmradio_Infomation_Page_Title_Focus_DrawStyle _Zui_Fmradio_Infomation_Page_Title_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_AUTOTUNE_INFO_PAGE styles..

#define _Zui_Fmradio_Autotune_Info_Page_Normal_DrawStyle _Zui_Fmradio_Infomation_Page_Normal_DrawStyle
#define _Zui_Fmradio_Autotune_Info_Page_Focus_DrawStyle _Zui_Fmradio_Infomation_Page_Normal_DrawStyle
#define _Zui_Fmradio_Autotune_Info_Page_Disabled_DrawStyle _Zui_Fmradio_Infomation_Page_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_AUTOTUNE_INFO_PROGRESS_BAR styles..

#define _Zui_Fmradio_Autotune_Info_Progress_Bar_Normal_DrawStyle _Zui_Fmradio_List_Page_Bg_L_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_AUTOTUNE_INFO_PERCENTAGE_VALUE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Autotune_Info_Percentage_Value_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_805 },
    { CP_NOON, 0 },
};
#define _Zui_Fmradio_Autotune_Info_Percentage_Value_Focus_DrawStyle _Zui_Fmradio_Autotune_Info_Percentage_Value_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_AUTOTUNE_INFO_PERCENTAGE_TEXT styles..

#define _Zui_Fmradio_Autotune_Info_Percentage_Text_Normal_DrawStyle _Zui_Fmradio_Autotune_Info_Percentage_Value_Normal_DrawStyle
#define _Zui_Fmradio_Autotune_Info_Percentage_Text_Focus_DrawStyle _Zui_Fmradio_Autotune_Info_Percentage_Value_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_AUTOTUNE_INFO_FREQUENCY_VALUE styles..

#define _Zui_Fmradio_Autotune_Info_Frequency_Value_Normal_DrawStyle _Zui_Fmradio_Autotune_Info_Percentage_Value_Normal_DrawStyle
#define _Zui_Fmradio_Autotune_Info_Frequency_Value_Focus_DrawStyle _Zui_Fmradio_Autotune_Info_Percentage_Value_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_AUTOTUNE_INFO_FREQUENCY_TEXT styles..

#define _Zui_Fmradio_Autotune_Info_Frequency_Text_Normal_DrawStyle _Zui_Fmradio_Autotune_Info_Percentage_Value_Normal_DrawStyle
#define _Zui_Fmradio_Autotune_Info_Frequency_Text_Focus_DrawStyle _Zui_Fmradio_Autotune_Info_Percentage_Value_Normal_DrawStyle

/////////////////////////////////////////////////////
// FMRADIO_TENKEY_CH_NUMBER_PAGE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Fmradio_Tenkey_Ch_Number_Page_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_12 },
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1048 },
    { CP_NOON, 0 },
};
#define _Zui_Fmradio_Tenkey_Ch_Number_Page_Focus_DrawStyle _Zui_Fmradio_Tenkey_Ch_Number_Page_Normal_DrawStyle

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Fmradio[] =
{
    // HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // HWND_FMRADIO_ROOT_TRANSPARENT_BG
    { NULL, NULL, NULL     },

    // HWND_FMRADIO_BG_PAGE
    { _Zui_Fmradio_Bg_Page_Normal_DrawStyle, NULL, NULL     },

    // HWND_FMRADIO_LIST_PAGE
    { NULL, NULL, NULL     },

    // HWND_FMRADIO_LIST_PAGE_BG_L
    { _Zui_Fmradio_List_Page_Bg_L_Normal_DrawStyle, NULL, NULL     },

    // HWND_FMRADIO_LIST_PAGE_BG_C
    { _Zui_Fmradio_List_Page_Bg_C_Normal_DrawStyle, _Zui_Fmradio_List_Page_Bg_C_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_PAGE_BG_R
    { _Zui_Fmradio_List_Page_Bg_R_Normal_DrawStyle, NULL, NULL     },

    // HWND_FMRADIO_LIST_ITEM1
    { NULL, _Zui_Fmradio_List_Item1_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM1_CHANNEL_NUMBER
    { _Zui_Fmradio_List_Item1_Channel_Number_Normal_DrawStyle, _Zui_Fmradio_List_Item1_Channel_Number_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM1_FREQUENCY
    { _Zui_Fmradio_List_Item1_Frequency_Normal_DrawStyle, _Zui_Fmradio_List_Item1_Frequency_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM1_EDIT_NAME
    { _Zui_Fmradio_List_Item1_Edit_Name_Normal_DrawStyle, _Zui_Fmradio_List_Item1_Edit_Name_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM2
    { NULL, _Zui_Fmradio_List_Item2_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM2_CHANNEL_NUMBER
    { _Zui_Fmradio_List_Item2_Channel_Number_Normal_DrawStyle, _Zui_Fmradio_List_Item2_Channel_Number_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM2_FREQUENCY
    { _Zui_Fmradio_List_Item2_Frequency_Normal_DrawStyle, _Zui_Fmradio_List_Item2_Frequency_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM2_EDIT_NAME
    { _Zui_Fmradio_List_Item2_Edit_Name_Normal_DrawStyle, _Zui_Fmradio_List_Item2_Edit_Name_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM3
    { NULL, _Zui_Fmradio_List_Item3_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM3_CHANNEL_NUMBER
    { _Zui_Fmradio_List_Item3_Channel_Number_Normal_DrawStyle, _Zui_Fmradio_List_Item3_Channel_Number_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM3_FREQUENCY
    { _Zui_Fmradio_List_Item3_Frequency_Normal_DrawStyle, _Zui_Fmradio_List_Item3_Frequency_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM3_EDIT_NAME
    { _Zui_Fmradio_List_Item3_Edit_Name_Normal_DrawStyle, _Zui_Fmradio_List_Item3_Edit_Name_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM4
    { NULL, _Zui_Fmradio_List_Item4_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM4_CHANNEL_NUMBER
    { _Zui_Fmradio_List_Item4_Channel_Number_Normal_DrawStyle, _Zui_Fmradio_List_Item4_Channel_Number_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM4_FREQUENCY
    { _Zui_Fmradio_List_Item4_Frequency_Normal_DrawStyle, _Zui_Fmradio_List_Item4_Frequency_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM4_EDIT_NAME
    { _Zui_Fmradio_List_Item4_Edit_Name_Normal_DrawStyle, _Zui_Fmradio_List_Item4_Edit_Name_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM5
    { NULL, _Zui_Fmradio_List_Item5_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM5_CHANNEL_NUMBER
    { _Zui_Fmradio_List_Item5_Channel_Number_Normal_DrawStyle, _Zui_Fmradio_List_Item5_Channel_Number_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM5_FREQUENCY
    { _Zui_Fmradio_List_Item5_Frequency_Normal_DrawStyle, _Zui_Fmradio_List_Item5_Frequency_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM5_EDIT_NAME
    { _Zui_Fmradio_List_Item5_Edit_Name_Normal_DrawStyle, _Zui_Fmradio_List_Item5_Edit_Name_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM6
    { NULL, _Zui_Fmradio_List_Item6_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM6_CHANNEL_NUMBER
    { _Zui_Fmradio_List_Item6_Channel_Number_Normal_DrawStyle, _Zui_Fmradio_List_Item6_Channel_Number_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM6_FREQUENCY
    { _Zui_Fmradio_List_Item6_Frequency_Normal_DrawStyle, _Zui_Fmradio_List_Item6_Frequency_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM6_EDIT_NAME
    { _Zui_Fmradio_List_Item6_Edit_Name_Normal_DrawStyle, _Zui_Fmradio_List_Item6_Edit_Name_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM7
    { NULL, _Zui_Fmradio_List_Item7_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM7_CHANNEL_NUMBER
    { _Zui_Fmradio_List_Item7_Channel_Number_Normal_DrawStyle, _Zui_Fmradio_List_Item7_Channel_Number_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM7_FREQUENCY
    { _Zui_Fmradio_List_Item7_Frequency_Normal_DrawStyle, _Zui_Fmradio_List_Item7_Frequency_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM7_EDIT_NAME
    { _Zui_Fmradio_List_Item7_Edit_Name_Normal_DrawStyle, _Zui_Fmradio_List_Item7_Edit_Name_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM8
    { NULL, _Zui_Fmradio_List_Item8_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM8_CHANNEL_NUMBER
    { _Zui_Fmradio_List_Item8_Channel_Number_Normal_DrawStyle, _Zui_Fmradio_List_Item8_Channel_Number_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM8_FREQUENCY
    { _Zui_Fmradio_List_Item8_Frequency_Normal_DrawStyle, _Zui_Fmradio_List_Item8_Frequency_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM8_EDIT_NAME
    { _Zui_Fmradio_List_Item8_Edit_Name_Normal_DrawStyle, _Zui_Fmradio_List_Item8_Edit_Name_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM9
    { NULL, _Zui_Fmradio_List_Item9_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM9_CHANNEL_NUMBER
    { _Zui_Fmradio_List_Item9_Channel_Number_Normal_DrawStyle, _Zui_Fmradio_List_Item9_Channel_Number_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM9_FREQUENCY
    { _Zui_Fmradio_List_Item9_Frequency_Normal_DrawStyle, _Zui_Fmradio_List_Item9_Frequency_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM9_EDIT_NAME
    { _Zui_Fmradio_List_Item9_Edit_Name_Normal_DrawStyle, _Zui_Fmradio_List_Item9_Edit_Name_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM10
    { NULL, _Zui_Fmradio_List_Item10_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM10_CHANNEL_NUMBER
    { _Zui_Fmradio_List_Item10_Channel_Number_Normal_DrawStyle, _Zui_Fmradio_List_Item10_Channel_Number_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM10_FREQUENCY
    { _Zui_Fmradio_List_Item10_Frequency_Normal_DrawStyle, _Zui_Fmradio_List_Item10_Frequency_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_ITEM10_EDIT_NAME
    { _Zui_Fmradio_List_Item10_Edit_Name_Normal_DrawStyle, _Zui_Fmradio_List_Item10_Edit_Name_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_PAGE_TITLE
    { _Zui_Fmradio_List_Page_Title_Normal_DrawStyle, _Zui_Fmradio_List_Page_Title_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_PAGE_KEY_INFO
    { _Zui_Fmradio_List_Page_Key_Info_Normal_DrawStyle, NULL, NULL     },

    // HWND_FMRADIO_LIST_PAGE_KEY_INFO_REDKEY
    { _Zui_Fmradio_List_Page_Key_Info_Redkey_Normal_DrawStyle, _Zui_Fmradio_List_Page_Key_Info_Redkey_Focus_DrawStyle, _Zui_Fmradio_List_Page_Key_Info_Redkey_Disabled_DrawStyle     },

    // HWND_FMRADIO_LIST_PAGE_KEY_INFO_REDKEY_TEXT
    { _Zui_Fmradio_List_Page_Key_Info_Redkey_Text_Normal_DrawStyle, _Zui_Fmradio_List_Page_Key_Info_Redkey_Text_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_PAGE_KEY_INFO_GREENKEY
    { _Zui_Fmradio_List_Page_Key_Info_Greenkey_Normal_DrawStyle, _Zui_Fmradio_List_Page_Key_Info_Greenkey_Focus_DrawStyle, _Zui_Fmradio_List_Page_Key_Info_Greenkey_Disabled_DrawStyle     },

    // HWND_FMRADIO_LIST_PAGE_KEY_INFO_GREENKEY_TEXT
    { _Zui_Fmradio_List_Page_Key_Info_Greenkey_Text_Normal_DrawStyle, _Zui_Fmradio_List_Page_Key_Info_Greenkey_Text_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_LIST_PAGE_KEY_INFO_SELECTKEY
    { _Zui_Fmradio_List_Page_Key_Info_Selectkey_Normal_DrawStyle, _Zui_Fmradio_List_Page_Key_Info_Selectkey_Focus_DrawStyle, _Zui_Fmradio_List_Page_Key_Info_Selectkey_Disabled_DrawStyle     },

    // HWND_FMRADIO_LIST_PAGE_KEY_INFO_SELECTKEY_TEXT
    { _Zui_Fmradio_List_Page_Key_Info_Selectkey_Text_Normal_DrawStyle, _Zui_Fmradio_List_Page_Key_Info_Selectkey_Text_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_PAGE
    { _Zui_Fmradio_Infomation_Page_Normal_DrawStyle, _Zui_Fmradio_Infomation_Page_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_CHANNEL_NUMBER
    { _Zui_Fmradio_Infomation_Channel_Number_Normal_DrawStyle, _Zui_Fmradio_Infomation_Channel_Number_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_CHANNEL_NUMBER_TEXT
    { _Zui_Fmradio_Infomation_Channel_Number_Text_Normal_DrawStyle, _Zui_Fmradio_Infomation_Channel_Number_Text_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_CHANNEL_NUMBER_VALUE
    { _Zui_Fmradio_Infomation_Channel_Number_Value_Normal_DrawStyle, _Zui_Fmradio_Infomation_Channel_Number_Value_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_FREQUENCY
    { _Zui_Fmradio_Infomation_Frequency_Normal_DrawStyle, _Zui_Fmradio_Infomation_Frequency_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_FREQUENCY_TEXT
    { _Zui_Fmradio_Infomation_Frequency_Text_Normal_DrawStyle, _Zui_Fmradio_Infomation_Frequency_Text_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_FREQUENCY_VALUE
    { _Zui_Fmradio_Infomation_Frequency_Value_Normal_DrawStyle, _Zui_Fmradio_Infomation_Frequency_Value_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_EDIT_NAME
    { _Zui_Fmradio_Infomation_Edit_Name_Normal_DrawStyle, _Zui_Fmradio_Infomation_Edit_Name_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_EDIT_NAME_TEXT
    { _Zui_Fmradio_Infomation_Edit_Name_Text_Normal_DrawStyle, _Zui_Fmradio_Infomation_Edit_Name_Text_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_EDIT_NAME_VALUE
    { NULL, NULL, NULL     },

    // HWND_FMRADIO_INFOMATION_EDIT_NAME_VALUE1
    { _Zui_Fmradio_Infomation_Edit_Name_Value1_Normal_DrawStyle, _Zui_Fmradio_Infomation_Edit_Name_Value1_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_EDIT_NAME_VALUE2
    { _Zui_Fmradio_Infomation_Edit_Name_Value2_Normal_DrawStyle, _Zui_Fmradio_Infomation_Edit_Name_Value2_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_EDIT_NAME_VALUE3
    { _Zui_Fmradio_Infomation_Edit_Name_Value3_Normal_DrawStyle, _Zui_Fmradio_Infomation_Edit_Name_Value3_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_EDIT_NAME_VALUE4
    { _Zui_Fmradio_Infomation_Edit_Name_Value4_Normal_DrawStyle, _Zui_Fmradio_Infomation_Edit_Name_Value4_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_EDIT_NAME_VALUE5
    { _Zui_Fmradio_Infomation_Edit_Name_Value5_Normal_DrawStyle, _Zui_Fmradio_Infomation_Edit_Name_Value5_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_EDIT_NAME_VALUE6
    { _Zui_Fmradio_Infomation_Edit_Name_Value6_Normal_DrawStyle, _Zui_Fmradio_Infomation_Edit_Name_Value6_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_INFOMATION_PAGE_TITLE
    { _Zui_Fmradio_Infomation_Page_Title_Normal_DrawStyle, _Zui_Fmradio_Infomation_Page_Title_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_AUTOTUNE_INFO_PAGE
    { _Zui_Fmradio_Autotune_Info_Page_Normal_DrawStyle, _Zui_Fmradio_Autotune_Info_Page_Focus_DrawStyle, _Zui_Fmradio_Autotune_Info_Page_Disabled_DrawStyle     },

    // HWND_FMRADIO_AUTOTUNE_INFO_PROGRESS_BAR
    { _Zui_Fmradio_Autotune_Info_Progress_Bar_Normal_DrawStyle, NULL, NULL     },

    // HWND_FMRADIO_AUTOTUNE_INFO_PERCENTAGE_VALUE
    { _Zui_Fmradio_Autotune_Info_Percentage_Value_Normal_DrawStyle, _Zui_Fmradio_Autotune_Info_Percentage_Value_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_AUTOTUNE_INFO_PERCENTAGE_TEXT
    { _Zui_Fmradio_Autotune_Info_Percentage_Text_Normal_DrawStyle, _Zui_Fmradio_Autotune_Info_Percentage_Text_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_AUTOTUNE_INFO_FREQUENCY_VALUE
    { _Zui_Fmradio_Autotune_Info_Frequency_Value_Normal_DrawStyle, _Zui_Fmradio_Autotune_Info_Frequency_Value_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_AUTOTUNE_INFO_FREQUENCY_TEXT
    { _Zui_Fmradio_Autotune_Info_Frequency_Text_Normal_DrawStyle, _Zui_Fmradio_Autotune_Info_Frequency_Text_Focus_DrawStyle, NULL     },

    // HWND_FMRADIO_TENKEY_CH_NUMBER_PAGE
    { _Zui_Fmradio_Tenkey_Ch_Number_Page_Normal_DrawStyle, _Zui_Fmradio_Tenkey_Ch_Number_Page_Focus_DrawStyle, NULL     },

};
