////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jan  5 2015 10:22:03]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// KTV_MAIN_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ktv_Main_Bg_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_0 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// KTV_MAIN_ITEMS styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ktv_Main_Items_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_23 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// KTV_SEARCH_BY_SINGER_TYPE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ktv_Search_By_Singer_Type_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_23 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_2 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// KTV_SEARCH_BY_SINGER_SEARCH_TYPE styles..

#define _Zui_Ktv_Search_By_Singer_Search_Type_Normal_DrawStyle _Zui_Ktv_Search_By_Singer_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_SEARCH_BY_SINGER_PAGE styles..

#define _Zui_Ktv_Search_By_Singer_Page_Normal_DrawStyle _Zui_Ktv_Main_Items_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_SEARCH_FOUND_SONGS styles..

#define _Zui_Ktv_Search_Found_Songs_Normal_DrawStyle _Zui_Ktv_Main_Items_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_SEARCH_BY_SINGER_NAMELIST styles..

#define _Zui_Ktv_Search_By_Singer_Namelist_Normal_DrawStyle _Zui_Ktv_Main_Items_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_SEARCH_BY_NAME_PAGE styles..

#define _Zui_Ktv_Search_By_Name_Page_Normal_DrawStyle _Zui_Ktv_Main_Items_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_SEARCH_BY_NAME_WORDNUMBER_PAGE styles..

#define _Zui_Ktv_Search_By_Name_Wordnumber_Page_Normal_DrawStyle _Zui_Ktv_Main_Items_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_SEARCH_BY_NAME_WORDNUMBER_LIST_PAGE styles..

#define _Zui_Ktv_Search_By_Name_Wordnumber_List_Page_Normal_DrawStyle _Zui_Ktv_Main_Items_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_SEARCH_BY_ID_PAGE styles..

#define _Zui_Ktv_Search_By_Id_Page_Normal_DrawStyle _Zui_Ktv_Main_Items_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_SOFTWARE_KEYBOARD_DIGIT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ktv_Software_Keyboard_Digit_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_24 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_10 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Ktv_Software_Keyboard_Digit_Focus_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_24 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// KTV_SOFTWARE_KEYBOARD_LETTER styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ktv_Software_Keyboard_Letter_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_25 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_2 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// KTV_SONGS_LIST_TO_PLAY styles..

#define _Zui_Ktv_Songs_List_To_Play_Normal_DrawStyle _Zui_Ktv_Main_Items_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_TONE_OF_SONGS styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ktv_Tone_Of_Songs_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_26 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_11 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// KTV_DIALOG styles..

#define _Zui_Ktv_Dialog_Normal_DrawStyle _Zui_Ktv_Search_By_Singer_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_SETUP_PAGE styles..

#define _Zui_Ktv_Setup_Page_Normal_DrawStyle _Zui_Ktv_Search_By_Singer_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_SETUP_SOUND_SETTING_PAGE styles..

#define _Zui_Ktv_Setup_Sound_Setting_Page_Normal_DrawStyle _Zui_Ktv_Search_By_Singer_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// KTV_SIMPLE_CONTROL_BAR styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ktv_Simple_Control_Bar_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_4 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_11 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// KTV_MSGBOX_PANE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ktv_Msgbox_Pane_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_27 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// KTV_WAITING_INFO styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Ktv_Waiting_Info_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_4 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_2 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Ktv_Waiting_Info_Focus_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_4 },
    { CP_NOON, 0 },
};

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Ktv_Main[] =
{
    // HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // HWND_KTV_MAIN_BG
    { _Zui_Ktv_Main_Bg_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_MAIN_ITEMS
    { _Zui_Ktv_Main_Items_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SEARCH_BY_SINGER_TYPE
    { _Zui_Ktv_Search_By_Singer_Type_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SEARCH_BY_SINGER_SEARCH_TYPE
    { _Zui_Ktv_Search_By_Singer_Search_Type_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SEARCH_BY_SINGER_PAGE
    { _Zui_Ktv_Search_By_Singer_Page_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SEARCH_FOUND_SONGS
    { _Zui_Ktv_Search_Found_Songs_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SEARCH_BY_SINGER_NAMELIST
    { _Zui_Ktv_Search_By_Singer_Namelist_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SEARCH_BY_NAME_PAGE
    { _Zui_Ktv_Search_By_Name_Page_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SEARCH_BY_NAME_WORDNUMBER_PAGE
    { _Zui_Ktv_Search_By_Name_Wordnumber_Page_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SEARCH_BY_NAME_WORDNUMBER_LIST_PAGE
    { _Zui_Ktv_Search_By_Name_Wordnumber_List_Page_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SEARCH_BY_ID_PAGE
    { _Zui_Ktv_Search_By_Id_Page_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SOFTWARE_KEYBOARD_DIGIT
    { _Zui_Ktv_Software_Keyboard_Digit_Normal_DrawStyle, _Zui_Ktv_Software_Keyboard_Digit_Focus_DrawStyle, NULL     },

    // HWND_KTV_SOFTWARE_KEYBOARD_LETTER
    { _Zui_Ktv_Software_Keyboard_Letter_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SONGS_LIST_TO_PLAY
    { _Zui_Ktv_Songs_List_To_Play_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_TONE_OF_SONGS
    { _Zui_Ktv_Tone_Of_Songs_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_DIALOG
    { _Zui_Ktv_Dialog_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SETUP_PAGE
    { _Zui_Ktv_Setup_Page_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SETUP_SOUND_SETTING_PAGE
    { _Zui_Ktv_Setup_Sound_Setting_Page_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_SIMPLE_CONTROL_BAR
    { _Zui_Ktv_Simple_Control_Bar_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_MSGBOX_PANE
    { _Zui_Ktv_Msgbox_Pane_Normal_DrawStyle, NULL, NULL     },

    // HWND_KTV_WAITING_INFO
    { _Zui_Ktv_Waiting_Info_Normal_DrawStyle, _Zui_Ktv_Waiting_Info_Focus_DrawStyle, NULL     },

};
