////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2017 09:17:51]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// DESIGN_MENU_BG_TRANSPARENT styles..


/////////////////////////////////////////////////////
// DESIGN_MENU_BAR_TRANS styles..


/////////////////////////////////////////////////////
// DESIGN_MENU_BAR styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Bar_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_34 },
    { CP_NOON, 0 },
};
#define _Zui_Design_Menu_Bar_Focus_DrawStyle _Zui_Design_Menu_Bar_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_BAR_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Bar_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1019 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Bar_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1043 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Bar_Text_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1044 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_MENU_BAR_OPTION styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Bar_Option_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1045 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Bar_Option_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1046 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Bar_Option_Disabled_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1047 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_MENU_BAR_LEFT_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Bar_Left_Arrow_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_37 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_MENU_BAR_RIGHT_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Bar_Right_Arrow_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_38 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_MENU_BG_PANE styles..


/////////////////////////////////////////////////////
// DESIGN_MENU_BG_RECT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Bg_Rect_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_25 },
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_10 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_MENU_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1048 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_MENU_INPUT_INFO styles..


/////////////////////////////////////////////////////
// DESIGN_MENU_INPUT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Input_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1049 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_MENU_INPUT_TYPE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Input_Type_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1050 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_MENU_LIST styles..


/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM0 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Item0_Focus_DrawStyle[] =
{
    { CP_RECT_BORDER, CP_ZUI_RECT_BORDER_INDEX_2 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM0_NAME styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Item0_Name_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1051 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Item0_Name_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_947 },
    { CP_NOON, 0 },
};
#define _Zui_Design_Menu_Item0_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM0_VALUE styles..

#define _Zui_Design_Menu_Item0_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Item0_Value_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1027 },
    { CP_NOON, 0 },
};
#define _Zui_Design_Menu_Item0_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM1 styles..

#define _Zui_Design_Menu_Item1_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM1_NAME styles..

#define _Zui_Design_Menu_Item1_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item1_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item1_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM1_VALUE styles..

#define _Zui_Design_Menu_Item1_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item1_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item1_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM2 styles..

#define _Zui_Design_Menu_Item2_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM2_NAME styles..

#define _Zui_Design_Menu_Item2_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item2_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item2_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM2_VALUE styles..

#define _Zui_Design_Menu_Item2_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item2_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item2_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM3 styles..

#define _Zui_Design_Menu_Item3_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM3_NAME styles..

#define _Zui_Design_Menu_Item3_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item3_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item3_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM3_VALUE styles..

#define _Zui_Design_Menu_Item3_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item3_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item3_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM4 styles..

#define _Zui_Design_Menu_Item4_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM4_NAME styles..

#define _Zui_Design_Menu_Item4_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item4_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item4_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM4_VALUE styles..

#define _Zui_Design_Menu_Item4_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item4_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item4_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM5 styles..

#define _Zui_Design_Menu_Item5_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM5_NAME styles..

#define _Zui_Design_Menu_Item5_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item5_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item5_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM5_VALUE styles..

#define _Zui_Design_Menu_Item5_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item5_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item5_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM6 styles..

#define _Zui_Design_Menu_Item6_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM6_NAME styles..

#define _Zui_Design_Menu_Item6_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item6_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item6_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM6_VALUE styles..

#define _Zui_Design_Menu_Item6_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item6_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item6_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM7 styles..

#define _Zui_Design_Menu_Item7_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM7_NAME styles..

#define _Zui_Design_Menu_Item7_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item7_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item7_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM7_VALUE styles..

#define _Zui_Design_Menu_Item7_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item7_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item7_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM8 styles..

#define _Zui_Design_Menu_Item8_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM8_NAME styles..

#define _Zui_Design_Menu_Item8_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item8_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item8_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM8_VALUE styles..

#define _Zui_Design_Menu_Item8_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item8_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item8_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM9 styles..

#define _Zui_Design_Menu_Item9_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM9_NAME styles..

#define _Zui_Design_Menu_Item9_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item9_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item9_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM9_VALUE styles..

#define _Zui_Design_Menu_Item9_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item9_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item9_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM10 styles..

#define _Zui_Design_Menu_Item10_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM10_NAME styles..

#define _Zui_Design_Menu_Item10_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item10_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item10_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM10_VALUE styles..

#define _Zui_Design_Menu_Item10_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item10_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item10_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM11 styles..

#define _Zui_Design_Menu_Item11_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM11_NAME styles..

#define _Zui_Design_Menu_Item11_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item11_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item11_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM11_VALUE styles..

#define _Zui_Design_Menu_Item11_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item11_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item11_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM12 styles..

#define _Zui_Design_Menu_Item12_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM12_NAME styles..

#define _Zui_Design_Menu_Item12_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item12_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item12_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM12_VALUE styles..

#define _Zui_Design_Menu_Item12_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item12_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item12_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM13 styles..

#define _Zui_Design_Menu_Item13_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM13_NAME styles..

#define _Zui_Design_Menu_Item13_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item13_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item13_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM13_VALUE styles..

#define _Zui_Design_Menu_Item13_Value_Normal_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle
#define _Zui_Design_Menu_Item13_Value_Focus_DrawStyle _Zui_Design_Menu_Item0_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item13_Value_Disabled_DrawStyle _Zui_Design_Menu_Input_Type_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM14 styles..

#define _Zui_Design_Menu_Item14_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM14_NAME styles..

#define _Zui_Design_Menu_Item14_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item14_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item14_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM14_VALUE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Item14_Value_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1052 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Item14_Value_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1053 },
    { CP_NOON, 0 },
};
#define _Zui_Design_Menu_Item14_Value_Disabled_DrawStyle _Zui_Design_Menu_Item14_Value_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM15 styles..

#define _Zui_Design_Menu_Item15_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM15_NAME styles..

#define _Zui_Design_Menu_Item15_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item15_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item15_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM15_VALUE styles..

#define _Zui_Design_Menu_Item15_Value_Normal_DrawStyle _Zui_Design_Menu_Item14_Value_Normal_DrawStyle
#define _Zui_Design_Menu_Item15_Value_Focus_DrawStyle _Zui_Design_Menu_Item14_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item15_Value_Disabled_DrawStyle _Zui_Design_Menu_Item14_Value_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM16 styles..

#define _Zui_Design_Menu_Item16_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM16_NAME styles..

#define _Zui_Design_Menu_Item16_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item16_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item16_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM16_VALUE styles..

#define _Zui_Design_Menu_Item16_Value_Normal_DrawStyle _Zui_Design_Menu_Item14_Value_Normal_DrawStyle
#define _Zui_Design_Menu_Item16_Value_Focus_DrawStyle _Zui_Design_Menu_Item14_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item16_Value_Disabled_DrawStyle _Zui_Design_Menu_Item14_Value_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM17 styles..

#define _Zui_Design_Menu_Item17_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM17_NAME styles..

#define _Zui_Design_Menu_Item17_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item17_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item17_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM17_VALUE styles..

#define _Zui_Design_Menu_Item17_Value_Normal_DrawStyle _Zui_Design_Menu_Item14_Value_Normal_DrawStyle
#define _Zui_Design_Menu_Item17_Value_Focus_DrawStyle _Zui_Design_Menu_Item14_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item17_Value_Disabled_DrawStyle _Zui_Design_Menu_Item14_Value_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM18 styles..

#define _Zui_Design_Menu_Item18_Focus_DrawStyle _Zui_Design_Menu_Item0_Focus_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM18_NAME styles..

#define _Zui_Design_Menu_Item18_Name_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle
#define _Zui_Design_Menu_Item18_Name_Focus_DrawStyle _Zui_Design_Menu_Item0_Name_Focus_DrawStyle
#define _Zui_Design_Menu_Item18_Name_Disabled_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_ITEM18_VALUE styles..

#define _Zui_Design_Menu_Item18_Value_Normal_DrawStyle _Zui_Design_Menu_Item14_Value_Normal_DrawStyle
#define _Zui_Design_Menu_Item18_Value_Focus_DrawStyle _Zui_Design_Menu_Item14_Value_Focus_DrawStyle
#define _Zui_Design_Menu_Item18_Value_Disabled_DrawStyle _Zui_Design_Menu_Item14_Value_Normal_DrawStyle

/////////////////////////////////////////////////////
// DESIGN_MENU_HOT_KEY_HELP1 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Hot_Key_Help1_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1054 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_MENU_HOT_KEY_HELP2 styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Menu_Hot_Key_Help2_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1055 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_SW_INFO styles..


/////////////////////////////////////////////////////
// DESIGN_SW_INFO_VERSION styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Sw_Info_Version_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1056 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_SW_INFO_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Design_Sw_Info_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1057 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// DESIGN_MENU_BOARD_INFO styles..

#define _Zui_Design_Menu_Board_Info_Normal_DrawStyle _Zui_Design_Menu_Item0_Name_Normal_DrawStyle

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Design_Menu[] =
{
    // HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // HWND_DESIGN_MENU_BG_TRANSPARENT
    { NULL, NULL, NULL     },

    // HWND_DESIGN_MENU_BAR_TRANS
    { NULL, NULL, NULL     },

    // HWND_DESIGN_MENU_BAR
    { _Zui_Design_Menu_Bar_Normal_DrawStyle, _Zui_Design_Menu_Bar_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_BAR_TEXT
    { _Zui_Design_Menu_Bar_Text_Normal_DrawStyle, _Zui_Design_Menu_Bar_Text_Focus_DrawStyle, _Zui_Design_Menu_Bar_Text_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_BAR_OPTION
    { _Zui_Design_Menu_Bar_Option_Normal_DrawStyle, _Zui_Design_Menu_Bar_Option_Focus_DrawStyle, _Zui_Design_Menu_Bar_Option_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_BAR_LEFT_ARROW
    { NULL, _Zui_Design_Menu_Bar_Left_Arrow_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_BAR_RIGHT_ARROW
    { NULL, _Zui_Design_Menu_Bar_Right_Arrow_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_BG_PANE
    { NULL, NULL, NULL     },

    // HWND_DESIGN_MENU_BG_RECT
    { _Zui_Design_Menu_Bg_Rect_Normal_DrawStyle, NULL, NULL     },

    // HWND_DESIGN_MENU_TITLE
    { _Zui_Design_Menu_Title_Normal_DrawStyle, NULL, NULL     },

    // HWND_DESIGN_MENU_INPUT_INFO
    { NULL, NULL, NULL     },

    // HWND_DESIGN_MENU_INPUT
    { _Zui_Design_Menu_Input_Normal_DrawStyle, NULL, NULL     },

    // HWND_DESIGN_MENU_INPUT_TYPE
    { _Zui_Design_Menu_Input_Type_Normal_DrawStyle, NULL, NULL     },

    // HWND_DESIGN_MENU_LIST
    { NULL, NULL, NULL     },

    // HWND_DESIGN_MENU_ITEM0
    { NULL, _Zui_Design_Menu_Item0_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM0_NAME
    { _Zui_Design_Menu_Item0_Name_Normal_DrawStyle, _Zui_Design_Menu_Item0_Name_Focus_DrawStyle, _Zui_Design_Menu_Item0_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM0_VALUE
    { _Zui_Design_Menu_Item0_Value_Normal_DrawStyle, _Zui_Design_Menu_Item0_Value_Focus_DrawStyle, _Zui_Design_Menu_Item0_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM1
    { NULL, _Zui_Design_Menu_Item1_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM1_NAME
    { _Zui_Design_Menu_Item1_Name_Normal_DrawStyle, _Zui_Design_Menu_Item1_Name_Focus_DrawStyle, _Zui_Design_Menu_Item1_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM1_VALUE
    { _Zui_Design_Menu_Item1_Value_Normal_DrawStyle, _Zui_Design_Menu_Item1_Value_Focus_DrawStyle, _Zui_Design_Menu_Item1_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM2
    { NULL, _Zui_Design_Menu_Item2_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM2_NAME
    { _Zui_Design_Menu_Item2_Name_Normal_DrawStyle, _Zui_Design_Menu_Item2_Name_Focus_DrawStyle, _Zui_Design_Menu_Item2_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM2_VALUE
    { _Zui_Design_Menu_Item2_Value_Normal_DrawStyle, _Zui_Design_Menu_Item2_Value_Focus_DrawStyle, _Zui_Design_Menu_Item2_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM3
    { NULL, _Zui_Design_Menu_Item3_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM3_NAME
    { _Zui_Design_Menu_Item3_Name_Normal_DrawStyle, _Zui_Design_Menu_Item3_Name_Focus_DrawStyle, _Zui_Design_Menu_Item3_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM3_VALUE
    { _Zui_Design_Menu_Item3_Value_Normal_DrawStyle, _Zui_Design_Menu_Item3_Value_Focus_DrawStyle, _Zui_Design_Menu_Item3_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM4
    { NULL, _Zui_Design_Menu_Item4_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM4_NAME
    { _Zui_Design_Menu_Item4_Name_Normal_DrawStyle, _Zui_Design_Menu_Item4_Name_Focus_DrawStyle, _Zui_Design_Menu_Item4_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM4_VALUE
    { _Zui_Design_Menu_Item4_Value_Normal_DrawStyle, _Zui_Design_Menu_Item4_Value_Focus_DrawStyle, _Zui_Design_Menu_Item4_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM5
    { NULL, _Zui_Design_Menu_Item5_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM5_NAME
    { _Zui_Design_Menu_Item5_Name_Normal_DrawStyle, _Zui_Design_Menu_Item5_Name_Focus_DrawStyle, _Zui_Design_Menu_Item5_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM5_VALUE
    { _Zui_Design_Menu_Item5_Value_Normal_DrawStyle, _Zui_Design_Menu_Item5_Value_Focus_DrawStyle, _Zui_Design_Menu_Item5_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM6
    { NULL, _Zui_Design_Menu_Item6_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM6_NAME
    { _Zui_Design_Menu_Item6_Name_Normal_DrawStyle, _Zui_Design_Menu_Item6_Name_Focus_DrawStyle, _Zui_Design_Menu_Item6_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM6_VALUE
    { _Zui_Design_Menu_Item6_Value_Normal_DrawStyle, _Zui_Design_Menu_Item6_Value_Focus_DrawStyle, _Zui_Design_Menu_Item6_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM7
    { NULL, _Zui_Design_Menu_Item7_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM7_NAME
    { _Zui_Design_Menu_Item7_Name_Normal_DrawStyle, _Zui_Design_Menu_Item7_Name_Focus_DrawStyle, _Zui_Design_Menu_Item7_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM7_VALUE
    { _Zui_Design_Menu_Item7_Value_Normal_DrawStyle, _Zui_Design_Menu_Item7_Value_Focus_DrawStyle, _Zui_Design_Menu_Item7_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM8
    { NULL, _Zui_Design_Menu_Item8_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM8_NAME
    { _Zui_Design_Menu_Item8_Name_Normal_DrawStyle, _Zui_Design_Menu_Item8_Name_Focus_DrawStyle, _Zui_Design_Menu_Item8_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM8_VALUE
    { _Zui_Design_Menu_Item8_Value_Normal_DrawStyle, _Zui_Design_Menu_Item8_Value_Focus_DrawStyle, _Zui_Design_Menu_Item8_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM9
    { NULL, _Zui_Design_Menu_Item9_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM9_NAME
    { _Zui_Design_Menu_Item9_Name_Normal_DrawStyle, _Zui_Design_Menu_Item9_Name_Focus_DrawStyle, _Zui_Design_Menu_Item9_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM9_VALUE
    { _Zui_Design_Menu_Item9_Value_Normal_DrawStyle, _Zui_Design_Menu_Item9_Value_Focus_DrawStyle, _Zui_Design_Menu_Item9_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM10
    { NULL, _Zui_Design_Menu_Item10_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM10_NAME
    { _Zui_Design_Menu_Item10_Name_Normal_DrawStyle, _Zui_Design_Menu_Item10_Name_Focus_DrawStyle, _Zui_Design_Menu_Item10_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM10_VALUE
    { _Zui_Design_Menu_Item10_Value_Normal_DrawStyle, _Zui_Design_Menu_Item10_Value_Focus_DrawStyle, _Zui_Design_Menu_Item10_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM11
    { NULL, _Zui_Design_Menu_Item11_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM11_NAME
    { _Zui_Design_Menu_Item11_Name_Normal_DrawStyle, _Zui_Design_Menu_Item11_Name_Focus_DrawStyle, _Zui_Design_Menu_Item11_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM11_VALUE
    { _Zui_Design_Menu_Item11_Value_Normal_DrawStyle, _Zui_Design_Menu_Item11_Value_Focus_DrawStyle, _Zui_Design_Menu_Item11_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM12
    { NULL, _Zui_Design_Menu_Item12_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM12_NAME
    { _Zui_Design_Menu_Item12_Name_Normal_DrawStyle, _Zui_Design_Menu_Item12_Name_Focus_DrawStyle, _Zui_Design_Menu_Item12_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM12_VALUE
    { _Zui_Design_Menu_Item12_Value_Normal_DrawStyle, _Zui_Design_Menu_Item12_Value_Focus_DrawStyle, _Zui_Design_Menu_Item12_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM13
    { NULL, _Zui_Design_Menu_Item13_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM13_NAME
    { _Zui_Design_Menu_Item13_Name_Normal_DrawStyle, _Zui_Design_Menu_Item13_Name_Focus_DrawStyle, _Zui_Design_Menu_Item13_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM13_VALUE
    { _Zui_Design_Menu_Item13_Value_Normal_DrawStyle, _Zui_Design_Menu_Item13_Value_Focus_DrawStyle, _Zui_Design_Menu_Item13_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM14
    { NULL, _Zui_Design_Menu_Item14_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM14_NAME
    { _Zui_Design_Menu_Item14_Name_Normal_DrawStyle, _Zui_Design_Menu_Item14_Name_Focus_DrawStyle, _Zui_Design_Menu_Item14_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM14_VALUE
    { _Zui_Design_Menu_Item14_Value_Normal_DrawStyle, _Zui_Design_Menu_Item14_Value_Focus_DrawStyle, _Zui_Design_Menu_Item14_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM15
    { NULL, _Zui_Design_Menu_Item15_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM15_NAME
    { _Zui_Design_Menu_Item15_Name_Normal_DrawStyle, _Zui_Design_Menu_Item15_Name_Focus_DrawStyle, _Zui_Design_Menu_Item15_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM15_VALUE
    { _Zui_Design_Menu_Item15_Value_Normal_DrawStyle, _Zui_Design_Menu_Item15_Value_Focus_DrawStyle, _Zui_Design_Menu_Item15_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM16
    { NULL, _Zui_Design_Menu_Item16_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM16_NAME
    { _Zui_Design_Menu_Item16_Name_Normal_DrawStyle, _Zui_Design_Menu_Item16_Name_Focus_DrawStyle, _Zui_Design_Menu_Item16_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM16_VALUE
    { _Zui_Design_Menu_Item16_Value_Normal_DrawStyle, _Zui_Design_Menu_Item16_Value_Focus_DrawStyle, _Zui_Design_Menu_Item16_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM17
    { NULL, _Zui_Design_Menu_Item17_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM17_NAME
    { _Zui_Design_Menu_Item17_Name_Normal_DrawStyle, _Zui_Design_Menu_Item17_Name_Focus_DrawStyle, _Zui_Design_Menu_Item17_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM17_VALUE
    { _Zui_Design_Menu_Item17_Value_Normal_DrawStyle, _Zui_Design_Menu_Item17_Value_Focus_DrawStyle, _Zui_Design_Menu_Item17_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM18
    { NULL, _Zui_Design_Menu_Item18_Focus_DrawStyle, NULL     },

    // HWND_DESIGN_MENU_ITEM18_NAME
    { _Zui_Design_Menu_Item18_Name_Normal_DrawStyle, _Zui_Design_Menu_Item18_Name_Focus_DrawStyle, _Zui_Design_Menu_Item18_Name_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_ITEM18_VALUE
    { _Zui_Design_Menu_Item18_Value_Normal_DrawStyle, _Zui_Design_Menu_Item18_Value_Focus_DrawStyle, _Zui_Design_Menu_Item18_Value_Disabled_DrawStyle     },

    // HWND_DESIGN_MENU_HOT_KEY_HELP1
    { _Zui_Design_Menu_Hot_Key_Help1_Normal_DrawStyle, NULL, NULL     },

    // HWND_DESIGN_MENU_HOT_KEY_HELP2
    { _Zui_Design_Menu_Hot_Key_Help2_Normal_DrawStyle, NULL, NULL     },

    // HWND_DESIGN_SW_INFO
    { NULL, NULL, NULL     },

    // HWND_DESIGN_SW_INFO_VERSION
    { _Zui_Design_Sw_Info_Version_Normal_DrawStyle, NULL, NULL     },

    // HWND_DESIGN_SW_INFO_TEXT
    { _Zui_Design_Sw_Info_Text_Normal_DrawStyle, NULL, NULL     },

    // HWND_DESIGN_MENU_BOARD_INFO
    { _Zui_Design_Menu_Board_Info_Normal_DrawStyle, NULL, NULL     },

};
