// New DLC from No OS Code Ver.01

// ==============  Fix Star ====================
#define DLC_PARAMETER_L_L_U     			  3
#define DLC_PARAMETER_L_L_D     			  0
#define DLC_PARAMETER_L_H_U     			  3
#define DLC_PARAMETER_L_H_D     			  3
#define DLC_PARAMETER_S_L_U     			  128
#define DLC_PARAMETER_S_L_D     			  128
#define DLC_PARAMETER_S_H_U     			  128
#define DLC_PARAMETER_S_H_D     			  127
#define DLC_PARAMETER_PURE_IMAGE_MODE      E_XC_DLC_PURE_IMAGE_DO_NOTHING
#define DLC_PARAMETER_LEVEL_LIMIT          0
#define DLC_PARAMETER_AVG_DELTA            15
#define DLC_PARAMETER_AVG_DELTA_STILL      0
#define DLC_PARAMETER_FAST_ALPHA_BLENDING  31
#define DLC_PARAMETER_BLE_POINT            48
#define DLC_PARAMETER_WLE_POINT            48
#define DLC_PARAMETER_ENABLE_BLE           0
#define DLC_PARAMETER_ENABLE_WLE           0
#define DLC_CGC_ENABLE                     0
#define DLC_CGC_CGAIN_OFFSET               0
#define DLC_CGC_CGAIN_LIMIT_H              0x00
#define DLC_CGC_CGAIN_LIMIT_L              0x00
#define DLC_CGC_YC_SLOPE                   0x01
#define DLC_CGC_Y_TH                       0x08
// ==============  Fix End ====================
#define DLC_PARAMETER_CURVE_MODE                    2
#define DLC_PARAMETER_Y_AVG_THRESHOLD_M             70
#define DLC_PARAMETER_CURVE_MIXALPHA                72
#define DLC_PARAMETER_SepPoint_H                    188
#define DLC_PARAMETER_SepPoint_L                    80
#define DLC_PARAMETER_BLEStartPointTH               640
#define DLC_PARAMETER_BLEEndPointTH                 320
#define DLC_PARAMETER_DLC_CurveDiff_L_TH            56
#define DLC_PARAMETER_DLC_CurveDiff_H_TH            148
#define DLC_PARAMETER_BLE_Slop_Point1               1032
#define DLC_PARAMETER_BLE_Slop_Point2               1172
#define DLC_PARAMETER_BLE_Slop_Point3               1242
#define DLC_PARAMETER_BLE_Slop_Point4               1324
#define DLC_PARAMETER_BLE_Slop_Point5               1396
#define DLC_PARAMETER_BLE_Dark_Slop_Min             1200
#define DLC_PARAMETER_DLC_CurveDiff_Coring_TH   2
#define DLC_PARAMETER_DLC_FAST_ALPHA_BLENDING_MIN   1
#define DLC_PARAMETER_DLC_FAST_ALPHA_BLENDING_MAX   128
#define DLC_PARAMETER_DLC_FlICKER_ALPHA             96
#define DLC_PARAMETER_DLC_YAVG_L_TH                 56
#define DLC_PARAMETER_DLC_YAVG_H_TH                 136
#define DLC_PARAMETER_DLC_DiffBase_L                4
#define DLC_PARAMETER_DLC_DiffBase_M                14
#define DLC_PARAMETER_DLC_DiffBase_H                20
#define DLC_PARAMETER_Y_AVG_THRESHOLD_L             5
#define DLC_PARAMETER_Y_AVG_THRESHOLD_H             200
