////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2017 09:17:51]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_BG_PANE styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_BG_CLEAN styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Info_Bg_Clean_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_0 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_BG_C styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Bg_C_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_153 },
    { CP_NOON, 0 },
};
#define _Zui_Pvr_Browser_Bg_C_Focus_DrawStyle _Zui_Pvr_Browser_Bg_C_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_BG_L styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Bg_L_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_154 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_BG_R styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Bg_R_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_155 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_TOP_HALF_BANNER_TITLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Top_Half_Banner_Title_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1125 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_TOP_HALF_BANNER_TITLE_TYPE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Top_Half_Banner_Title_Type_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_771 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_BOTTOM_OK_BTN styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Bottom_Ok_Btn_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_36 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_BOTTOM_INDEX_BTN styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Bottom_Index_Btn_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_228 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_BOTTOM_INFO_BTN styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Bottom_Info_Btn_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_225 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_BOTTOM_DELETE_BTN styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Bottom_Delete_Btn_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_156 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_LIST_PANE styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM0 styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM0_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Item0_Bg_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_126 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM0_ICON styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_282 },
    { CP_NOON, 0 },
};
#define _Zui_Pvr_Browser_Item0_Icon_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM0_TEXT styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Item0_Text_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_946 },
    { CP_NOON, 0 },
};
static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Item0_Text_Focus_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1126 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM0_R_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Item0_R_Arrow_Focus_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_38 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM1 styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM1_BG styles..

#define _Zui_Pvr_Browser_Item1_Bg_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM1_ICON styles..

#define _Zui_Pvr_Browser_Item1_Icon_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item1_Icon_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM1_TEXT styles..

#define _Zui_Pvr_Browser_Item1_Text_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Text_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item1_Text_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM1_R_ARROW styles..

#define _Zui_Pvr_Browser_Item1_R_Arrow_Focus_DrawStyle _Zui_Pvr_Browser_Item0_R_Arrow_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM2 styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM2_BG styles..

#define _Zui_Pvr_Browser_Item2_Bg_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM2_ICON styles..

#define _Zui_Pvr_Browser_Item2_Icon_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item2_Icon_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM2_TEXT styles..

#define _Zui_Pvr_Browser_Item2_Text_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Text_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item2_Text_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM2_R_ARROW styles..

#define _Zui_Pvr_Browser_Item2_R_Arrow_Focus_DrawStyle _Zui_Pvr_Browser_Item0_R_Arrow_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM3 styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM3_BG styles..

#define _Zui_Pvr_Browser_Item3_Bg_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM3_ICON styles..

#define _Zui_Pvr_Browser_Item3_Icon_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item3_Icon_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM3_TEXT styles..

#define _Zui_Pvr_Browser_Item3_Text_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Text_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item3_Text_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM3_R_ARROW styles..

#define _Zui_Pvr_Browser_Item3_R_Arrow_Focus_DrawStyle _Zui_Pvr_Browser_Item0_R_Arrow_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM4 styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM4_BG styles..

#define _Zui_Pvr_Browser_Item4_Bg_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM4_ICON styles..

#define _Zui_Pvr_Browser_Item4_Icon_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item4_Icon_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM4_TEXT styles..

#define _Zui_Pvr_Browser_Item4_Text_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Text_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item4_Text_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM4_R_ARROW styles..

#define _Zui_Pvr_Browser_Item4_R_Arrow_Focus_DrawStyle _Zui_Pvr_Browser_Item0_R_Arrow_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM5 styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM5_BG styles..

#define _Zui_Pvr_Browser_Item5_Bg_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM5_ICON styles..

#define _Zui_Pvr_Browser_Item5_Icon_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item5_Icon_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM5_TEXT styles..

#define _Zui_Pvr_Browser_Item5_Text_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Text_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item5_Text_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM5_R_ARROW styles..

#define _Zui_Pvr_Browser_Item5_R_Arrow_Focus_DrawStyle _Zui_Pvr_Browser_Item0_R_Arrow_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM6 styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM6_BG styles..

#define _Zui_Pvr_Browser_Item6_Bg_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM6_ICON styles..

#define _Zui_Pvr_Browser_Item6_Icon_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item6_Icon_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM6_TEXT styles..

#define _Zui_Pvr_Browser_Item6_Text_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Text_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item6_Text_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM6_R_ARROW styles..

#define _Zui_Pvr_Browser_Item6_R_Arrow_Focus_DrawStyle _Zui_Pvr_Browser_Item0_R_Arrow_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM7 styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM7_BG styles..

#define _Zui_Pvr_Browser_Item7_Bg_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM7_ICON styles..

#define _Zui_Pvr_Browser_Item7_Icon_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item7_Icon_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM7_TEXT styles..

#define _Zui_Pvr_Browser_Item7_Text_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Text_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item7_Text_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM7_R_ARROW styles..

#define _Zui_Pvr_Browser_Item7_R_Arrow_Focus_DrawStyle _Zui_Pvr_Browser_Item0_R_Arrow_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM8 styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM8_BG styles..

#define _Zui_Pvr_Browser_Item8_Bg_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM8_ICON styles..

#define _Zui_Pvr_Browser_Item8_Icon_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item8_Icon_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM8_TEXT styles..

#define _Zui_Pvr_Browser_Item8_Text_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Text_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item8_Text_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM8_R_ARROW styles..

#define _Zui_Pvr_Browser_Item8_R_Arrow_Focus_DrawStyle _Zui_Pvr_Browser_Item0_R_Arrow_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM9 styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM9_BG styles..

#define _Zui_Pvr_Browser_Item9_Bg_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Bg_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM9_ICON styles..

#define _Zui_Pvr_Browser_Item9_Icon_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item9_Icon_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM9_TEXT styles..

#define _Zui_Pvr_Browser_Item9_Text_Normal_DrawStyle _Zui_Pvr_Browser_Item0_Text_Normal_DrawStyle
#define _Zui_Pvr_Browser_Item9_Text_Focus_DrawStyle _Zui_Pvr_Browser_Item0_Text_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM9_R_ARROW styles..

#define _Zui_Pvr_Browser_Item9_R_Arrow_Focus_DrawStyle _Zui_Pvr_Browser_Item0_R_Arrow_Focus_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_PANE styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_ITEM_L_ARROW styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Item_L_Arrow_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_37 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_BG styles..


/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_BG_UP styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Info_Bg_Up_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_230 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_BG_MIDDLE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Info_Bg_Middle_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_229 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_BG_DOWN styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Info_Bg_Down_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_231 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_DATE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_1127 },
    { CP_NOON, 0 },
};
#define _Zui_Pvr_Browser_Info_Date_Focus_DrawStyle _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_TIME styles..

#define _Zui_Pvr_Browser_Info_Time_Normal_DrawStyle _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle
#define _Zui_Pvr_Browser_Info_Time_Focus_DrawStyle _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_DURATION styles..

#define _Zui_Pvr_Browser_Info_Duration_Normal_DrawStyle _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle
#define _Zui_Pvr_Browser_Info_Duration_Focus_DrawStyle _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_PROGRAM styles..

#define _Zui_Pvr_Browser_Info_Program_Normal_DrawStyle _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle
#define _Zui_Pvr_Browser_Info_Program_Focus_DrawStyle _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_CHANNEL styles..

#define _Zui_Pvr_Browser_Info_Channel_Normal_DrawStyle _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle
#define _Zui_Pvr_Browser_Info_Channel_Focus_DrawStyle _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle

/////////////////////////////////////////////////////
// PVR_BROWSER_INFO_DESCRIPTION styles..

#define _Zui_Pvr_Browser_Info_Description_Normal_DrawStyle _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle
#define _Zui_Pvr_Browser_Info_Description_Focus_DrawStyle _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Pvr_Browser[] =
{
    // HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_BG_PANE
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_INFO_BG_CLEAN
    { _Zui_Pvr_Browser_Info_Bg_Clean_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_BG_C
    { _Zui_Pvr_Browser_Bg_C_Normal_DrawStyle, _Zui_Pvr_Browser_Bg_C_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_BG_L
    { _Zui_Pvr_Browser_Bg_L_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_BG_R
    { _Zui_Pvr_Browser_Bg_R_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_TOP_HALF_BANNER_TITLE
    { _Zui_Pvr_Browser_Top_Half_Banner_Title_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_TOP_HALF_BANNER_TITLE_TYPE
    { _Zui_Pvr_Browser_Top_Half_Banner_Title_Type_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_BOTTOM_OK_BTN
    { _Zui_Pvr_Browser_Bottom_Ok_Btn_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_BOTTOM_INDEX_BTN
    { _Zui_Pvr_Browser_Bottom_Index_Btn_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_BOTTOM_INFO_BTN
    { _Zui_Pvr_Browser_Bottom_Info_Btn_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_BOTTOM_DELETE_BTN
    { _Zui_Pvr_Browser_Bottom_Delete_Btn_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_LIST_PANE
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM0
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM0_BG
    { NULL, _Zui_Pvr_Browser_Item0_Bg_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM0_ICON
    { _Zui_Pvr_Browser_Item0_Icon_Normal_DrawStyle, _Zui_Pvr_Browser_Item0_Icon_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM0_TEXT
    { _Zui_Pvr_Browser_Item0_Text_Normal_DrawStyle, _Zui_Pvr_Browser_Item0_Text_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM0_R_ARROW
    { NULL, _Zui_Pvr_Browser_Item0_R_Arrow_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM1
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM1_BG
    { NULL, _Zui_Pvr_Browser_Item1_Bg_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM1_ICON
    { _Zui_Pvr_Browser_Item1_Icon_Normal_DrawStyle, _Zui_Pvr_Browser_Item1_Icon_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM1_TEXT
    { _Zui_Pvr_Browser_Item1_Text_Normal_DrawStyle, _Zui_Pvr_Browser_Item1_Text_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM1_R_ARROW
    { NULL, _Zui_Pvr_Browser_Item1_R_Arrow_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM2
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM2_BG
    { NULL, _Zui_Pvr_Browser_Item2_Bg_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM2_ICON
    { _Zui_Pvr_Browser_Item2_Icon_Normal_DrawStyle, _Zui_Pvr_Browser_Item2_Icon_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM2_TEXT
    { _Zui_Pvr_Browser_Item2_Text_Normal_DrawStyle, _Zui_Pvr_Browser_Item2_Text_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM2_R_ARROW
    { NULL, _Zui_Pvr_Browser_Item2_R_Arrow_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM3
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM3_BG
    { NULL, _Zui_Pvr_Browser_Item3_Bg_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM3_ICON
    { _Zui_Pvr_Browser_Item3_Icon_Normal_DrawStyle, _Zui_Pvr_Browser_Item3_Icon_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM3_TEXT
    { _Zui_Pvr_Browser_Item3_Text_Normal_DrawStyle, _Zui_Pvr_Browser_Item3_Text_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM3_R_ARROW
    { NULL, _Zui_Pvr_Browser_Item3_R_Arrow_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM4
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM4_BG
    { NULL, _Zui_Pvr_Browser_Item4_Bg_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM4_ICON
    { _Zui_Pvr_Browser_Item4_Icon_Normal_DrawStyle, _Zui_Pvr_Browser_Item4_Icon_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM4_TEXT
    { _Zui_Pvr_Browser_Item4_Text_Normal_DrawStyle, _Zui_Pvr_Browser_Item4_Text_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM4_R_ARROW
    { NULL, _Zui_Pvr_Browser_Item4_R_Arrow_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM5
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM5_BG
    { NULL, _Zui_Pvr_Browser_Item5_Bg_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM5_ICON
    { _Zui_Pvr_Browser_Item5_Icon_Normal_DrawStyle, _Zui_Pvr_Browser_Item5_Icon_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM5_TEXT
    { _Zui_Pvr_Browser_Item5_Text_Normal_DrawStyle, _Zui_Pvr_Browser_Item5_Text_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM5_R_ARROW
    { NULL, _Zui_Pvr_Browser_Item5_R_Arrow_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM6
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM6_BG
    { NULL, _Zui_Pvr_Browser_Item6_Bg_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM6_ICON
    { _Zui_Pvr_Browser_Item6_Icon_Normal_DrawStyle, _Zui_Pvr_Browser_Item6_Icon_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM6_TEXT
    { _Zui_Pvr_Browser_Item6_Text_Normal_DrawStyle, _Zui_Pvr_Browser_Item6_Text_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM6_R_ARROW
    { NULL, _Zui_Pvr_Browser_Item6_R_Arrow_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM7
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM7_BG
    { NULL, _Zui_Pvr_Browser_Item7_Bg_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM7_ICON
    { _Zui_Pvr_Browser_Item7_Icon_Normal_DrawStyle, _Zui_Pvr_Browser_Item7_Icon_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM7_TEXT
    { _Zui_Pvr_Browser_Item7_Text_Normal_DrawStyle, _Zui_Pvr_Browser_Item7_Text_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM7_R_ARROW
    { NULL, _Zui_Pvr_Browser_Item7_R_Arrow_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM8
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM8_BG
    { NULL, _Zui_Pvr_Browser_Item8_Bg_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM8_ICON
    { _Zui_Pvr_Browser_Item8_Icon_Normal_DrawStyle, _Zui_Pvr_Browser_Item8_Icon_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM8_TEXT
    { _Zui_Pvr_Browser_Item8_Text_Normal_DrawStyle, _Zui_Pvr_Browser_Item8_Text_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM8_R_ARROW
    { NULL, _Zui_Pvr_Browser_Item8_R_Arrow_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM9
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM9_BG
    { NULL, _Zui_Pvr_Browser_Item9_Bg_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM9_ICON
    { _Zui_Pvr_Browser_Item9_Icon_Normal_DrawStyle, _Zui_Pvr_Browser_Item9_Icon_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM9_TEXT
    { _Zui_Pvr_Browser_Item9_Text_Normal_DrawStyle, _Zui_Pvr_Browser_Item9_Text_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_ITEM9_R_ARROW
    { NULL, _Zui_Pvr_Browser_Item9_R_Arrow_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_INFO_PANE
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_ITEM_L_ARROW
    { _Zui_Pvr_Browser_Item_L_Arrow_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_INFO_BG
    { NULL, NULL, NULL     },

    // HWND_PVR_BROWSER_INFO_BG_UP
    { _Zui_Pvr_Browser_Info_Bg_Up_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_INFO_BG_MIDDLE
    { _Zui_Pvr_Browser_Info_Bg_Middle_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_INFO_BG_DOWN
    { _Zui_Pvr_Browser_Info_Bg_Down_Normal_DrawStyle, NULL, NULL     },

    // HWND_PVR_BROWSER_INFO_DATE
    { _Zui_Pvr_Browser_Info_Date_Normal_DrawStyle, _Zui_Pvr_Browser_Info_Date_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_INFO_TIME
    { _Zui_Pvr_Browser_Info_Time_Normal_DrawStyle, _Zui_Pvr_Browser_Info_Time_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_INFO_DURATION
    { _Zui_Pvr_Browser_Info_Duration_Normal_DrawStyle, _Zui_Pvr_Browser_Info_Duration_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_INFO_PROGRAM
    { _Zui_Pvr_Browser_Info_Program_Normal_DrawStyle, _Zui_Pvr_Browser_Info_Program_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_INFO_CHANNEL
    { _Zui_Pvr_Browser_Info_Channel_Normal_DrawStyle, _Zui_Pvr_Browser_Info_Channel_Focus_DrawStyle, NULL     },

    // HWND_PVR_BROWSER_INFO_DESCRIPTION
    { _Zui_Pvr_Browser_Info_Description_Normal_DrawStyle, _Zui_Pvr_Browser_Info_Description_Focus_DrawStyle, NULL     },

};
