////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2017 09:17:51]
/////////////////////////////////////////////////////////////////////////////



//////////////////////////////////////////////////////
// Window List (Position)

WINDOWPOSDATA _MP_TBLSEG _GUI_WindowPositionList_Zui_Channel_Info_Atsc[] =
{
    // HWND_MAINFRAME
    {
        HWND_MAINFRAME, HWND_CHINFO_DIRECT_TUNE_PANEL_TEXT,
        { 0, 0, 1920, 1080 },
    },

    // HWND_CHINFO_TRANSPARENT
    {
        HWND_MAINFRAME, HWND_CHINFO_TRANSPARENT,
        { 0, 0, 1920, 1080 },
    },

    // HWND_CHINFO_BTM_EXT_PANE
    {
        HWND_MAINFRAME, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_BLUE,
        { 0, 788, 1920, 291 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_BG
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_BTM_EXT_PANE_EXTENTION_BG,
        { 0, 788, 1920, 291 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_TITLE_C
    {
        HWND_CHINFO_BTM_EXT_PANE_BG, HWND_CHINFO_BTM_EXT_PANE_TITLE_C,
        { 0, 788, 907, 61 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_TITLE_R
    {
        HWND_CHINFO_BTM_EXT_PANE_BG, HWND_CHINFO_BTM_EXT_PANE_TITLE_R,
        { 907, 788, 9, 61 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_GREEN_BG
    {
        HWND_CHINFO_BTM_EXT_PANE_BG, HWND_CHINFO_BTM_EXT_PANE_GREEN_BG,
        { 0, 850, 1920, 57 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_SIMPLE_BG
    {
        HWND_CHINFO_BTM_EXT_PANE_BG, HWND_CHINFO_BTM_EXT_PANE_SIMPLE_BG,
        { 0, 902, 1920, 92 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_EXTENTION_BG
    {
        HWND_CHINFO_BTM_EXT_PANE_BG, HWND_CHINFO_BTM_EXT_PANE_EXTENTION_BG,
        { 0, 992, 1920, 87 },
    },

    // HWND_CHINFO_PROG_NUM_TEXT
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_PROG_NUM_TEXT,
        { 23, 788, 210, 61 },
    },

    // HWND_CHINFO_PROG_NAME_TEXT
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_PROG_NAME_TEXT,
        { 238, 788, 258, 61 },
    },

    // HWND_CHINFO_CONTENT_1ST_ROW_CC_INFO
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_1ST_ROW_CC_INFO,
        { 147, 908, 416, 45 },
    },

    // HWND_CHINFO_CONTENT_2ND_ROW_RESOLUTION
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_2ND_ROW_RESOLUTION,
        { 1262, 908, 491, 45 },
    },

    // HWND_CHINFO_CONTENT_1ST_ROW_CC_ICON
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_1ST_ROW_CC_ICON,
        { 64, 909, 70, 35 },
    },

    // HWND_CHINFO_CONTENT_2ND_ROW_VID_RES_ICON
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_2ND_ROW_VID_RES_ICON,
        { 663, 908, 285, 40 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_TIME_TEXT
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_3RD_ROW_TIME_TEXT,
        { 500, 788, 415, 61 },
    },

    // HWND_CHINFO_CONTENT_1ST_ROW_EVENT_INFO
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_1ST_ROW_EVENT_INFO,
        { 517, 850, 877, 50 },
    },

    // HWND_CHINFO_CONTENT_2ND_ROW_SCRAMBLE_STATUS
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_2ND_ROW_SCRAMBLE_STATUS,
        { 64, 949, 1160, 45 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_BLUE,
        { 1262, 949, 491, 45 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_TEXT
    {
        HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_TEXT,
        { 1498, 949, 112, 45 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_RED
    {
        HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_RED,
        { 1262, 966, 59, 11 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_YELLOW
    {
        HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_YELLOW,
        { 1321, 966, 59, 11 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_GREEN
    {
        HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_GREEN,
        { 1380, 966, 59, 11 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_BLUE
    {
        HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_BLUE,
        { 1439, 966, 59, 11 },
    },

    // HWND_CHINFO_ETT_BG
    {
        HWND_MAINFRAME, HWND_CHINFO_ETT_TEXT,
        { 0, 992, 1920, 87 },
    },

    // HWND_CHINFO_ETT_TEXT
    {
        HWND_CHINFO_ETT_BG, HWND_CHINFO_ETT_TEXT,
        { 63, 992, 1785, 87 },
    },

    // HWND_CHINFO_BANNER
    {
        HWND_MAINFRAME, HWND_CHINFO_BANNER_PROG_SCRAMBLE_INFO,
        { 1557, 36, 344, 140 },
    },

    // HWND_CHINFO_BANNER_BG
    {
        HWND_CHINFO_BANNER, HWND_CHINFO_BANNER_BG,
        { 1557, 36, 344, 140 },
    },

    // HWND_CHINFO_BANNER_PROG_NUM
    {
        HWND_CHINFO_BANNER, HWND_CHINFO_BANNER_PROG_NUM,
        { 1557, 36, 344, 56 },
    },

    // HWND_CHINFO_BANNER_PROG_NAME
    {
        HWND_CHINFO_BANNER, HWND_CHINFO_BANNER_PROG_NAME,
        { 1557, 88, 344, 56 },
    },

    // HWND_CHINFO_BANNER_PROG_SCRAMBLE_INFO
    {
        HWND_CHINFO_BANNER, HWND_CHINFO_BANNER_PROG_SCRAMBLE_INFO,
        { 1557, 142, 344, 33 },
    },

    // HWND_CHINFO_DIRECT_TUNE_PANEL
    {
        HWND_MAINFRAME, HWND_CHINFO_DIRECT_TUNE_PANEL_TEXT,
        { 23, 28, 306, 81 },
    },

    // HWND_CHINFO_DIRECT_TUNE_PANEL_BG
    {
        HWND_CHINFO_DIRECT_TUNE_PANEL, HWND_CHINFO_DIRECT_TUNE_PANEL_BG,
        { 30, 28, 84, 81 },
    },

    // HWND_CHINFO_DIRECT_TUNE_PANEL_TEXT
    {
        HWND_CHINFO_DIRECT_TUNE_PANEL, HWND_CHINFO_DIRECT_TUNE_PANEL_TEXT,
        { 118, 28, 205, 81 },
    },

};
