////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Dec 18 2014 17:25:00]
/////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////
// MAINFRAME styles..


/////////////////////////////////////////////////////
// BAT_PERCENTPAGE_WINDOW styles..


/////////////////////////////////////////////////////
// BAT_PERCENTPAGE_WINDOW_BG styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Bat_Percentpage_Window_Bg_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_14 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// BAT_PERCENTPAGE_WINDOW_BAR styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Bat_Percentpage_Window_Bar_Normal_DrawStyle[] =
{
    { CP_FILL_RECT, CP_ZUI_FILL_RECT_INDEX_15 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// BAT_PERCENTPAGE_WINDOW_DISCHARGE_ICON styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Bat_Percentpage_Window_Discharge_Icon_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_320 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// BAT_PERCENTPAGE_WINDOW_CHARGE_ICON styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Bat_Percentpage_Window_Charge_Icon_Normal_DrawStyle[] =
{
    { CP_BITMAP, CP_ZUI_BITMAP_INDEX_321 },
    { CP_NOON, 0 },
};

/////////////////////////////////////////////////////
// BAT_PERCENTPAGE_WINDOW_TEXT styles..


/////////////////////////////////////////////////////
// BAT_PERCENTPAGE_WINDOW_VALUE styles..

static DRAWSTYLE _MP_TBLSEG _Zui_Bat_Percentpage_Window_Value_Normal_DrawStyle[] =
{
    { CP_TEXT_OUT, CP_ZUI_TEXT_OUT_INDEX_806 },
    { CP_NOON, 0 },
};

//////////////////////////////////////////////////////
// Window Draw Style List  (normal, focused, disable)

WINDOWDRAWSTYLEDATA _MP_TBLSEG _GUI_WindowsDrawStyleList_Zui_Bat_Percentage[] =
{
    // HWND_MAINFRAME
    { NULL, NULL, NULL     },

    // HWND_BAT_PERCENTPAGE_WINDOW
    { NULL, NULL, NULL     },

    // HWND_BAT_PERCENTPAGE_WINDOW_BG
    { _Zui_Bat_Percentpage_Window_Bg_Normal_DrawStyle, NULL, NULL     },

    // HWND_BAT_PERCENTPAGE_WINDOW_BAR
    { _Zui_Bat_Percentpage_Window_Bar_Normal_DrawStyle, NULL, NULL     },

    // HWND_BAT_PERCENTPAGE_WINDOW_DISCHARGE_ICON
    { _Zui_Bat_Percentpage_Window_Discharge_Icon_Normal_DrawStyle, NULL, NULL     },

    // HWND_BAT_PERCENTPAGE_WINDOW_CHARGE_ICON
    { _Zui_Bat_Percentpage_Window_Charge_Icon_Normal_DrawStyle, NULL, NULL     },

    // HWND_BAT_PERCENTPAGE_WINDOW_TEXT
    { NULL, NULL, NULL     },

    // HWND_BAT_PERCENTPAGE_WINDOW_VALUE
    { _Zui_Bat_Percentpage_Window_Value_Normal_DrawStyle, NULL, NULL     },

};
